window.lang = {
	"es":{
		"label_config_offviewer" : "Vista de espectador apagada",
		"label_config_onviewer" : "Vista de espectador prendida",
		"label_config_stream_pianoon_btn" : "Posición de boton en overlay",
		"label_select_config_position" : "Posición",
		"label_config_playnote_buttons" : "Botones de notas",
		"label_tooltip_scalenotes_bits" : "Notas de escalas bits",
		"label_tooltip_chordnotes_bits" : "Notas de acordes bits",
		"label_tooltip_customnotes_bits" : "Notas personalizadas bits",
		"label_config_playnote_color" : "Color de nota tocada",
		"label_config_btnsave" : "Salvar",
		"label_config_requirements" : "Requerimientos",
		"label_config_requirements_content" : "- Bits activos en tu canal si quieres dejar que tus espectadores las usen por bits<br>",
		"label_config_usage" : "Uso",
		"label_config_usage_content" : "- Guarde la configuración en este panel. <br> - Active el piano desde el tablero o desde la superposición, y / o deje que sus espectadores activen el piano si lo desea. Si elige dejar que se active el piano por bits, si el proceso de bits se completa con éxito, las notas se enviarán a todos los espectadores en el canal y en el chat. <br>",
		"label_config_feedback_text" : "Feedback",
		"label_config_a_send" : "Enviar",
		"label_config_support_text" : "* Si te sirve esta extension tu apoyo es muy bien recibido ",
		"label_overlay_send" : "Enviar",
		"label_config_credits" : "Créditos",
		"tooltip_bits_config_complete" : "envio notas por",
		"tooltip_config_save" : "<p>Configuracion <b class='green-text'>Salvada</b>!</p>",
		"tooltip_custom_notes_empty" : "No dejes ningun campo vacio",
		"tooltip_feedback_ok" : "Gracias por tu feedback, lo mas pronto posible antendere tus comentarios.",
		"tooltip_feedback_error" : "Lo siento, pero hubo un error y no se pudo mandar tu feedback en este momento.",
		"tooltip_bits_error" : "<p>Hubo un error. Intenta de nuevo.</p>",
		"label_leaderboard_tab_pianoon" : "Notas",
		"label_leaderboard_tab_note10" : "Notas 10",
		"label_leaderboard_tab_viwer10" : "Espectadores 10",
		"label_leaderboard_tab_bits10" : "Bits 10",
		"label_leaderboard_viewer" : "Espectador",
		"label_leaderboard_times" : "Veces",
		"label_leaderboard_spend" : "Bits usados",
		"label_select_note" : "Notas",
		"label_select_alterations" : "Alteraciones",
		"label_select_mode" : "Modo",
		"label_play_scale" : "Tocar escala",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes" : "Notas personalizadas",
		"label_tooltip_input_custom" : "<p>Usa letras separadas por coma:<br> C,E,G#,Ab,C</p>",
		"label_play_chord" : "Tocar acorde",
		"label_play_custom" : "Tocar notas",
		"tooltip_feedback_empty" : "No dejes ningun campo vacio"
	},
	"es-mx":{
		"label_config_offviewer" : "Vista de espectador apagada",
		"label_config_onviewer" : "Vista de espectador prendida",
		"label_config_stream_pianoon_btn" : "Posición de boton en overlay",
		"label_select_config_position" : "Posición",
		"label_config_playnote_buttons" : "Botones de notas",
		"label_tooltip_scalenotes_bits" : "Notas de escalas bits",
		"label_tooltip_chordnotes_bits" : "Notas de acordes bits",
		"label_tooltip_customnotes_bits" : "Notas personalizadas bits",
		"label_config_playnote_color" : "Color de nota tocada",
		"label_config_btnsave" : "Salvar",
		"label_config_requirements" : "Requerimientos",
		"label_config_requirements_content" : "- Bits activos en tu canal si quieres dejar que tus espectadores las usen por bits<br>",
		"label_config_usage" : "Uso",
		"label_config_usage_content" : "- Guarde la configuración en este panel. <br> - Active el piano desde el tablero o desde la superposición, y / o deje que sus espectadores activen el piano si lo desea. Si elige dejar que se active el piano por bits, si el proceso de bits se completa con éxito, las notas se enviarán a todos los espectadores en el canal y en el chat. <br>",
		"label_config_feedback_text" : "Feedback",
		"label_config_a_send" : "Enviar",
		"label_config_support_text" : "* Si te sirve esta extension tu apoyo es muy bien recibido ",
		"label_overlay_send" : "Enviar",
		"label_config_credits" : "Créditos",
		"tooltip_bits_config_complete" : "envio notas por",
		"tooltip_config_save" : "<p>Configuracion <b class='green-text'>Salvada</b>!</p>",
		"tooltip_custom_notes_empty" : "No dejes ningun campo vacio",
		"tooltip_feedback_ok" : "Gracias por tu feedback, lo mas pronto posible antendere tus comentarios.",
		"tooltip_feedback_error" : "Lo siento, pero hubo un error y no se pudo mandar tu feedback en este momento.",
		"tooltip_bits_error" : "<p>Hubo un error. Intenta de nuevo.</p>",
		"label_leaderboard_tab_pianoon" : "Notas",
		"label_leaderboard_tab_note10" : "Notas 10",
		"label_leaderboard_tab_viwer10" : "Espectadores 10",
		"label_leaderboard_tab_bits10" : "Bits 10",
		"label_leaderboard_viewer" : "Espectador",
		"label_leaderboard_times" : "Veces",
		"label_leaderboard_spend" : "Bits usados",
		"label_select_note" : "Notas",
		"label_select_alterations" : "Alteraciones",
		"label_select_mode" : "Modo",
		"label_play_scale" : "Tocar escala",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes" : "Notas personalizadas",
		"label_tooltip_input_custom" : "<p>Usa letras separadas por coma:<br> C,E,G#,Ab,C</p>",
		"label_play_chord" : "Tocar acorde",
		"label_play_custom" : "Tocar notas",
		"tooltip_feedback_empty" : "No dejes ningun campo vacio"
	},
	"de":{
		"label_config_offviewer": "Viewer-Ansicht aus",
		"label_config_onviewer": "Viewer-Ansicht ein",
		"label_config_stream_pianoon_btn": "Position der Überlagerungstaste",
		"label_select_config_position": "Position",
		"label_config_playnote_buttons": "Hinweis-Buttons",
		"label_tooltip_scalenotes_bits": "Notizen von Bit-Skalen",
		"label_tooltip_chordnotes_bits": "Noten von Akkordbits",
		"label_tooltip_customnotes_bits": "Benutzerdefinierte Notenbits",
		"label_config_playnote_color": "Notenfarbe gespielt",
		"label_config_btnsave": "Speichern",
		"label_config_requirements": "Bedarf",
		"label_config_requirements_content": "- Aktive Bits in deinem Kanal, wenn du möchtest, dass deine Zuschauer sie bitweise verwenden.",
		"label_config_usage": "Verwenden",
		"label_config_usage_content": "- Speichern Sie die Einstellungen in diesem Bereich. <br> - Aktivieren Sie das Klavier über die Tafel oder das Overlay und / oder lassen Sie Ihre Zuschauer das Klavier aktivieren, wenn Sie dies wünschen. Wenn Sie das Klavier aktivieren lassen möchten Bitweise, wenn der Bitvorgang erfolgreich abgeschlossen wurde, werden die Notizen an alle Zuschauer auf dem Kanal und im Chat gesendet. <br> ",
		"label_config_feedback_text": "Feedback",
		"label_config_a_send": "Senden",
		"label_config_support_text": "* Wenn diese Erweiterung nützlich ist, wird Ihre Unterstützung sehr gut angenommen",
		"label_overlay_send": "Senden",
		"label_config_credits": "Credits",
		"tooltip_bits_config_complete": "Notizen senden von",
		"tooltip_config_save": "<p> Konfiguration <b class='green-text'> Gespeichert </b>! </p>",
		"tooltip_custom_notes_empty": "Lassen Sie keine leeren Felder",
		"tooltip_feedback_ok": "Vielen Dank für Ihr Feedback. Ich werde Ihre Kommentare so schnell wie möglich kommentieren.",
		"tooltip_feedback_error": "Entschuldigung, aber es gab einen Fehler und Ihr Feedback konnte zu diesem Zeitpunkt nicht gesendet werden.",
		"tooltip_bits_error": "<p> Es ist ein Fehler aufgetreten. Versuchen Sie es erneut. </p>",
		"label_leaderboard_tab_pianoon": "Notizen",
		"label_leaderboard_tab_note10": "Notes 10",
		"label_leaderboard_tab_viwer10": "Zuschauer 10",
		"label_leaderboard_tab_bits10": "Bits 10",
		"label_leaderboard_viewer": "Zuschauer",
		"label_leaderboard_times": "Mal",
		"label_leaderboard_spend": "Benutzte Bits",
		"label_select_note": "Notizen",
		"label_select_alterations": "Änderungen",
		"label_select_mode": "Mode",
		"label_play_scale": "Skala abspielen",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Benutzerdefinierte Notizen",
		"label_tooltip_input_custom": "<p> Verwenden Sie durch Kommas getrennte Buchstaben: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Akkord spielen",
		"label_play_custom": "Noten spielen",
		"tooltip_feedback_empty" : "Lassen Sie kein leeres Feld"
	},
	"fr":{
		"label_config_offviewer": "Visualiseur désactivé",
		"label_config_onviewer": "Vue du visualiseur sur",
		"label_config_stream_pianoon_btn": "Position du bouton de superposition",
		"label_select_config_position": "Position",
		"label_config_playnote_buttons": "Boutons de note",
		"label_tooltip_scalenotes_bits": "Notes d'échelles de bits",
		"label_tooltip_chordnotes_bits": "Notes de bits d'accord",
		"label_tooltip_customnotes_bits": "Bits de notes personnalisés",
		"label_config_playnote_color": "Note de couleur jouée",
		"label_config_btnsave": "Enregistrer",
		"label_config_requirements": "Conditions requises",
		"label_config_requirements_content": "- Bits actifs dans votre canal si vous souhaitez laisser vos téléspectateurs les utiliser par bits <br>",
		"label_config_usage": "Utiliser",
		"label_config_usage_content": "- Enregistrez les paramètres dans ce panneau. <br> - Activez le piano à partir du tableau ou de la superposition, et / ou laissez vos téléspectateurs activer le piano si vous le souhaitez. Si vous choisissez de l'activer, par bits, si le processus de traitement des bits est terminé avec succès, les notes sont envoyées à tous les téléspectateurs du canal et du chat. <br> ",
		"label_config_feedback_text": "Commentaires",
		"label_config_a_send": "Envoyer",
		"label_config_support_text": "* Si cette extension est utile, votre assistance est très bien reçue",
		"label_overlay_send": "Envoyer",
		"label_config_credits": "Crédits",
		"tooltip_bits_config_complete": "envoyer des notes par",
		"tooltip_config_save": "<p> Configuration <b class='green-text'> Enregistré </b>! </p>",
		"tooltip_custom_notes_empty": "Ne laissez pas de champs vides",
		"tooltip_feedback_ok": "Merci pour vos commentaires, je vais commenter vos commentaires dès que possible.",
		"tooltip_feedback_error": "Désolé, une erreur s'est produite et vos commentaires n'ont pas pu être envoyés pour le moment.",
		"tooltip_bits_error": "<p> Une erreur s'est produite. Réessayez. </p>",
		"label_leaderboard_tab_pianoon": "Notes",
		"label_leaderboard_tab_note10": "Notes 10",
		"label_leaderboard_tab_viwer10": "Les téléspectateurs 10",
		"label_leaderboard_tab_bits10": "Bits 10",
		"label_leaderboard_viewer": "Visionneuse",
		"label_leaderboard_times": "Fois",
		"label_leaderboard_spend": "Bits utilisés",
		"label_select_note": "Notes",
		"label_select_alterations": "Modifications",
		"label_select_mode": "Mode",
		"label_play_scale": "Jouer à l'échelle",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Notes personnalisées",
		"label_tooltip_input_custom": "<p> Utilisez des lettres séparées par des virgules: <br> C, E, V #, Ab, C </p>",
		"label_play_chord": "Jouer un accord",
		"label_play_custom": "Lire des notes",
		"tooltip_feedback_empty" : "Ne laissez aucun champ vide"
	},
	"ru":{
		"label_config_offviewer": "Просмотр зрителя выключен",
		"label_config_onviewer": "Зритель включен",
		"label_config_stream_pianoon_btn": "Положение кнопки наложения",
		"label_select_config_position": "Позиция",
		"label_config_playnote_buttons": "Кнопки заметок",
		"label_tooltip_scalenotes_bits": "Примечания битовых шкал",
		"label_tooltip_chordnotes_bits": "Ноты битов аккордов",
		"label_tooltip_customnotes_bits": "Биты пользовательских заметок",
		"label_config_playnote_color": "Цвет ноты проигран",
		"label_config_btnsave": "Сохранить",
		"label_config_requirements": "Требования",
		"label_config_requirements_content": "- Активные биты в вашем канале, если вы хотите, чтобы ваши зрители использовали их по битам <br>",
		"label_config_usage": "использование",
		"label_config_usage_content": "- Сохраните настройки на этой панели. <br> - Активируйте пианино с доски или с наложения, и / или позвольте зрителям активировать пианино, если хотите. Если вы решите разрешить пианино активировать по битам, если битовый процесс завершен успешно, заметки будут отправлены всем зрителям на канале и в чате. <br> ",
		"label_config_feedback_text": "Обратная связь",
		"label_config_a_send": "Отправить",
		"label_config_support_text": "* Если это расширение полезно, ваша поддержка очень хорошо принята",
		"label_overlay_send": "Отправить",
		"label_config_credits": "Кредиты",
		"tooltip_bits_config_complete": "отправлять заметки по",
		"tooltip_config_save": "<p> Конфигурация <b class='green-text'> Сохранено </b>! </p>",
		"tooltip_custom_notes_empty": "Не оставляйте пустых полей",
		"tooltip_feedback_ok": "Спасибо за ваш отзыв, как можно скорее я буду комментировать ваши комментарии.",
		"tooltip_feedback_error": "Извините, но произошла ошибка, и ваш отзыв не может быть отправлен в данный момент.",
		"tooltip_bits_error": "<p> Произошла ошибка. Попробуйте еще раз. </p>",
		"label_leaderboard_tab_pianoon": "Примечания",
		"label_leaderboard_tab_note10": "Примечания 10",
		"label_leaderboard_tab_viwer10": "Зрители 10",
		"label_leaderboard_tab_bits10": "Биты 10",
		"label_leaderboard_viewer": "зритель",
		"label_leaderboard_times": "раз",
		"label_leaderboard_spend": "Используемые биты",
		"label_select_note": "Примечания",
		"label_select_alterations": "Изменения",
		"label_select_mode": "Режим",
		"label_play_scale": "Игровой масштаб",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Пользовательские заметки",
		"label_tooltip_input_custom": "<p> Использовать разделенные запятыми буквы: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Играть аккорд",
		"label_play_custom": "Играть ноты",
		"tooltip_feedback_empty" : "Не оставляйте пустое поле"
	},
	"sv":{
		"label_config_offviewer": "Viewer view off",
		"label_config_onviewer": "Viewer view on",
		"label_config_stream_pianoon_btn": "Position för överläggsknapp",
		"label_select_config_position": "Position",
		"label_config_playnote_buttons": "Obs-knappar",
		"label_tooltip_scalenotes_bits": "Anteckningar om bitskalor",
		"label_tooltip_chordnotes_bits": "Anteckningar om ackordbitar",
		"label_tooltip_customnotes_bits": "Anpassade anteckningsbitar",
		"label_config_playnote_color": "Obs färg spelas",
		"label_config_btnsave": "Spara",
		"label_config_requirements": "Krav",
		"label_config_requirements_content": "- Aktiva bitar i din kanal om du vill låta dina tittare använda dem av bitar <br>",
		"label_config_usage": "Använd",
		"label_config_usage_content": "- Spara inställningarna på den här panelen. <br> - Aktivera piano från brädet eller från överlägget, och / eller låt dina tittare aktivera piano om du vill. Om du väljer att låta piano aktivera av bitar, om bitprocessen har slutförts, kommer anteckningarna att skickas till alla tittare på kanalen och i chatten. <br> ",
		"label_config_feedback_text": "Feedback",
		"label_config_a_send": "Skicka",
		"label_config_support_text": "* Om det här tillägget är användbart mottas ditt stöd mycket väl",
		"label_overlay_send": "Skicka",
		"label_config_credits": "Credits",
		"tooltip_bits_config_complete": "skicka anteckningar av",
		"tooltip_config_save": "<p> Konfiguration <b class='green-text'> Sparat </b>! </p>",
		"tooltip_custom_notes_empty": "Lämna inga tomma fält",
		"tooltip_feedback_ok": "Tack för din feedback, så snart som möjligt kommer jag att kommentera dina kommentarer.",
		"tooltip_feedback_error": "Tyvärr, men det var ett fel och din feedback kunde inte skickas just nu.",
		"tooltip_bits_error": "<p> Det uppstod ett fel. Försök igen. </p>",
		"label_leaderboard_tab_pianoon": "Anteckningar",
		"label_leaderboard_tab_note10": "Anteckningar 10",
		"label_leaderboard_tab_viwer10": "Viewers 10",
		"label_leaderboard_tab_bits10": "Bitar 10",
		"label_leaderboard_viewer": "Viewer",
		"label_leaderboard_times": "Times",
		"label_leaderboard_spend": "Begagnade bitar",
		"label_select_note": "Anteckningar",
		"label_select_alterations": "Ändringar",
		"label_select_mode": "Läge",
		"label_play_scale": "Spela skala",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Anpassade anteckningar",
		"label_tooltip_input_custom": "<p> Använd kommaseparerade bokstäver: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Spela ackord",
		"label_play_custom": "Spela anteckningar",
		"tooltip_feedback_empty" : "Lämna inga tomma fält"
	},
	"pt":{
		"label_config_offviewer": "Visualização do visualizador desativada",
		"label_config_onviewer": "Visualização do visualizador ativada",
		"label_config_stream_pianoon_btn": "Posição do botão de sobreposição",
		"label_select_config_position": "Position",
		"label_config_playnote_buttons": "Botões de anotação",
		"label_tooltip_scalenotes_bits": "Notas de escala de bits",
		"label_tooltip_chordnotes_bits": "Notas dos bits dos acordes",
		"label_tooltip_customnotes_bits": "Bits de notas personalizadas",
		"label_config_playnote_color": "Observe a cor reproduzida",
		"label_config_btnsave": "Salvar",
		"label_config_requirements": "Requisitos",
		"label_config_requirements_content": "- Bits ativos em seu canal se você quiser permitir que seus espectadores os usem por bits <br>",
		"label_config_usage": "Usar",
		"label_config_usage_content": "- Salve as configurações neste painel. <br> - Ative o piano a partir do quadro ou da sobreposição e / ou permita que seus visualizadores ativem o piano, se desejar. Se você optar por ativar o piano por bits, se o processo de bits for concluído com êxito, as notas serão enviadas a todos os espectadores no canal e no chat. <br> ",
		"label_config_feedback_text": "Comentários",
		"label_config_a_send": "Enviar",
		"label_config_support_text": "* Se esta extensão for útil, seu suporte será muito bem recebido",
		"label_overlay_send": "Enviar",
		"label_config_credits": "Créditos",
		"tooltip_bits_config_complete": "envie notas por",
		"tooltip_config_save": "<p> Configuração <b class='green-text'> Salva </b>! </p>",
		"tooltip_custom_notes_empty": "Não deixe nenhum campo vazio",
		"tooltip_feedback_ok": "Obrigado por seus comentários, assim que possível, comentarei seus comentários.",
		"tooltip_feedback_error": "Desculpe, mas ocorreu um erro e seu feedback não pôde ser enviado no momento.",
		"tooltip_bits_error": "<p> Ocorreu um erro. Tente novamente. </p>",
		"label_leaderboard_tab_pianoon": "Notas",
		"label_leaderboard_tab_note10": "Notas 10",
		"label_leaderboard_tab_viwer10": "Visualizadores 10",
		"label_leaderboard_tab_bits10": "Bits 10",
		"label_leaderboard_viewer": "Visualizador",
		"label_leaderboard_times": "Vezes",
		"label_leaderboard_spend": "Bits usados",
		"label_select_note": "Notas",
		"label_select_alterations": "Alterações",
		"label_select_mode": "Mode",
		"label_play_scale": "Reproduzir escala",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Notas personalizadas",
		"label_tooltip_input_custom": "<p> Use letras separadas por vírgula: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Tocar acorde",
		"label_play_custom": "Reproduzir notas",
		"tooltip_feedback_empty" : "Não deixe nenhum campo vazio"
	},
	"pt-br":{
		"label_config_offviewer": "Visualização do visualizador desativada",
		"label_config_onviewer": "Visualização do visualizador ativada",
		"label_config_stream_pianoon_btn": "Posição do botão de sobreposição",
		"label_select_config_position": "Position",
		"label_config_playnote_buttons": "Botões de anotação",
		"label_tooltip_scalenotes_bits": "Notas de escala de bits",
		"label_tooltip_chordnotes_bits": "Notas dos bits dos acordes",
		"label_tooltip_customnotes_bits": "Bits de notas personalizadas",
		"label_config_playnote_color": "Observe a cor reproduzida",
		"label_config_btnsave": "Salvar",
		"label_config_requirements": "Requisitos",
		"label_config_requirements_content": "- Bits ativos em seu canal se você quiser permitir que seus espectadores os usem por bits <br>",
		"label_config_usage": "Usar",
		"label_config_usage_content": "- Salve as configurações neste painel. <br> - Ative o piano a partir do quadro ou da sobreposição e / ou permita que seus visualizadores ativem o piano, se desejar. Se você optar por ativar o piano por bits, se o processo de bits for concluído com êxito, as notas serão enviadas a todos os espectadores no canal e no chat. <br> ",
		"label_config_feedback_text": "Comentários",
		"label_config_a_send": "Enviar",
		"label_config_support_text": "* Se esta extensão for útil, seu suporte será muito bem recebido",
		"label_overlay_send": "Enviar",
		"label_config_credits": "Créditos",
		"tooltip_bits_config_complete": "envie notas por",
		"tooltip_config_save": "<p> Configuração <b class='green-text'> Salva </b>! </p>",
		"tooltip_custom_notes_empty": "Não deixe nenhum campo vazio",
		"tooltip_feedback_ok": "Obrigado por seus comentários, assim que possível, comentarei seus comentários.",
		"tooltip_feedback_error": "Desculpe, mas ocorreu um erro e seu feedback não pôde ser enviado no momento.",
		"tooltip_bits_error": "<p> Ocorreu um erro. Tente novamente. </p>",
		"label_leaderboard_tab_pianoon": "Notas",
		"label_leaderboard_tab_note10": "Notas 10",
		"label_leaderboard_tab_viwer10": "Visualizadores 10",
		"label_leaderboard_tab_bits10": "Bits 10",
		"label_leaderboard_viewer": "Visualizador",
		"label_leaderboard_times": "Vezes",
		"label_leaderboard_spend": "Bits usados",
		"label_select_note": "Notas",
		"label_select_alterations": "Alterações",
		"label_select_mode": "Mode",
		"label_play_scale": "Reproduzir escala",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Notas personalizadas",
		"label_tooltip_input_custom": "<p> Use letras separadas por vírgula: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Tocar acorde",
		"label_play_custom": "Reproduzir notas",
		"tooltip_feedback_empty" : "Não deixe nenhum campo vazio"
	},
	"zh":{
		"label_config_offviewer":"查看器视图关闭",
		"label_config_onviewer":"查看器视图打开",
		"label_config_stream_pianoon_btn":"叠加按钮位置",
		"label_select_config_position":"位置",
		"label_config_playnote_buttons":"注释按钮",
		"label_tooltip_scalenotes_bits":"位标度注释",
		"label_tooltip_chordnotes_bits":"和弦音符",
		"label_tooltip_customnotes_bits":"自定义注释位",
		"label_config_playnote_color":"演奏的音符颜色",
		"label_config_btnsave":"保存",
		"label_config_requirements":"要求",
		"label_config_requirements_content":"-如果您想让观众按<br>位使用频道中的有效位,",
		"label_config_usage":"使用",
		"label_config_usage_content":"-将设置保存在此面板中。<br>-如果需要,从面板或覆盖层激活钢琴,和/或让观众激活钢琴。如果选择让钢琴激活按位,如果位处理成功完成,则笔记将发送给频道和聊天中的所有观看者。<br>",
		"label_config_feedback_text":"反馈",
		"label_config_a_send":"发送",
		"label_config_support_text":"*如果此扩展有用,将非常欢迎您的支持",
		"label_overlay_send":"发送",
		"label_config_credits":"信用",
		"tooltip_bits_config_complete":"发送注释者",
		"tooltip_config_save":"<p>配置<b class ='green-text'>已保存</b>！</p>",
		"tooltip_custom_notes_empty":"不要留空字段",
		"tooltip_feedback_ok":"感谢您的反馈,我会尽快评论您的评论。",
		"tooltip_feedback_error":"对不起,但是发生错误,目前无法发送您的反馈。",
		"tooltip_bits_error":"<p>发生错误。请重试。</p>",
		"label_leaderboard_tab_pianoon":"注释",
		"label_leaderboard_tab_note10":"注释10",
		"label_leaderboard_tab_viwer10":"查看者10",
		"label_leaderboard_tab_bits10":"位10",
		"label_leaderboard_viewer":"查看器",
		"label_leaderboard_times":"时间",
		"label_leaderboard_spend":"使用的位",
		"label_select_note":"注释",
		"label_select_alterations":"更改",
		"label_select_mode":"模式",
		"label_play_scale":"播放比例",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes":"自定义注释",
		"label_tooltip_input_custom":"<p>使用逗号分隔的字母:<br> C,E,G＃,Ab,C </p>",
		"label_play_chord":"弹奏和弦",
		"label_play_custom":"播放笔记",
		"tooltip_feedback_empty" : "不要留下任何空白"
	},
	"zh-cn":{
		"label_config_offviewer":"查看器视图关闭",
		"label_config_onviewer":"查看器视图打开",
		"label_config_stream_pianoon_btn":"叠加按钮位置",
		"label_select_config_position":"位置",
		"label_config_playnote_buttons":"注释按钮",
		"label_tooltip_scalenotes_bits":"位标度注释",
		"label_tooltip_chordnotes_bits":"和弦音符",
		"label_tooltip_customnotes_bits":"自定义注释位",
		"label_config_playnote_color":"演奏的音符颜色",
		"label_config_btnsave":"保存",
		"label_config_requirements":"要求",
		"label_config_requirements_content":"-如果您想让观众按<br>位使用频道中的有效位,",
		"label_config_usage":"使用",
		"label_config_usage_content":"-将设置保存在此面板中。<br>-如果需要,从面板或覆盖层激活钢琴,和/或让观众激活钢琴。如果选择让钢琴激活按位,如果位处理成功完成,则笔记将发送给频道和聊天中的所有观看者。<br>",
		"label_config_feedback_text":"反馈",
		"label_config_a_send":"发送",
		"label_config_support_text":"*如果此扩展有用,将非常欢迎您的支持",
		"label_overlay_send":"发送",
		"label_config_credits":"信用",
		"tooltip_bits_config_complete":"发送注释者",
		"tooltip_config_save":"<p>配置<b class ='green-text'>已保存</b>！</p>",
		"tooltip_custom_notes_empty":"不要留空字段",
		"tooltip_feedback_ok":"感谢您的反馈,我会尽快评论您的评论。",
		"tooltip_feedback_error":"对不起,但是发生错误,目前无法发送您的反馈。",
		"tooltip_bits_error":"<p>发生错误。请重试。</p>",
		"label_leaderboard_tab_pianoon":"注释",
		"label_leaderboard_tab_note10":"注释10",
		"label_leaderboard_tab_viwer10":"查看者10",
		"label_leaderboard_tab_bits10":"位10",
		"label_leaderboard_viewer":"查看器",
		"label_leaderboard_times":"时间",
		"label_leaderboard_spend":"使用的位",
		"label_select_note":"注释",
		"label_select_alterations":"更改",
		"label_select_mode":"模式",
		"label_play_scale":"播放比例",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes":"自定义注释",
		"label_tooltip_input_custom":"<p>使用逗号分隔的字母:<br> C,E,G＃,Ab,C </p>",
		"label_play_chord":"弹奏和弦",
		"label_play_custom":"播放笔记",
		"tooltip_feedback_empty" : "不要留下任何空白"
	},
	"zh-tw":{
		"label_config_offviewer":"查看器视图关闭",
		"label_config_onviewer":"查看器视图打开",
		"label_config_stream_pianoon_btn":"叠加按钮位置",
		"label_select_config_position":"位置",
		"label_config_playnote_buttons":"注释按钮",
		"label_tooltip_scalenotes_bits":"位标度注释",
		"label_tooltip_chordnotes_bits":"和弦音符",
		"label_tooltip_customnotes_bits":"自定义注释位",
		"label_config_playnote_color":"演奏的音符颜色",
		"label_config_btnsave":"保存",
		"label_config_requirements":"要求",
		"label_config_requirements_content":"-如果您想让观众按<br>位使用频道中的有效位,",
		"label_config_usage":"使用",
		"label_config_usage_content":"-将设置保存在此面板中。<br>-如果需要,从面板或覆盖层激活钢琴,和/或让观众激活钢琴。如果选择让钢琴激活按位,如果位处理成功完成,则笔记将发送给频道和聊天中的所有观看者。<br>",
		"label_config_feedback_text":"反馈",
		"label_config_a_send":"发送",
		"label_config_support_text":"*如果此扩展有用,将非常欢迎您的支持",
		"label_overlay_send":"发送",
		"label_config_credits":"信用",
		"tooltip_bits_config_complete":"发送注释者",
		"tooltip_config_save":"<p>配置<b class ='green-text'>已保存</b>！</p>",
		"tooltip_custom_notes_empty":"不要留空字段",
		"tooltip_feedback_ok":"感谢您的反馈,我会尽快评论您的评论。",
		"tooltip_feedback_error":"对不起,但是发生错误,目前无法发送您的反馈。",
		"tooltip_bits_error":"<p>发生错误。请重试。</p>",
		"label_leaderboard_tab_pianoon":"注释",
		"label_leaderboard_tab_note10":"注释10",
		"label_leaderboard_tab_viwer10":"查看者10",
		"label_leaderboard_tab_bits10":"位10",
		"label_leaderboard_viewer":"查看器",
		"label_leaderboard_times":"时间",
		"label_leaderboard_spend":"使用的位",
		"label_select_note":"注释",
		"label_select_alterations":"更改",
		"label_select_mode":"模式",
		"label_play_scale":"播放比例",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes":"自定义注释",
		"label_tooltip_input_custom":"<p>使用逗号分隔的字母:<br> C,E,G＃,Ab,C </p>",
		"label_play_chord":"弹奏和弦",
		"label_play_custom":"播放笔记",
		"tooltip_feedback_empty" : "不要留下任何空白"
	},
	"ko":{
		"label_config_offviewer": "뷰어보기 해제",
		"label_config_onviewer": "뷰어보기",
		"label_config_stream_pianoon_btn": "오버레이 버튼 위치",
		"label_select_config_position": "위치",
		"label_config_playnote_buttons": "메모 버튼",
		"label_tooltip_scalenotes_bits": "비트 스케일의 메모",
		"label_tooltip_chordnotes_bits": "코드 비트의 음표",
		"label_tooltip_customnotes_bits": "맞춤 메모 비트",
		"label_config_playnote_color": "노트 색상 연주",
		"label_config_btnsave": "저장",
		"label_config_requirements": "요구 사항",
		"label_config_requirements_content": "-시청자가 비트 <br> 단위로 사용하도록하려면 채널의 활성 비트",
		"label_config_usage": "사용",
		"label_config_usage_content": "-이 패널에서 설정을 저장하십시오. <br>-보드 또는 오버레이에서 피아노를 활성화하거나 원하는 경우 시청자가 피아노를 활성화 시키십시오. 피아노를 활성화 시키려면 비트 단위로 비트 프로세스가 성공적으로 완료되면 메모가 채널 및 채팅의 모든 시청자에게 전송됩니다. <br> ",
		"label_config_feedback_text": "피드백",
		"label_config_a_send": "보내기",
		"label_config_support_text": "*이 확장이 유용하면 지원이 매우 잘 전달됩니다",
		"label_overlay_send": "보내기",
		"label_config_credits": "크레딧",
		"tooltip_bits_config_complete": "노트 보내기",
		"tooltip_config_save": "<p> 구성 <b class='green-text'> 저장 됨 </b>! </p>",
		"tooltip_custom_notes_empty": "빈 필드를 두지 마십시오",
		"tooltip_feedback_ok": "피드백에 대한 의견을 보내 주시면 최대한 빨리 의견을 보내 주셔서 감사합니다.",
		"tooltip_feedback_error": "죄송합니다. 오류가 발생하여 현재 의견을 보내지 못했습니다.",
		"tooltip_bits_error": "<p> 오류가 발생했습니다. 다시 시도하십시오. </p>",
		"label_leaderboard_tab_pianoon": "노트",
		"label_leaderboard_tab_note10": "노트 10",
		"label_leaderboard_tab_viwer10": "뷰어 10",
		"label_leaderboard_tab_bits10": "비트 10",
		"label_leaderboard_viewer": "뷰어",
		"label_leaderboard_times": "시간",
		"label_leaderboard_spend": "사용 된 비트",
		"label_select_note": "노트",
		"label_select_alterations": "변경",
		"label_select_mode": "모드",
		"label_play_scale": "플레이 스케일",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "맞춤 메모",
		"label_tooltip_input_custom": "<p> 쉼표로 구분 된 문자 사용 : <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "코드 연주",
		"label_play_custom": "노트 재생",
		"tooltip_feedback_empty" : "빈 칸을 두지 마십시오"
	},
	"da":{
		"label_config_offviewer": "Viewer view off",
		"label_config_onviewer": "Viewer view on",
		"label_config_stream_pianoon_btn": "Placering af overlay-knap",
		"label_select_config_position": "Position",
		"label_config_playnote_buttons": "Bemærk knapper",
		"label_tooltip_scalenotes_bits": "Noter om bitskalaer",
		"label_tooltip_chordnotes_bits": "Noter om akkordbits",
		"label_tooltip_customnotes_bits": "Brugerdefinerede noter",
		"label_config_playnote_color": "Bemærk farve spillet",
		"label_config_btnsave": "Gem",
		"label_config_requirements": "Krav",
		"label_config_requirements_content": "- Aktive bits i din kanal, hvis du vil lade dine seere bruge dem af bits <br>",
		"label_config_usage": "Brug",
		"label_config_usage_content": "- Gem indstillingerne i dette panel. <br> - Aktivér klaveret fra brættet eller fra overlayet, og / eller lad dine seere aktivere klaveret, hvis du ønsker det. Hvis du vælger at lade klaveret aktivere af bit, hvis bitprocessen er afsluttet, sendes noterne til alle seere på kanalen og i chatten. <br> ",
		"label_config_feedback_text": "Feedback",
		"label_config_a_send": "Send",
		"label_config_support_text": "* Hvis denne udvidelse er nyttig, modtages din support meget godt",
		"label_overlay_send": "Send",
		"label_config_credits": "Credits",
		"tooltip_bits_config_complete": "send noter af",
		"tooltip_config_save": "<p> Konfiguration <b class='green-text'> Gemt </b>! </p>",
		"tooltip_custom_notes_empty": "Efterlad ikke nogen tomme felter",
		"tooltip_feedback_ok": "Tak for din feedback, så snart som muligt kommenterer jeg dine kommentarer.",
		"tooltip_feedback_error": "Beklager, men der var en fejl, og din feedback kunne ikke sendes på dette tidspunkt.",
		"tooltip_bits_error": "<p> Der opstod en fejl. Prøv igen. </p>",
		"label_leaderboard_tab_pianoon": "Noter",
		"label_leaderboard_tab_note10": "Noter 10",
		"label_leaderboard_tab_viwer10": "Seere 10",
		"label_leaderboard_tab_bits10": "Bits 10",
		"label_leaderboard_viewer": "Viewer",
		"label_leaderboard_times": "Times",
		"label_leaderboard_spend": "Brugte bits",
		"label_select_note": "Noter",
		"label_select_alterations": "Ændringer",
		"label_select_mode": "Mode",
		"label_play_scale": "Afspil skala",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Brugerdefinerede noter",
		"label_tooltip_input_custom": "<p> Brug kommaseparerede bogstaver: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Spil akkord",
		"label_play_custom": "Spil noter",
		"tooltip_feedback_empty" : "Efterlad ikke noget tomt felt"
	},
	"it":{
		"label_config_offviewer": "Viewer view off",
		"label_config_onviewer": "Visualizzazione visualizzatore attivata",
		"label_config_stream_pianoon_btn": "Posizione pulsante overlay",
		"label_select_config_position": "Posizione",
		"label_config_playnote_buttons": "Pulsanti nota",
		"label_tooltip_scalenotes_bits": "Note di scale di bit",
		"label_tooltip_chordnotes_bits": "Note di bit di accordi",
		"label_tooltip_customnotes_bits": "Bit di note personalizzate",
		"label_config_playnote_color": "Colore della nota riprodotto",
		"label_config_btnsave": "Salva",
		"label_config_requirements": "Requisiti",
		"label_config_requirements_content": "- Bit attivi nel tuo canale se vuoi che i tuoi spettatori li usino per bit <br>",
		"label_config_usage": "Usa",
		"label_config_usage_content": "- Salva le impostazioni in questo pannello. <br> - Attiva il piano dalla lavagna o dall'overlay e / o lascia che i tuoi spettatori attivino il piano se lo desideri. Se scegli di lasciarlo attivare a bit, se il processo di bit viene completato correttamente, le note verranno inviate a tutti gli spettatori sul canale e nella chat. <br> ",
		"label_config_feedback_text": "Feedback",
		"label_config_a_send": "Invia",
		"label_config_support_text": "* Se questa estensione è utile, il tuo supporto è molto ben accolto",
		"label_overlay_send": "Invia",
		"label_config_credits": "Crediti",
		"tooltip_bits_config_complete": "invia note per",
		"tooltip_config_save": "<p> Configurazione <b class='green-text'> Salvato </b>! </p>",
		"tooltip_custom_notes_empty": "Non lasciare campi vuoti",
		"tooltip_feedback_ok": "Grazie per il tuo feedback, appena possibile commenterò i tuoi commenti.",
		"tooltip_feedback_error": "Siamo spiacenti, ma si è verificato un errore e al momento non è stato possibile inviare il tuo feedback.",
		"tooltip_bits_error": "<p> Si è verificato un errore. Riprova. </p>",
		"label_leaderboard_tab_pianoon": "Note",
		"label_leaderboard_tab_note10": "Note 10",
		"label_leaderboard_tab_viwer10": "Viewers 10",
		"label_leaderboard_tab_bits10": "Bit 10",
		"label_leaderboard_viewer": "Spettatore",
		"label_leaderboard_times": "Volte",
		"label_leaderboard_spend": "Bit usati",
		"label_select_note": "Note",
		"label_select_alterations": "Alterations",
		"label_select_mode": "Mode",
		"label_play_scale": "Riproduci scala",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Note personalizzate",
		"label_tooltip_input_custom": "<p> Usa lettere separate da virgola: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Suonare l'accordo",
		"label_play_custom": "Riproduci note",
		"tooltip_feedback_empty" : "Non lasciare alcun campo vuoto"
	},
	"hu":{
		"label_config_offviewer": "Viewer view off",
		"label_config_onviewer": "Viewer view on",
		"label_config_stream_pianoon_btn": "Overlay gomb pozíciója",
		"label_select_config_position": "Pozíció",
		"label_config_playnote_buttons": "Megjegyzés gombok",
		"label_tooltip_scalenotes_bits": "Bitskála megjegyzések",
		"label_tooltip_chordnotes_bits": "Akkordbitek megjegyzése",
		"label_tooltip_customnotes_bits": "Egyéni jegyzetek bitjei",
		"label_config_playnote_color": "Megjegyzés színét játsszák",
		"label_config_btnsave": "Mentés",
		"label_config_requirements": "Követelmények",
		"label_config_requirements_content": "- Aktív bitjei a csatornádon, ha azt akarja, hogy a nézők bitjekenként használják őket <br>",
		"label_config_usage": "Használat",
		"label_config_usage_content": "- Mentse el a beállításokat ezen a panelen. <br> - Aktiválja a zongorát a tábláról vagy az overlay-ről, és / vagy hagyja, hogy a nézők bekapcsolják a zongorát, ha akarják. Ha úgy dönt, hogy aktiválja a zongorát. bittel, ha a bitfolyamat sikeresen befejeződik, a jegyzeteket a csatorna és a chat összes nézőjének elküldjük. <br> ",
		"label_config_feedback_text": "Visszajelzés",
		"label_config_a_send": "Küldés",
		"label_config_support_text": "* Ha ez a kiterjesztés hasznos, a támogatást nagyon jól fogadják",
		"label_overlay_send": "Küldés",
		"label_config_credits": "Kreditek",
		"tooltip_bits_config_complete": "Jegyzeteket küld",
		"tooltip_config_save": "<p> Konfiguráció <b class='green-text'> Mentett </b>! </p>",
		"tooltip_custom_notes_empty": "Ne hagyjon üres mezőket",
		"tooltip_feedback_ok": "Köszönjük visszajelzését, a lehető leghamarabb megjegyzéseket fűzök hozzászólásodhoz.",
		"tooltip_feedback_error": "Elnézést kérünk, de hiba történt, és visszajelzését nem sikerült elküldeni.",
		"tooltip_bits_error": "<p> Hiba történt. Próbálkozzon újra. </p>",
		"label_leaderboard_tab_pianoon": "hangjegyek",
		"label_leaderboard_tab_note10": "10. megjegyzés",
		"label_leaderboard_tab_viwer10": "10 néző",
		"label_leaderboard_tab_bits10": "10 bit",
		"label_leaderboard_viewer": "Néző",
		"label_leaderboard_times": "Times",
		"label_leaderboard_spend": "Használt bitek",
		"label_select_note": "hangjegyek",
		"label_select_alterations": "Módosítások",
		"label_select_mode": "Mód",
		"label_play_scale": "Játssz skálán",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Egyéni jegyzetek",
		"label_tooltip_input_custom": "<p> Vesszővel elválasztott betűk használata: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Akkord lejátszása",
		"label_play_custom": "Jegyzetek lejátszása",
		"tooltip_feedback_empty" : "Ne hagyjon üres mezőket"
	},
	"nl":{
		"label_config_offviewer": "Viewerweergave uit",
		"label_config_onviewer": "Viewerweergave op",
		"label_config_stream_pianoon_btn": "Positie overlayknop",
		"label_select_config_position": "Positie",
		"label_config_playnote_buttons": "Notitieknoppen",
		"label_tooltip_scalenotes_bits": "Aantekeningen van bitschalen",
		"label_tooltip_chordnotes_bits": "Noten van akkoordbits",
		"label_tooltip_customnotes_bits": "Aangepaste notities bits",
		"label_config_playnote_color": "Notitiekleur gespeeld",
		"label_config_btnsave": "Opslaan",
		"label_config_requirements": "Vereisten",
		"label_config_requirements_content": "- Actieve bits in je kanaal als je je kijkers ze wilt laten gebruiken door bits <br>",
		"label_config_usage": "Gebruik",
		"label_config_usage_content": "- Sla de instellingen in dit paneel op. <br> - Activeer de piano vanaf het bord of vanuit de overlay en / of laat uw kijkers de piano activeren als u dat wilt. Als u ervoor kiest om de piano te activeren door bits, als het bitproces met succes is voltooid, worden de notities verzonden naar alle kijkers op het kanaal en in de chat. <br> ",
		"label_config_feedback_text": "Feedback",
		"label_config_a_send": "Verzenden",
		"label_config_support_text": "* Als deze extensie nuttig is, wordt uw ondersteuning zeer goed ontvangen",
		"label_overlay_send": "Verzenden",
		"label_config_credits": "Credits",
		"tooltip_bits_config_complete": "stuur notities door",
		"tooltip_config_save": "<p> Configuratie <b class='green-text'> Opgeslagen </b>! </p>",
		"tooltip_custom_notes_empty": "Laat geen lege velden achter",
		"tooltip_feedback_ok": "Bedankt voor uw feedback, ik zal zo snel mogelijk reageren op uw opmerkingen.",
		"tooltip_feedback_error": "Sorry, maar er is een fout opgetreden en uw feedback kon op dit moment niet worden verzonden.",
		"tooltip_bits_error": "<p> Er is een fout opgetreden. Probeer het opnieuw. </p>",
		"label_leaderboard_tab_pianoon": "Notes",
		"label_leaderboard_tab_note10": "Notes 10",
		"label_leaderboard_tab_viwer10": "Viewers 10",
		"label_leaderboard_tab_bits10": "Bits 10",
		"label_leaderboard_viewer": "Viewer",
		"label_leaderboard_times": "Keer",
		"label_leaderboard_spend": "Gebruikte bits",
		"label_select_note": "Notes",
		"label_select_alterations": "wijzigingen",
		"label_select_mode": "Mode",
		"label_play_scale": "Speelschaal",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Custom notes",
		"label_tooltip_input_custom": "<p> Gebruik door komma's gescheiden letters: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Akkoord spelen",
		"label_play_custom": "Notities spelen",
		"tooltip_feedback_empty" : "Laat geen leeg veld achter"
	},
	"no":{
		"label_config_offviewer": "Viewer view off",
		"label_config_onviewer": "Viewer view on",
		"label_config_stream_pianoon_btn": "Posisjon for overleggsknapp",
		"label_select_config_position": "Posisjon",
		"label_config_playnote_buttons": "Merknadsknapper",
		"label_tooltip_scalenotes_bits": "Merknader om biteskalaer",
		"label_tooltip_chordnotes_bits": "Merknader om akkordbiter",
		"label_tooltip_customnotes_bits": "Egendefinerte notatbiter",
		"label_config_playnote_color": "Merk farge spilt",
		"label_config_btnsave": "Lagre",
		"label_config_requirements": "Krav",
		"label_config_requirements_content": "- Aktive biter i kanalen din hvis du vil la seerne bruke dem av biter <br>",
		"label_config_usage": "Bruk",
		"label_config_usage_content": "- Lagre innstillingene i dette panelet. <br> - Aktiver pianoet fra brettet eller fra overlegget, og / eller la seerne aktivere pianoet hvis du vil. Hvis du velger å la pianoet aktivere etter bit, hvis bitprosessen er fullført, vil notatene bli sendt til alle seere på kanalen og i chatten. <br> ",
		"label_config_feedback_text": "Tilbakemelding",
		"label_config_a_send": "Send",
		"label_config_support_text": "* Hvis denne utvidelsen er nyttig, blir støtten din veldig godt mottatt",
		"label_overlay_send": "Send",
		"label_config_credits": "studiepoeng",
		"tooltip_bits_config_complete": "send notater av",
		"tooltip_config_save": "<p> Konfigurasjon <b class='green-text'> Lagret </b>! </p>",
		"tooltip_custom_notes_empty": "Ikke legg igjen noen tomme felt",
		"tooltip_feedback_ok": "Takk for tilbakemeldingen, så snart som mulig vil jeg kommentere kommentarene dine.",
		"tooltip_feedback_error": "Beklager, men det var en feil, og tilbakemeldingene dine kunne ikke sendes på dette tidspunktet.",
		"tooltip_bits_error": "<p> Det oppstod en feil. Prøv igjen. </p>",
		"label_leaderboard_tab_pianoon": "Merknader",
		"label_leaderboard_tab_note10": "Merknader 10",
		"label_leaderboard_tab_viwer10": "Seere 10",
		"label_leaderboard_tab_bits10": "Bits 10",
		"label_leaderboard_viewer": "Viewer",
		"label_leaderboard_times": "ganger",
		"label_leaderboard_spend": "Brukte biter",
		"label_select_note": "Merknader",
		"label_select_alterations": "Endringer",
		"label_select_mode": "Mode",
		"label_play_scale": "Spill skala",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Egendefinerte notater",
		"label_tooltip_input_custom": "<p> Bruk kommaseparerte bokstaver: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Spill akkord",
		"label_play_custom": "Spill notater",
		"tooltip_feedback_empty" : "Ikke la noe tomt felt"
	},
	"ro":{
		"label_config_offviewer": "Vizualizare dezactivată",
		"label_config_onviewer": "Vizualizare afișat la",
		"label_config_stream_pianoon_btn": "Poziția butonului de suprapunere",
		"label_select_config_position": "Poziție",
		"label_config_playnote_buttons": "Butoane de notare",
		"label_tooltip_scalenotes_bits": "Note de cântare de biți",
		"label_tooltip_chordnotes_bits": "Note de biți de acord",
		"label_tooltip_customnotes_bits": "Biți de note personalizate",
		"label_config_playnote_color": "Notați culoarea jucată",
		"label_config_btnsave": "Salvați",
		"label_config_requirements": "Cerințe",
		"label_config_requirements_content": "- Bit-uri active în canalul dvs. dacă doriți să permiteți spectatorilor să le folosească de biți pe",
		"label_config_usage": "Utilizați",
		"label_config_usage_content": "- Salvați setările din acest panou. <br> - Activați pianul de pe placă sau de la suprapunere și / sau lăsați spectatorii să activeze pianul dacă doriți. Dacă alegeți să lăsați pianul să activeze pe biți, dacă procesul de biți este finalizat cu succes, notele vor fi trimise tuturor spectatorilor de pe canal și din chat. <br> ",
		"label_config_feedback_text": "Feedback",
		"label_config_a_send": "Trimite",
		"label_config_support_text": "* Dacă această extensie este utilă, suportul dvs. este foarte bine primit",
		"label_overlay_send": "Trimite",
		"label_config_credits": "Credite",
		"tooltip_bits_config_complete": "trimite note după",
		"tooltip_config_save": "<p> Configurare <b class='green-text'> Salvat </b>! </p>",
		"tooltip_custom_notes_empty": "Nu lăsați câmpuri goale",
		"tooltip_feedback_ok": "Vă mulțumim pentru feedback, cât de curând posibil voi face comentarii.",
		"tooltip_feedback_error": "Ne pare rău, dar a existat o eroare, iar feedback-ul dvs. nu a putut fi trimis în acest moment.",
		"tooltip_bits_error": "<p> A apărut o eroare. Încercați din nou. </p>",
		"label_leaderboard_tab_pianoon": "Note",
		"label_leaderboard_tab_note10": "Note 10",
		"label_leaderboard_tab_viwer10": "Viewers 10",
		"label_leaderboard_tab_bits10": "Bits 10",
		"label_leaderboard_viewer": "Viewer",
		"label_leaderboard_times": "Times",
		"label_leaderboard_spend": "Biți folosiți",
		"label_select_note": "Note",
		"label_select_alterations": "Modificări",
		"label_select_mode": "Mod",
		"label_play_scale": "Scara de joc",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Note personalizate",
		"label_tooltip_input_custom": "<p> Folosiți litere separate prin virgulă: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Corde de joc",
		"label_play_custom": "Note de redare",
		"tooltip_feedback_empty" : "Nu lăsați niciun câmp gol"
	},
	"sk":{
		"label_config_offviewer": "Pogled gledalca izklopljen",
		"label_config_onviewer": "Pogled gledalca naprej",
		"label_config_stream_pianoon_btn": "Položaj gumba za prekrivanje",
		"label_select_config_position": "Položaj",
		"label_config_playnote_buttons": "Gumbi za opombo",
		"label_tooltip_scalenotes_bits": "Opombe bitnih lestvic",
		"label_tooltip_chordnotes_bits": "Opombe bordov akordov",
		"label_tooltip_customnotes_bits": "Bilješke po meri",
		"label_config_playnote_color": "Igrala se je barva note",
		"label_config_btnsave": "Shrani",
		"label_config_requirements": "Zahteve",
		"label_config_requirements_content": "- Aktivni biti v vašem kanalu, če želite svojim gledalcem omogočiti, da jih uporabljajo z bitovi <br>",
		"label_config_usage": "Uporabi",
		"label_config_usage_content": "- Shranite nastavitve na tej plošči. <br> - Aktivirajte klavir s plošče ali s prekrivke in / ali pustite svojim gledalcem, da po potrebi aktivirajo klavir. Če želite pustiti, da se klavir aktivira z biti, če je bitni postopek uspešno zaključen, bodo opombe poslane vsem gledalcem na kanalu in v klepetu. <br> ",
		"label_config_feedback_text": "Povratne informacije",
		"label_config_a_send": "Pošlji",
		"label_config_support_text": "* Če je ta razširitev uporabna, je vaša podpora zelo dobro sprejeta",
		"label_overlay_send": "Pošlji",
		"label_config_credits": "Zasluge",
		"tooltip_bits_config_complete": "pošiljanje zapiskov s",
		"tooltip_config_save": "<p> Konfiguracija <b class='green-text'> Shranjena </b>! </p>",
		"tooltip_custom_notes_empty": "Ne puščajte praznih polj",
		"tooltip_feedback_ok": "Hvala za povratne informacije, čim prej bom razumel vaše komentarje.",
		"tooltip_feedback_error": "Oprosti, vendar je prišlo do napake in povratnih informacij trenutno ni bilo mogoče poslati.",
		"tooltip_bits_error": "<p> Prišlo je do napake. Poskusite znova. </p>",
		"label_leaderboard_tab_pianoon": "Opombe",
		"label_leaderboard_tab_note10": "Opombe 10",
		"label_leaderboard_tab_viwer10": "Gledalcev 10",
		"label_leaderboard_tab_bits10": "Biti 10",
		"label_leaderboard_viewer": "Pregledovalnik",
		"label_leaderboard_times": "Časi",
		"label_leaderboard_spend": "Uporabljeni biti",
		"label_select_note": "Opombe",
		"label_select_alterations": "Spremembe",
		"label_select_mode": "Način",
		"label_play_scale": "Lestvica predvajanja",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Opombe po meri",
		"label_tooltip_input_custom": "<p> Uporabi ločene z vejicami črke: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Predvajaj akord",
		"label_play_custom": "Predvajaj zapiske",
		"tooltip_feedback_empty" : "Ne puščajte praznega polja"
	},
	"fi":{
		"label_config_offviewer": "Viewer view off",
		"label_config_onviewer": "Katseluohjelma päällä",
		"label_config_stream_pianoon_btn": "Peittopainikkeen sijainti",
		"label_select_config_position": "Sijainti",
		"label_config_playnote_buttons": "Muistipainikkeet",
		"label_tooltip_scalenotes_bits": "bittivaakojen muistiinpanot",
		"label_tooltip_chordnotes_bits": "Akordibittien muistiinpanot",
		"label_tooltip_customnotes_bits": "Muokatut muistiinpanobitit",
		"label_config_playnote_color": "Muistiinpanon väri soitettu",
		"label_config_btnsave": "Tallenna",
		"label_config_requirements": "Vaatimukset",
		"label_config_requirements_content": "- Kanavasi aktiiviset bitit, jos haluat antaa katsojille käyttää niitä bittiä <br> <br>",
		"label_config_usage": "Käytä",
		"label_config_usage_content": "- Tallenna asetukset tähän paneeliin. <br> - Aktivoi piano pöydältä tai peittoalueelta ja / tai anna katsojien aktivoida piano, jos haluat. Jos päätät antaa pianon aktivoida. bittiä kohti, jos bittiprosessi suoritetaan onnistuneesti, muistiinpanot lähetetään kaikille kanavan ja chatin katsojille. <br> ",
		"label_config_feedback_text": "Palaute",
		"label_config_a_send": "Lähetä",
		"label_config_support_text": "* Jos tämä laajennus on hyödyllinen, tuki on saanut erittäin hyvän vastaanoton",
		"label_overlay_send": "Lähetä",
		"label_config_credits": "Laajuudet",
		"tooltip_bits_config_complete": "lähetä muistiinpanoja",
		"tooltip_config_save": "<p> Määritykset <b class='green-text'> Tallennettu </b>! </p>",
		"tooltip_custom_notes_empty": "Älä jätä tyhjiä kenttiä",
		"tooltip_feedback_ok": "Kiitos palautteestasi, kommentoin kommentteja niin pian kuin mahdollista.",
		"tooltip_feedback_error": "Anteeksi, mutta tapahtui virhe ja palautetta ei voitu lähettää tällä hetkellä.",
		"tooltip_bits_error": "<p> Oli virhe. Yritä uudelleen. </p>",
		"label_leaderboard_tab_pianoon": "Notes",
		"label_leaderboard_tab_note10": "Notes 10",
		"label_leaderboard_tab_viwer10": "Katsojat 10",
		"label_leaderboard_tab_bits10": "Bittejä 10",
		"label_leaderboard_viewer": "katsoja",
		"label_leaderboard_times": "Ajat",
		"label_leaderboard_spend": "Käytetyt bitit",
		"label_select_note": "Notes",
		"label_select_alterations": "Muutokset",
		"label_select_mode": "Mode",
		"label_play_scale": "Pelaa mittakaavaa",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Mukautetut muistiinpanot",
		"label_tooltip_input_custom": "<p> Käytä pilkuilla erotettuja kirjaimia: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Soita sointu",
		"label_play_custom": "Toista muistiinpanot",
		"tooltip_feedback_empty" : "Älä jätä tyhjää kenttää"
	},
	"tr":{
		"label_config_offviewer": "Görüntüleyici görünümü kapalı",
		"label_config_onviewer": "İzleyici görünümü açık",
		"label_config_stream_pianoon_btn": "Yerleşim düğmesi konumu",
		"label_select_config_position": "Konum",
		"label_config_playnote_buttons": "Not düğmeleri",
		"label_tooltip_scalenotes_bits": "Bit ölçekleri notları",
		"label_tooltip_chordnotes_bits": "Akor bitlerinin notları",
		"label_tooltip_customnotes_bits": "Özel notlar bit",
		"label_config_playnote_color": "Oynatılan nota rengi",
		"label_config_btnsave": "Kaydet",
		"label_config_requirements": "Gereksinimler",
		"label_config_requirements_content": "- İzleyicilerinizin bunları bitlerle kullanmasına izin vermek istiyorsanız kanalınızdaki etkin bitler <br>",
		"label_config_usage": "Kullanım",
		"label_config_usage_content": "- Ayarları bu panelde kaydedin. - - Piyanoyu panodan veya yer paylaşımından etkinleştirin ve / veya isterseniz izleyicilerin piyanoyu etkinleştirmesine izin verin. Piyanonun etkinleştirilmesine izin vermek isterseniz bit işlemi ile bit işlemi başarıyla tamamlanırsa, notlar kanaldaki ve sohbetteki tüm izleyicilere gönderilir. <br> ",
		"label_config_feedback_text": "Geribildirim",
		"label_config_a_send": "Gönder",
		"label_config_support_text": "* Bu uzantı yararlıysa, desteğiniz çok iyi karşılanır",
		"label_overlay_send": "Gönder",
		"label_config_credits": "Kredi",
		"tooltip_bits_config_complete": "notları gönder",
		"tooltip_config_save": "<p> Yapılandırma <b class='green-text'> Kayıtlı </b>! </p>",
		"tooltip_custom_notes_empty": "Boş alan bırakmayın",
		"tooltip_feedback_ok": "Geri bildiriminiz için teşekkür ederiz, en kısa zamanda yorumlarınız hakkında yorum yapacağım.",
		"tooltip_feedback_error": "Üzgünüz, ancak bir hata oluştu ve geri bildiriminiz şu anda gönderilemedi.",
		"tooltip_bits_error": "<p> Bir hata oluştu. Tekrar deneyin. </p>",
		"label_leaderboard_tab_pianoon": "Notlar",
		"label_leaderboard_tab_note10": "Notlar 10",
		"label_leaderboard_tab_viwer10": "Görüntüleyenler 10",
		"label_leaderboard_tab_bits10": "Bit 10",
		"label_leaderboard_viewer": "Görüntüleyici",
		"label_leaderboard_times": "Kez",
		"label_leaderboard_spend": "Kullanılmış bitler",
		"label_select_note": "Notlar",
		"label_select_alterations": "Değişiklikler",
		"label_select_mode": "Mod",
		"label_play_scale": "Oynatma ölçeği",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Özel notlar",
		"label_tooltip_input_custom": "<p> Virgülle ayrılmış harfler kullanın: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Akor çal",
		"label_play_custom": "Notları oynat",
		"tooltip_feedback_empty" : "Boş alan bırakmayın"
	},
	"cs":{
		"label_config_offviewer": "Viewer view off",
		"label_config_onviewer": "Viewer view on",
		"label_config_stream_pianoon_btn": "Pozice tlačítka překrytí",
		"label_select_config_position": "Position",
		"label_config_playnote_buttons": "Note buttons",
		"label_tooltip_scalenotes_bits": "Notes of bit scale",
		"label_tooltip_chordnotes_bits": "Poznámky k akordovým bitům",
		"label_tooltip_customnotes_bits": "Bity vlastních poznámek",
		"label_config_playnote_color": "Barva poznámky byla přehrávána",
		"label_config_btnsave": "Uložit",
		"label_config_requirements": "Požadavky",
		"label_config_requirements_content": "- Aktivní bity ve vašem kanálu, pokud chcete, aby je diváci mohli používat podle bitů <br>",
		"label_config_usage": "Použití",
		"label_config_usage_content": "- Uložte nastavení do tohoto panelu. <br> - Aktivujte klavír z hracího plánu nebo z překryvné vrstvy a / nebo nechte diváky aktivovat klavír, pokud si přejete. Pokud se rozhodnete nechat piano aktivovat po bitech, pokud je bitový proces úspěšně dokončen, budou poznámky zaslány všem divákům na kanálu a v chatu. <br> ",
		"label_config_feedback_text": "Zpětná vazba",
		"label_config_a_send": "Odeslat",
		"label_config_support_text": "* Pokud je toto rozšíření užitečné, je vaše podpora velmi dobře přijata",
		"label_overlay_send": "Odeslat",
		"label_config_credits": "Úvěry",
		"tooltip_bits_config_complete": "posílat poznámky od",
		"tooltip_config_save": "<p> Konfigurace <b class='green-text'> Uloženo </b>! </p>",
		"tooltip_custom_notes_empty": "Nenechávejte žádná prázdná pole",
		"tooltip_feedback_ok": "Děkuji za vaše hodnocení, jakmile to bude možné, porozumím vašim komentářům.",
		"tooltip_feedback_error": "Litujeme, ale došlo k chybě a vaše zpětná vazba se v tuto chvíli nemohla odeslat.",
		"tooltip_bits_error": "<p> Došlo k chybě. Zkuste to znovu. </p>",
		"label_leaderboard_tab_pianoon": "Noty",
		"label_leaderboard_tab_note10": "Noty 10",
		"label_leaderboard_tab_viwer10": "Viewers 10",
		"label_leaderboard_tab_bits10": "Bits 10",
		"label_leaderboard_viewer": "Divák",
		"label_leaderboard_times": "Krát",
		"label_leaderboard_spend": "Použité bity",
		"label_select_note": "Noty",
		"label_select_alterations": "Alterations",
		"label_select_mode": "Mode",
		"label_play_scale": "Přehrát měřítko",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Vlastní poznámky",
		"label_tooltip_input_custom": "<p> Použijte písmena oddělená čárkami: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Přehrát akord",
		"label_play_custom": "Přehrát poznámky",
		"tooltip_feedback_empty" : "Nenechávejte prázdné pole"
	},
	"bg":{
		"label_config_offviewer": "Изгледът на зрителя е изключен",
		"label_config_onviewer": "Изглед на зрителя на",
		"label_config_stream_pianoon_btn": "Позиция на бутона на наслагване",
		"label_select_config_position": "Позиция",
		"label_config_playnote_buttons": "Бутони за бележка",
		"label_tooltip_scalenotes_bits": "Бележки за битови скали",
		"label_tooltip_chordnotes_bits": "Бележки за битовете на акордите",
		"label_tooltip_customnotes_bits": "Персонализирани битове за бележки",
		"label_config_playnote_color": "Забележка игран цвят",
		"label_config_btnsave": "Запазване",
		"label_config_requirements": "Изисквания",
		"label_config_requirements_content": "- Активни битове във вашия канал, ако искате да разрешите на зрителите да ги използват по битове <br>",
		"label_config_usage": "Използване",
		"label_config_usage_content": "- Запазете настройките в този панел. <br> - Активирайте пианото от дъската или от наслагването и / или оставете зрителите си да активират пианото, ако желаете. Ако решите да оставите пианото да се активира по битове, ако битовият процес приключи успешно, бележките ще бъдат изпратени до всички зрители на канала и в чата. <br> ",
		"label_config_feedback_text": "Обратна връзка",
		"label_config_a_send": "Изпращане",
		"label_config_support_text": "* Ако това разширение е полезно, вашата подкрепа е много добре приета",
		"label_overlay_send": "Изпращане",
		"label_config_credits": "Кредити",
		"tooltip_bits_config_complete": "изпращане на бележки от",
		"tooltip_config_save": "<p> Конфигурация <b class='green-text'> Записан </b>! </p>",
		"tooltip_custom_notes_empty": "Не оставяйте празни полета",
		"tooltip_feedback_ok": "Благодаря ви за отзивите, възможно най-скоро ще коментирам вашите коментари.",
		"tooltip_feedback_error": "Съжалявам, но възникна грешка и обратната връзка не може да бъде изпратена понастоящем.",
		"tooltip_bits_error": "<p> Възникна грешка. Опитайте отново. </p>",
		"label_leaderboard_tab_pianoon": "Бележки",
		"label_leaderboard_tab_note10": "Бележки 10",
		"label_leaderboard_tab_viwer10": "Зрители 10",
		"label_leaderboard_tab_bits10": "Битове 10",
		"label_leaderboard_viewer": "Преглед",
		"label_leaderboard_times": "пъти",
		"label_leaderboard_spend": "Използвани битове",
		"label_select_note": "Бележки",
		"label_select_alterations": "Промени",
		"label_select_mode": "Режим",
		"label_play_scale": "Скала за възпроизвеждане",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Персонализирани бележки",
		"label_tooltip_input_custom": "<p> Използвайте букви, разделени със запетая: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Възпроизвеждане на акорд",
		"label_play_custom": "Възпроизвеждане на бележки",
		"tooltip_feedback_empty" : "Не оставяйте празно поле"
	},
	"pl":{
		"label_config_offviewer": "Widok przeglądarki wyłączony",
		"label_config_onviewer": "Widok przeglądarki włączony",
		"label_config_stream_pianoon_btn": "Położenie przycisku nakładki",
		"label_select_config_position": "Pozycja",
		"label_config_playnote_buttons": "Przyciski notatek",
		"label_tooltip_scalenotes_bits": "Uwagi o skalach bitowych",
		"label_tooltip_chordnotes_bits": "Nuty bitów akordów",
		"label_tooltip_customnotes_bits": "Niestandardowe bity notatek",
		"label_config_playnote_color": "Odtwarzany kolor notatki",
		"label_config_btnsave": "Zapisz",
		"label_config_requirements": "Wymagania",
		"label_config_requirements_content": "- Aktywne bity na Twoim kanale, jeśli chcesz, aby widzowie używali ich bitami <br>",
		"label_config_usage": "Użyj",
		"label_config_usage_content": "- Zapisz ustawienia w tym panelu. <br> - Aktywuj pianino z planszy lub z nakładki i / lub pozwól swoim widzom aktywować pianino, jeśli chcesz. Jeśli zdecydujesz się na aktywację pianina bitami, jeśli proces bitowy zakończy się pomyślnie, notatki zostaną wysłane do wszystkich widzów na kanale i na czacie. <br> ",
		"label_config_feedback_text": "Feedback",
		"label_config_a_send": "Wyślij",
		"label_config_support_text": "* Jeśli to rozszerzenie jest przydatne, twoje wsparcie jest bardzo dobrze odbierane",
		"label_overlay_send": "Wyślij",
		"label_config_credits": "Kredyty",
		"tooltip_bits_config_complete": "wysyłaj notatki przez",
		"tooltip_config_save": "<p> Konfiguracja <b class='green-text'> Zapisano </b>! </p>",
		"tooltip_custom_notes_empty": "Nie zostawiaj żadnych pustych pól",
		"tooltip_feedback_ok": "Dziękuję za opinie, jak najszybciej skomentuję twoje komentarze.",
		"tooltip_feedback_error": "Przepraszamy, ale wystąpił błąd i w tej chwili nie można wysłać Twojej opinii.",
		"tooltip_bits_error": "<p> Wystąpił błąd. Spróbuj ponownie. </p>",
		"label_leaderboard_tab_pianoon": "Notatki",
		"label_leaderboard_tab_note10": "Uwagi 10",
		"label_leaderboard_tab_viwer10": "Przeglądający 10",
		"label_leaderboard_tab_bits10": "Bity 10",
		"label_leaderboard_viewer": "Przeglądarka",
		"label_leaderboard_times": "Times",
		"label_leaderboard_spend": "Używane bity",
		"label_select_note": "Notatki",
		"label_select_alterations": "Alterations",
		"label_select_mode": "Tryb",
		"label_play_scale": "Odtwórz skalę",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "Niestandardowe notatki",
		"label_tooltip_input_custom": "<p> Użyj liter oddzielonych przecinkami: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Odtwórz akord",
		"label_play_custom": "Odtwórz notatki",
		"tooltip_feedback_empty" : "Nie pozostawiaj pustego pola"
	},
	"el":{
		"label_config_offviewer": "Προβολή εκτός προβολής",
		"label_config_onviewer": "Εμφάνιση προβολής προβολής",
		"label_config_stream_pianoon_btn": "Θέση κουμπιού επικάλυψης",
		"label_select_config_position": "Θέση",
		"label_config_playnote_buttons": "Κουμπιά σημείωσης",
		"label_tooltip_scalenotes_bits": "Σημειώσεις ζυγοί bit",
		"label_tooltip_chordnotes_bits": "Σημειώσεις χορδών",
		"label_tooltip_customnotes_bits": "Προσαρμοσμένα κομμάτια σημειώσεων",
		"label_config_playnote_color": "Έγινε αναπαραγωγή χρώματος",
		"label_config_btnsave": "Αποθήκευση",
		"label_config_requirements": "Απαιτήσεις",
		"label_config_requirements_content": "- Ενεργά bits στο κανάλι σας, εάν θέλετε να επιτρέψετε στους θεατές σας να τα χρησιμοποιούν με bits <br>",
		"label_config_usage": "Χρήση",
		"label_config_usage_content": "- Αποθήκευση των ρυθμίσεων σε αυτόν τον πίνακα. - Ενεργοποιήστε το πιάνο από το σκάφος ή από την επικάλυψη και / ή αφήστε τους θεατές να ενεργοποιήσουν το πιάνο, αν το επιθυμείτε. με δυαδικά ψηφία, αν η διαδικασία bit ολοκληρωθεί με επιτυχία, οι σημειώσεις θα αποσταλούν σε όλους τους θεατές στο κανάλι και στη συνομιλία.",
		"label_config_feedback_text": "Σχόλια",
		"label_config_a_send": "Αποστολή",
		"label_config_support_text": "* Εάν αυτή η επέκταση είναι χρήσιμη, η υποστήριξή σας λαμβάνει πολύ καλά",
		"label_overlay_send": "Αποστολή",
		"label_config_credits": "Πιστώσεις",
		"tooltip_bits_config_complete": "αποστολή σημειώσεων από",
		"tooltip_config_save": "<p> Διαμόρφωση <b class='πράσινο κείμενο»> Αποθηκευμένο </b>! </p>",
		"tooltip_custom_notes_empty": "Μην αφήνετε κενά πεδία",
		"tooltip_feedback_ok": "Σας ευχαριστώ για τα σχόλιά σας, το συντομότερο δυνατό θα σχολιάσω τα σχόλιά σας.",
		"tooltip_feedback_error": "Λυπούμαστε, αλλά παρουσιάστηκε ένα σφάλμα και τα σχόλιά σας δεν ήταν δυνατό να σταλούν αυτήν τη στιγμή.",
		"tooltip_bits_error": "<p> Παρουσιάστηκε σφάλμα. Δοκιμάστε ξανά. </p>",
		"label_leaderboard_tab_pianoon": "Σημειώσεις",
		"label_leaderboard_tab_note10": "Σημειώσεις 10",
		"label_leaderboard_tab_viwer10": "Προβολείς 10",
		"label_leaderboard_tab_bits10": "Μπιτς 10",
		"label_leaderboard_viewer": "Προβολή",
		"label_leaderboard_times": "Φορές",
		"label_leaderboard_spend": "Μεταχειρισμένα bits",
		"label_select_note": "Σημειώσεις",
		"label_select_alterations": "Τροποποιήσεις",
		"label_select_mode": "Λειτουργία",
		"label_play_scale": "Κλίμακα αναπαραγωγής",
		"label_select_second" : "2α",
		"label_select_third" : "3α",
		"label_select_fourth" : "4α",
		"label_select_fith" : "5α",
		"label_select_six" : "6α",
		"label_select_seven" : "7α",
		"label_select_nine" : "9α",
		"label_select_eleven" : "11α",
		"label_select_thirteen" : "13α",
		"custom_notes": "Προσαρμοσμένες σημειώσεις",
		"label_tooltip_input_custom": "<p> Χρησιμοποιήστε γράμματα χωρισμένα με κόμμα: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "Αναπαραγωγή χορδή",
		"label_play_custom": "Αναπαραγωγή σημειώσεων",
		"tooltip_feedback_empty" : "Μην αφήνετε κανένα κενό πεδίο"
	},
	"vi":{
		"label_config_offviewer" : "Người xem tắt",
		"label_config_onviewer" : "Lượt xem",
		"label_config_stream_pianoon_btn" : "Vị trí nút lớp phủ",
		"label_select_config_position" : "Vị trí",
		"label_config_playnote_buttons" : "Nút ghi chú",
		"label_tooltip_scalenotes_bits" : "Ghi chú tỷ lệ bit",
		"label_tooltip_chordnotes_bits" : "Ghi chú của các hợp âm bit",
		"label_tooltip_customnotes_bits" : "Bit ghi chú tùy chỉnh",
		"label_config_playnote_color" : "Ghi chú màu đã chơi",
		"label_config_btnsave" : "Lưu lại",
		"label_config_requirements" : "Yêu cầu",
		"label_config_requirements_content" : "- Các bit hoạt động trong kênh của bạn nếu bạn muốn cho phép người xem sử dụng chúng theo bit <br>",
		"label_config_usage" : "Sử dụng",
		"label_config_usage_content" : "- Lưu các cài đặt trong bảng này. <br> - Kích hoạt piano từ bảng hoặc từ lớp phủ và / hoặc để người xem của bạn kích hoạt piano nếu bạn muốn. Nếu bạn chọn để piano được kích hoạt bằng bit, nếu quá trình bit được hoàn thành thành công, các ghi chú sẽ được gửi đến tất cả người xem trên kênh và trong cuộc trò chuyện. <br>",
		"label_config_feedback_text" : "Phản hồi",
		"label_config_a_send" : "Gửi",
		"label_config_support_text" : "* Nếu tiện ích mở rộng này giúp bạn, sự hỗ trợ của bạn rất được đón nhận",
		"label_overlay_send" : "Gửi",
		"label_config_credits" : "Tín dụng",
		"tooltip_bits_config_complete" : "Tôi gửi ghi chú của",
		"tooltip_config_save" : "<p> Cấu hình <b class='green-text'> Đã lưu </b>! </p>",
		"tooltip_custom_notes_empty" : "Đừng để bất kỳ trường trống",
		"tooltip_feedback_ok" : "Cảm ơn phản hồi của bạn, càng sớm càng tốt tôi sẽ hiểu ý kiến của bạn.",
		"tooltip_feedback_error" : "Tôi xin lỗi, nhưng đã xảy ra lỗi và không thể gửi phản hồi của bạn tại thời điểm này.",
		"tooltip_bits_error" : "<p> Đã xảy ra lỗi. Hãy thử lại. </p>",
		"label_leaderboard_tab_pianoon" : "Ghi chú",
		"label_leaderboard_tab_note10" : "Ghi chú 10",
		"label_leaderboard_tab_viwer10" : "Khán giả 10",
		"label_leaderboard_tab_bits10" : "Bits 10",
		"label_leaderboard_viewer" : "Khán giả",
		"label_leaderboard_times" : "Thời đại",
		"label_leaderboard_spend" : "Bit được sử dụng",
		"label_select_note" : "Ghi chú",
		"label_select_alterations" : "Thay đổi",
		"label_select_mode" : "Chế độ",
		"label_play_scale" : "Chơi quy mô",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes" : "Ghi chú tùy chỉnh",
		"label_tooltip_input_custom" : "<p>Sử dụng các chữ cái được phân tách bằng dấu phẩy:<br> C,E,G#,Ab,C</p>",
		"label_play_chord" : "Chơi hợp âm",
		"label_play_custom" : "Chơi ghi chú",
		"tooltip_feedback_empty" : "Đừng để bất kỳ trường trống"
	},
	"ja":{
		"label_config_offviewer" : "ビューアービューオフ",
		"label_config_onviewer" : "ビューアビュー",
		"label_config_stream_pianoon_btn" : "オーバーレイボタンの位置",
		"label_select_config_position" : "役職",
		"label_config_playnote_buttons" : "ノートボタン",
		"label_tooltip_scalenotes_bits" : "ビットスケールノート",
		"label_tooltip_chordnotes_bits" : "コードビットのメモ",
		"label_tooltip_customnotes_bits" : "カスタムノートビット",
		"label_config_playnote_color" : "再生された音色",
		"label_config_btnsave" : "保存する",
		"label_config_requirements" : "必要条件",
		"label_config_requirements_content" : "-視聴者にビット単位で使用させたい場合は、チャンネル内のアクティブなビット<br>",
		"label_config_usage" : "使用する",
		"label_config_usage_content" : "-このパネルで設定を保存します。 <br>-ボードまたはオーバーレイからピアノを有効にします。また、必要に応じて視聴者にピアノを有効にします。 ピアノをビットでアクティベートすることを選択した場合、ビットプロセスが正常に完了すると、チャンネルおよびチャットのすべての視聴者にノートが送信されます。 <br>",
		"label_config_feedback_text" : "フィードバック",
		"label_config_a_send" : "送る",
		"label_config_support_text" : "*この拡張機能が役立つ場合、サポートは非常に好評です",
		"label_overlay_send" : "送る",
		"label_config_credits" : "クレジット",
		"tooltip_bits_config_complete" : "メモを送信します",
		"tooltip_config_save" : "<p>設定<b class='green-text'>保存済み</b>！</p>",
		"tooltip_custom_notes_empty" : "空のフィールドを残さないでください",
		"tooltip_feedback_ok" : "ご意見をお寄せいただきありがとうございます。できるだけ早くあなたのコメントを理解します。",
		"tooltip_feedback_error" : "申し訳ありませんが、エラーが発生したため、現時点ではフィードバックを送信できませんでした。",
		"tooltip_bits_error" : "<p>エラーが発生しました。 もう一度やり直してください。</p>",
		"label_leaderboard_tab_pianoon" : "注釈",
		"label_leaderboard_tab_note10" : "注釈 10",
		"label_leaderboard_tab_viwer10" : "観客 10",
		"label_leaderboard_tab_bits10" : "ビット 10",
		"label_leaderboard_viewer" : "観客",
		"label_leaderboard_times" : "回",
		"label_leaderboard_spend" : "使用済みビット",
		"label_select_note" : "注釈",
		"label_select_alterations" : "変更",
		"label_select_mode" : "モード",
		"label_play_scale" : "プレイスケール",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes" : "注釈 習慣",
		"label_tooltip_input_custom" : "<p>コンマ区切りの文字を使用します。<br> C,E,G#,Ab,C</p>",
		"label_play_chord" : "コードを弾く",
		"label_play_custom" : "メモを再生",
		"tooltip_feedback_empty" : "空のフィールドを残さないでください"
	},
	"th":{
		"label_config_offviewer": "ปิดมุมมองผู้ชม",
		"label_config_onviewer": "มุมมอง ผู้ชม บน",
		"label_config_stream_pianoon_btn": "ตำแหน่งปุ่มซ้อนทับ",
		"label_select_config_position": "ตำแหน่ง",
		"label_config_playnote_buttons": "ปุ่มบันทึกย่อ",
		"label_tooltip_scalenotes_bits": "หมายเหตุของบิตสเกล",
		"label_tooltip_chordnotes_bits": "หมายเหตุ ของบิตคอร์ด",
		"label_tooltip_customnotes_bits": "บิตบันทึกย่อที่กำหนดเอง",
		"label_config_playnote_color": "เล่นโน้ตสีแล้ว",
		"label_config_btnsave": "บันทึก",
		"label_config_requirements": "ข้อกำหนด",
		"label_config_requirements_content": "- บิตที่ใช้งานอยู่ในช่องของคุณหากคุณต้องการให้ผู้ดูใช้บิตเป็นบิต",
		"label_config_usage": "ใช้",
		"label_config_usage_content": "- บันทึกการตั้งค่าในแผงนี้ <br> - เปิดใช้งานเปียโนจากบอร์ดหรือจากการซ้อนทับและ / หรือให้ผู้ชมเปิดใช้งานเปียโนหากคุณต้องการหากคุณต้องการให้เปียโนเปิดใช้งาน โดยบิตหากกระบวนการบิตเสร็จสมบูรณ์แล้วบันทึกจะถูกส่งไปยังผู้ชมทั้งหมดในช่องและในการแชท <br> ",
		"label_config_feedback_text": "คำติชม",
		"label_config_a_send": "ส่ง",
		"label_config_support_text": "* หากส่วนขยายนี้มีประโยชน์การสนับสนุนของคุณจะได้รับอย่างดี",
		"label_overlay_send": "ส่ง",
		"label_config_credits": "เครดิต",
		"tooltip_bits_config_complete": "ส่งโน้ตโดย",
		"tooltip_config_save": "<p> การกำหนดค่า <b class='ข้อความสีเขียว'> บันทึกแล้ว </b>! </p>",
		"tooltip_custom_notes_empty": "อย่าเว้นช่องว่างไว้",
		"tooltip_feedback_ok": "ขอบคุณสำหรับความคิดเห็นของคุณโดยเร็วที่สุดฉันจะแสดงความคิดเห็นในความคิดเห็นของคุณ",
		"tooltip_feedback_error": "ขออภัยมีข้อผิดพลาดและไม่สามารถส่งความคิดเห็นของคุณได้ในเวลานี้",
		"tooltip_bits_error": "<p> มีข้อผิดพลาดลองอีกครั้ง </p>",
		"label_leaderboard_tab_pianoon": "หมายเหตุ",
		"label_leaderboard_tab_note10": "หมายเหตุ 10",
		"label_leaderboard_tab_viwer10": "ผู้ชม 10",
		"label_leaderboard_tab_bits10": "Bits 10",
		"label_leaderboard_viewer": "ผู้ชม",
		"label_leaderboard_times": "ไทม์ส",
		"label_leaderboard_spend": "บิตที่ใช้",
		"label_select_note": "หมายเหตุ",
		"label_select_alterations": "การปรับเปลี่ยน",
		"label_select_mode": "โหมด",
		"label_play_scale": "เล่นสเกล",
		"label_select_second" : "2a",
		"label_select_third" : "3a",
		"label_select_fourth" : "4a",
		"label_select_fith" : "5a",
		"label_select_six" : "6a",
		"label_select_seven" : "7a",
		"label_select_nine" : "9a",
		"label_select_eleven" : "11a",
		"label_select_thirteen" : "13a",
		"custom_notes": "บันทึกย่อที่กำหนดเอง",
		"label_tooltip_input_custom": "<p> ใช้ตัวอักษรที่คั่นด้วยจุลภาค: <br> C, E, G #, Ab, C </p>",
		"label_play_chord": "เล่นคอร์ด",
		"label_play_custom": "เล่นโน้ต",
		"tooltip_feedback_empty" : "อย่าปล่อยให้ฟิลด์ใด ๆ ว่างเปล่า"
	}
};