window.lang = {
	"es":{
		"label_config_image" : "Imagen",
		"label_config_title" : "titulo",
		"label_config_font" : "Fuente",
		"label_config_glow_light" : "Color claro",
		"label_config_glow_dark" : "Color obscuro",
		"label_select_config_position" : "Posicion",
		"label_select_config_fadein" : "Fadein de animacion",
		"label_select_config_fadeout" : "Fadeout de animacion",
		"label_select_config_type" : "Tipo de imagen",
		"label_select_config_shape" : "Forma de imagen",
		"label_config_timeout" : "Timeout de alerta",
		"label_config_timeout_tooltiped" : "Timeout de alerta",
		"label_config_btnsave" : "salvar",
		"label_config_btnreset" : "limpiar",
		"label_config_requirements" : "Requerimientos",
		"label_config_requirements_content" : "- Bits activos en tu canal<br>",
		"label_config_usage" : "Uso",
		"label_config_usage_content" : "- En este panel salva la configuracion para cada pupface(9).<br>&nbsp; . Imagen.<br>&nbsp; . Titulo.<br>&nbsp; . Color.<br>&nbsp; . Posicion.<br>&nbsp; . Fadein de animacion.<br>&nbsp; . Fadeout de animacion.<br>&nbsp; . Tipo.<br>&nbsp; . Forma.<br>&nbsp; . Duracion.<br>- Deja que tus viewers usen las pupfaces.<br>&nbsp; . Se pueden probar antes de enviar por bits.<br>&nbsp;&nbsp; . La alerta se mostrara solo en el player de quien hace la prueba.<br>&nbsp; . Si el proceso de bits se completa con exito, la alerta se envia a todos los viewers.<br>",
		"label_config_feedback_text" : "Feedback",
		"label_config_a_send" : "Enviar",
		"label_config_support_text" : "* Si te sirve esta extension tu apoyo es muy bien recibido ",
		"label_config_font_color" : "Color de fuente",
		"label_config_btntest" : "Probar",
		"label_overlay_preview" : "Vista previa",
		"label_overlay_send" : "Enviar",
		"label_config_credits" : "Créditos",
		"label_config_volumen" : "Volumen de audio",
		"label_config_stream_pupface_btn" : "Botón pupfaces en stream",
		"tooltip_bits_config_complete" : "envio una pupface por",
		"label_config_volumen_tooltiped" : "Volumen de audio",
		"label_config_confetti" : "Confetti",
		"tooltip_invalid_ext" : "<p>Extension invalida<br>Por favor intenta de nuevo</p>",
		"tooltip_invalid_format" : "<p>Formato invalido<br>Por favor intenta de nuevo</p>",
		"tooltip_config_save" : "<p>Configuracion <b class='green-text'>Salvada</b>!</p>",
		"tooltip_reset_tiers" : "<p>Los 9 tiers van a ser reinicializados. <br> ¿Estas seguro?<br><br><a class='btnAccept green white-text btn'>Si</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>No</a></p>",
		"tooltip_reset_ok" : "<p>Configuracion <b class='red-text'>reinicializada</b>!</p>",
		"tooltip_feedback_empty" : "No dejes ningun campo vacio",
		"tooltip_feedback_ok" : "Gracias por tu feedback, lo mas pronto posible antendere tus comentarios.",
		"tooltip_feedback_error" : "Lo siento, pero hubo un error y no se pudo mandar tu feedback en este momento.",
		"tooltip_bits_error" : "<p>Hubo un error. Intenta de nuevo.</p>",
		"tooltip_config_select_audio" : "Audio",
		"tooltiped_label_config_audio" : "Usa un link publico de dropbox como este:<br><br><b>https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0</b><br><br>Formatos válidos: <br>.mp3, .wav, .ogg",
		"label_config_iconres" : "Respuesta de chat",
		"label_leaderboard_viewer" : "Espectador",
		"label_leaderboard_times" : "Veces",
		"label_leaderboard_spend" : "Bits usados",
	},
	"es-mx":{
		"label_config_image" : "Imagen",
		"label_config_title" : "titulo",
		"label_config_font" : "Fuente",
		"label_config_glow_light" : "Color claro",
		"label_config_glow_dark" : "Color obscuro",
		"label_select_config_position" : "Posicion",
		"label_select_config_fadein" : "Fadein de animacion",
		"label_select_config_fadeout" : "Fadeout de animacion",
		"label_select_config_type" : "Tipo de imagen",
		"label_select_config_shape" : "Forma de imagen",
		"label_config_timeout" : "Timeout de alerta",
		"label_config_timeout_tooltiped" : "Timeout de alerta",
		"label_config_btnsave" : "salvar",
		"label_config_btnreset" : "limpiar",
		"label_config_requirements" : "Requerimientos",
		"label_config_requirements_content" : "- Bits activos en tu canal<br>",
		"label_config_usage" : "Uso",
		"label_config_usage_content" : "- En este panel salva la configuracion para cada pupface(9).<br>&nbsp; . Imagen.<br>&nbsp; . Titulo.<br>&nbsp; . Color.<br>&nbsp; . Posicion.<br>&nbsp; . Fadein de animacion.<br>&nbsp; . Fadeout de animacion.<br>&nbsp; . Tipo.<br>&nbsp; . Forma.<br>&nbsp; . Duracion.<br>- Deja que tus viewers usen las pupfaces.<br>&nbsp; . Se pueden probar antes de enviar por bits.<br>&nbsp;&nbsp; . La alerta se mostrara solo en el player de quien hace la prueba.<br>&nbsp; . Si el proceso de bits se completa con exito, la alerta se envia a todos los viewers.<br>",
		"label_config_feedback_text" : "Feedback",
		"label_config_a_send" : "Enviar",
		"label_config_support_text" : "* Si te sirve esta extension tu apoyo es muy bien recibido ",
		"label_config_font_color" : "Color de fuente",
		"label_config_btntest" : "Probar",
		"label_overlay_preview" : "Vista previa",
		"label_overlay_send" : "Enviar",
		"label_config_credits" : "Créditos",
		"label_config_volumen" : "Volumen de audio",
		"label_config_volumen_tooltiped" : "Volumen de audio",
		"label_config_confetti" : "Confetti",
		"label_config_stream_pupface_btn" : "Botón pupfaces en stream",
		"tooltip_bits_config_complete" : "envio una pupface por",
		"tooltip_invalid_ext" : "<p>Extension invalida<br>Por favor intenta de nuevo</p>",
		"tooltip_invalid_format" : "<p>Formato invalido<br>Por favor intenta de nuevo</p>",
		"tooltip_config_save" : "<p>Configuracion <b class='green-text'>Salvada</b>!</p>",
		"tooltip_reset_tiers" : "<p>Los 9 tiers van a ser reinicializados. <br> ¿Estas seguro?<br><br><a class='btnAccept green white-text btn'>Si</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>No</a></p>",
		"tooltip_reset_ok" : "<p>Configuracion <b class='red-text'>reinicializada</b>!</p>",
		"tooltip_feedback_empty" : "No dejes ningun campo vacio",
		"tooltip_feedback_ok" : "Gracias por tu feedback, lo mas pronto posible antendere tus comentarios.",
		"tooltip_feedback_error" : "Lo siento, pero hubo un error y no se pudo mandar tu feedback en este momento.",
		"tooltip_bits_error" : "<p>Hubo un error. Intenta de nuevo.</p>",
		"tooltip_config_select_audio" : "Audio",
		"tooltiped_label_config_audio" : "Usa un link publico de dropbox como este:<br><br><b>https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0</b><br><br>Formatos válidos: <br>.mp3, .wav, .ogg",
		"label_config_iconres" : "Respuesta de chat",
		"label_leaderboard_viewer" : "Espectador",
		"label_leaderboard_times" : "Veces",
		"label_leaderboard_spend" : "Bits usados"
	},
	"de":{
		"label_config_image" : "Bild",
		"label_config_title" : "Titel",
		"label_config_font" : "Schriftart",
		"label_config_glow_light" : "Lichtfarbe",
		"label_config_glow_dark" : "Dunkle Farbe",
		"label_select_config_position" : "Position",
		"label_select_config_fadein" : "Animation Fadein",
		"label_select_config_fadeout" : "Animation Fadein",
		"label_select_config_type" : "Bildtyp",
		"label_select_config_shape" : "Bildform",
		"label_config_timeout" : "Benachrichtigungs-Timeout",
		"label_config_timeout_tooltiped" : "Benachrichtigungs-Timeout",
		"label_config_btnsave" : "speichern",
		"label_config_btnreset" : "aufräumen",
		"label_config_requirements" : "Anforderungen",
		"label_config_requirements_content" : "- Aktive Bits in deinem Kanal<br>",
		"label_config_usage" : "Verwenden Sie",
		"label_config_usage_content" : "- In diesem Panel speichern Sie die Konfiguration für jedes Pupface (9).<br>&nbsp; . Bild.<br>&nbsp; . Titel.<br>&nbsp; . Farbe.<br>&nbsp; . Position.<br>&nbsp; . Animation Fadein.<br>&nbsp; . Animation Fadein.<br>&nbsp; . Typ.<br>&nbsp; . Form.<br>&nbsp; . Dauer.<br>- Lassen Sie Ihre Zuschauer die Pupfaces benutzen.<br>&nbsp; . Sie können vor dem Versand getestet werden.<br>&nbsp;&nbsp; . Der Alarm wird nur im Videoplayer der Person angezeigt, die den Test durchführt.<br>&nbsp; . Wenn der Bitprozess erfolgreich abgeschlossen wurde, wird die Warnung an alle Betrachter gesendet.<br>",
		"label_config_feedback_text" : "Feedback",
		"label_config_a_send" : "Senden",
		"label_config_support_text" : "* Wenn Ihnen diese Erweiterung hilft, wird Ihre Unterstützung sehr gut angenommen ",
		"label_config_font_color" : "Schriftfarbe",
		"label_config_btntest" : "Versuchen Sie es",
		"label_overlay_preview" : "Vorschau",
		"label_overlay_send" : "Senden",
		"label_config_credits" : "Credits",
		"label_config_volumen" : "Audio-Lautstärke",
		"label_config_volumen_tooltiped" : "Audio-Lautstärke",
		"label_config_confetti" : "Konfetti",
		"label_config_stream_pupface_btn" : "Schaltfläche Pupfaces streamen",
		"tooltip_bits_config_complete" : "schickte ein pupface für",
		"tooltip_invalid_ext" : "<p>Ungültige Erweiterung<br>Bitte versuchen Sie es erneut</p>",
		"tooltip_invalid_format" : "<p>Ungültiges Format<br>Bitte versuchen Sie es erneut</p>",
		"tooltip_config_save" : "<p>Konfiguration <b class='green-text'>gespeichert</b>!</p>",
		"tooltip_reset_tiers" : "<p>Die 9 Ebenen werden zurückgesetzt. <br> Bist du dir sicher?<br><br><a class='btnAccept green white-text btn'>Ja</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>Nein</a></p>",
		"tooltip_reset_ok" : "<p>Einstellungen <b class='red-text'>zurücksetzen</b>!</p>",
		"tooltip_feedback_empty" : "Lassen Sie kein leeres Feld",
		"tooltip_feedback_ok" : "Vielen Dank für Ihr Feedback. Ich werde Ihre Kommentare so schnell wie möglich verstehen.",
		"tooltip_feedback_error" : "Entschuldigung, aber es gab einen Fehler und Ihr Feedback konnte zu diesem Zeitpunkt nicht gesendet werden.",
		"tooltip_bits_error" : "<p>Es ist ein Fehler aufgetreten. Versuchen Sie es noch einmal.</p>",
		"tooltip_config_select_audio" : "Audio",
		"tooltiped_label_config_audio" : "Verwenden Sie einen öffentlichen Dropbox-Link wie diesen: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> <br> Formate Gültig: <br> .mp3, .wav, .ogg",
		"label_config_iconres" : "Chat-Antwort",
		"label_leaderboard_viewer" : "Zuschauer",
		"label_leaderboard_times" : "Times",
		"label_leaderboard_spend" : "Benutzte Bits"
	},
	"fr":{
		"label_config_image" : "Photo",
		"label_config_title" : "titre",
		"label_config_font" : "typographie",
		"label_config_glow_light" : "Couleur claire",
		"label_config_glow_dark" : "Couleur foncée",
		"label_select_config_position" : "Position",
		"label_select_config_fadein" : "Fadein d'animation",
		"label_select_config_fadeout" : "Fondu d'animation",
		"label_select_config_type" : "Type d'image",
		"label_select_config_shape" : "Formulaire d'image",
		"label_config_timeout" : "Délai d'alerte",
		"label_config_timeout_tooltiped" : "Délai d'alerte",
		"label_config_btnsave" : "sauvegarder",
		"label_config_btnreset" : "nettoyer",
		"label_config_requirements" : "Les exigences",
		"label_config_requirements_content" : "- Bits actifs dans votre canal<br>",
		"label_config_usage" : "Utiliser",
		"label_config_usage_content" : "- Dans ce panneau, enregistrez la configuration pour chaque pupface (9).<br>&nbsp; . Photo.<br>&nbsp; . titre.<br>&nbsp; . Couleur.<br>&nbsp; . Position.<br>&nbsp; . Fadein d'animation.<br>&nbsp; . Fondu d'animation.<br>&nbsp; . Type d'image.<br>&nbsp; . Formulaire d'image.<br>&nbsp; . Délai d'alerte.<br>- Laissez vos spectateurs utiliser les pupfaces.<br>&nbsp; . Ils peuvent être testés avant l'envoi par bits.<br>&nbsp;&nbsp; . L'alerte sera affichée uniquement sur le joueur qui teste.<br>&nbsp; . Si le processus de bit est terminé avec succès, l'alerte est envoyée à tous les téléspectateurs..<br>",
		"label_config_feedback_text" : "Retour d'information",
		"label_config_a_send" : "Envoyer",
		"label_config_support_text" : "* Si cette extension vous aide, votre support est très bien reçu ",
		"label_config_font_color" : "Couleur de la police",
		"label_config_btntest" : "Tester",
		"label_overlay_preview" : "Aperçu",
		"label_overlay_send" : "Envoyer",
		"label_config_volumen" : "volume audio",
		"label_config_volumen_tooltiped" : "volume audio",
		"label_config_confetti" : "Confettis",
		"label_config_stream_pupface_btn" : "Bouton Stream pupfaces",
		"label_config_credits": "Crédits",
		"tooltip_bits_config_complete" : "envoyé un pupface pour",
		"tooltip_invalid_ext" : "<p>Extension invalide<br>Veuillez réessayer</p>",
		"tooltip_invalid_format" : "<p>Formato invalido<br>Format invalide</p>",
		"tooltip_config_save" : "<p>Configuration <b class='green-text'>sauvegardée</b>!</p>",
		"tooltip_reset_tiers" : "<p>Les 9 niveaux vont être réinitialisés.<br> Tu es sûr?<br><br><a class='btnAccept green white-text btn'>Oui</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>Non</a></p>",
		"tooltip_reset_ok" : "<p><b class='red-text'>Réinitialiser</b> les paramètres!</p>",
		"tooltip_feedback_empty" : "Ne laissez aucun champ vide",
		"tooltip_feedback_ok" : "Merci pour vos commentaires, dès que possible je comprendrai vos commentaires.",
		"tooltip_feedback_error" : "Je suis désolé, mais il y avait une erreur et vos commentaires n'ont pas pu être envoyés pour le moment.",
		"tooltip_bits_error" : "<p>Il y a eu une erreur. Tente à nouveau.</p>",
		"tooltip_config_select_audio" : "Audio",
		"tooltiped_label_config_audio" : "Utilisez un lien de liste déroulante public comme celui-ci: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> Formats Valide: .mp3, .wav, .ogg",
		"label_config_iconres" : "Réponse de chat",
		"label_leaderboard_viewer" : "Spectateur",
		"label_leaderboard_times" : "Fois",
		"label_leaderboard_spend" : "Bits utilisés"
	},
	"ru":{
		"label_config_image" : "картина",
		"label_config_title" : "название",
		"label_config_font" : "книгопечатание",
		"label_config_glow_light" : "Светлый цвет",
		"label_config_glow_dark" : "Темный цвет",
		"label_select_config_position" : "положение",
		"label_select_config_fadein" : "Анимация увядает",
		"label_select_config_fadeout" : "Исчезновение анимации",
		"label_select_config_type" : "Тип изображения",
		"label_select_config_shape" : "Форма изображения",
		"label_config_timeout" : "Тайм-аут оповещения",
		"label_config_timeout_tooltiped" : "Тайм-аут оповещения",
		"label_config_btnsave" : "экономить",
		"label_config_btnreset" : "убирать",
		"label_config_requirements" : "требования",
		"label_config_requirements_content" : "- Активные биты в вашем канале<br>",
		"label_config_usage" : "использование",
		"label_config_usage_content" : "- В этой панели сохраните конфигурацию для каждого ученика (9)<br>&nbsp; . картина.<br>&nbsp; . название.<br>&nbsp; . цвет.<br>&nbsp; . положение.<br>&nbsp; . Анимация увядает.<br>&nbsp; . Исчезновение анимации.<br>&nbsp; . тип.<br>&nbsp; . форма.<br>&nbsp; . продолжительность.<br>- Пусть ваши зрители используют Pupfaces.<br>&nbsp; . Они могут быть проверены перед отправкой битами.<br>&nbsp;&nbsp; . Предупреждение будет отображаться только на игроке, который тестирует.<br>&nbsp; . Если битовый процесс завершен успешно, предупреждение отправляется всем зрителям.<br>",
		"label_config_feedback_text" : "Обратная связь",
		"label_config_a_send" : "послать",
		"label_config_support_text" : "* Если это расширение поможет вам, ваша поддержка будет принята очень хорошо ",
		"label_config_font_color" : "Цвет шрифта",
		"label_config_btntest" : "пробовать",
		"label_overlay_preview" : "предварительный просмотр",
		"label_overlay_send" : "послать",
		"label_config_volumen" : "громкость звука",
		"label_config_volumen_tooltiped" : "громкость звука",
		"label_config_confetti" : "конфетти",
		"label_config_stream_pupface_btn" : "Кнопка потоковых пупов",
		"label_config_credits": "кредиты",
		"tooltip_bits_config_complete" : "послал ученицу для",
		"tooltip_invalid_ext" : "<p>Неверное расширение<br>Пожалуйста, попробуйте еще раз</p>",
		"tooltip_invalid_format" : "<p>Неверный формат<br>Пожалуйста, попробуйте еще раз</p>",
		"tooltip_config_save" : "<p>Конфигурация <b class='green-text'>сохранена</b>!</p>",
		"tooltip_reset_tiers" : "<p>9 уровней будут сброшены. <br> Ты уверен<br><br><a class='btnAccept green white-text btn'>если</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>не</a></p>",
		"tooltip_reset_ok" : "<p>Сбросить <b class='red-text'>настройки</b>!</p>",
		"tooltip_feedback_empty" : "Не оставляйте пустое поле",
		"tooltip_feedback_ok" : "Спасибо за ваш отзыв, как можно скорее я пойму ваши комментарии.",
		"tooltip_feedback_error" : "Извините, но произошла ошибка, и ваш отзыв не может быть отправлен в данный момент.",
		"tooltip_bits_error" : "<p>Произошла ошибка Попробуй еще раз</p>",
		"tooltip_config_select_audio" : "аудио",
		"tooltiped_label_config_audio" : "Используйте общедоступную ссылку для размещения сообщений, например: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> <br> Форматы Действительно: <br> .mp3, .wav, .ogg",
		"label_config_iconres" : "Ответ в чате",
		"label_leaderboard_viewer" : "зритель",
		"label_leaderboard_times" : "раз",
		"label_leaderboard_spend" : "Используемые биты"
	},
	"sv":{
		"label_config_image" : "bild",
		"label_config_title" : "titel",
		"label_config_font" : "göra",
		"label_config_glow_light" : "Ljus färg",
		"label_config_glow_dark" : "Mörk färg",
		"label_select_config_position" : "ställning",
		"label_select_config_fadein" : "Animering fadein",
		"label_select_config_fadeout" : "Animering fadeout",
		"label_select_config_type" : "Bildtyp",
		"label_select_config_shape" : "Bildform",
		"label_config_timeout" : "Timeout för varning",
		"label_config_timeout_tooltiped" : "Timeout för varning",
		"label_config_btnsave" : "spara",
		"label_config_btnreset" : "städa upp",
		"label_config_requirements" : "krav",
		"label_config_requirements_content" : "- Aktiva bitar i din kanal<br>",
		"label_config_usage" : "användning",
		"label_config_usage_content" : "- I den här panelen sparar du konfigurationen för varje pupface (9).<br>&nbsp; . bild.<br>&nbsp; . titel.<br>&nbsp; . färg.<br>&nbsp; . ställning.<br>&nbsp; . Animering fadein.<br>&nbsp; . Animering fadeout.<br>&nbsp; . Typ.<br>&nbsp; . form.<br>&nbsp; . varaktighet.<br>- Låt dina tittare använda pupfaces.<br>&nbsp; . De kan testas innan de skickas med bitar.<br>&nbsp;&nbsp; . Varningen visas endast på spelaren som testar.<br>&nbsp; . Om bitprocessen har slutförts, skickas varningen till alla tittare.<br>",
		"label_config_feedback_text" : "Återkoppling",
		"label_config_a_send" : "skicka",
		"label_config_support_text" : "* Om det här tillägget hjälper dig mottas ditt stöd mycket väl ",
		"label_config_font_color" : "Teckensnitt färg",
		"label_config_btntest" : "prova",
		"label_overlay_preview" : "förhandsvisning",
		"label_overlay_send" : "skicka",
		"label_config_volumen" : "ljudvolym",
		"label_config_volumen_tooltiped" : "ljudvolym",
		"label_config_confetti" : "konfetti",
		"label_config_stream_pupface_btn" : "Ström på pupfaces-knappen",
		"label_config_credits": "hp",
		"tooltip_bits_config_complete" : "skickade en valp för",
		"tooltip_invalid_ext" : "<p>Ogiltig tillägg<br>Försök igen</p>",
		"tooltip_invalid_format" : "<p>Ogiltigt format<br>Försök igen</p>",
		"tooltip_config_save" : "<p>Konfiguration <b class='green-text'>sparad</b>!</p>",
		"tooltip_reset_tiers" : "<p>De 9 nivåerna återställs. <br> Är du säker<br><br><a class='btnAccept green white-text btn'>om</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>inte</a></p>",
		"tooltip_reset_ok" : "<p>Återställ <b class='red-text'>inställningar</b>!</p>",
		"tooltip_feedback_empty" : "Lämna inga tomma fält",
		"tooltip_feedback_ok" : "Tack för din feedback, så snart som möjligt förstår jag dina kommentarer.",
		"tooltip_feedback_error" : "Jag är ledsen, men det var ett fel och din feedback kunde inte skickas just nu.",
		"tooltip_bits_error" : "<p>Det var ett fel. Försök igen</p>",
		"tooltip_config_select_audio" : "audio",
		"tooltiped_label_config_audio" : "Använd en offentlig dropbox-länk så här: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> <br> Formater Giltigt: <br> .mp3, .wav, .ogg",
		"label_config_iconres" : "Chattsvar",
		"label_leaderboard_viewer" : "viewer",
		"label_leaderboard_times" : "gånger",
		"label_leaderboard_spend" : "Begagnade bitar"
	},
	"pt":{
		"label_config_image" : "Imagem",
		"label_config_title" : "Título",
		"label_config_font" : "Fonte",
		"label_config_glow_light" : "Cor clara",
		"label_config_glow_dark" : "Escuro",
		"label_select_config_position" : "Posição",
		"label_select_config_fadein" : "Animação desaparecendo",
		"label_select_config_fadeout" : "Fadeout de animação",
		"label_select_config_type" : "Tipo de imagem",
		"label_select_config_shape" : "Forma da imagem",
		"label_config_timeout" : "Tempo limite do alerta",
		"label_config_timeout_tooltiped" : "Tempo limite do alerta",
		"label_config_btnsave" : "salvar",
		"label_config_btnreset" : "limpar",
		"label_config_requirements" : "Exigências",
		"label_config_requirements_content" : "- Bits ativos no seu canal<br>",
		"label_config_usage" : "Use",
		"label_config_usage_content" : "- Neste painel, salve a configuração de cada pupface (9).<br>&nbsp; . Imagem.<br>&nbsp; . Título.<br>&nbsp; . Cor.<br>&nbsp; . Posição.<br>&nbsp; . Animação desaparecendo.<br>&nbsp; . Fadeout de animação.<br>&nbsp; . Tipo de imagem.<br>&nbsp; . Forma da imagem.<br>&nbsp; . Duração.<br>- Deixe seus espectadores usarem os pupfaces.<br>&nbsp; . Eles podem ser testados antes do envio por bits.<br>&nbsp;&nbsp; . O alerta será mostrado apenas no jogador que está testando.<br>&nbsp; . Se o processo de bits for concluído com êxito, o alerta será enviado a todos os visualizadores.<br>",
		"label_config_feedback_text" : "Comentários",
		"label_config_a_send" : "Enviar",
		"label_config_support_text" : "* Se esta extensão o ajudar, seu suporte será muito bem recebido ",
		"label_config_font_color" : "Cor da fonte",
		"label_config_btntest" : "Experimente",
		"label_overlay_preview" : "Vista prévia",
		"label_overlay_send" : "Enviar",
		"label_config_volumen" : "volume de áudio",
		"label_config_volumen_tooltiped" : "volume de áudio",
		"label_config_confetti" : "Confete",
		"label_config_stream_pupface_btn" : "Pupfaces de botão no fluxo",
		"label_config_credits": "Créditos",
		"tooltip_bits_config_complete" : "enviou uma pupface para",
		"tooltip_invalid_ext" : "<p>Extensão inválida<br>Por favor tente novamente</p>",
		"tooltip_invalid_format" : "<p>Formato invalido<br>Por favor tente novamente</p>",
		"tooltip_config_save" : "<p>Configuração <b class='green-text'>salva</b>!</p>",
		"tooltip_reset_tiers" : "<p>As 9 camadas serão redefinidas.<br> Tem certeza?<br><br><a class='btnAccept green white-text btn'>Sim</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>Não</a></p>",
		"tooltip_reset_ok" : "<p><b class='red-text'>Redefinir</b> configurações!</p>",
		"tooltip_feedback_empty" : "Não deixe nenhum campo vazio",
		"tooltip_feedback_ok" : "Obrigado pelo seu feedback. Assim que possível, entenderei seus comentários.",
		"tooltip_feedback_error" : "Sinto muito, mas ocorreu um erro e seu feedback não pôde ser enviado no momento.",
		"tooltip_bits_error" : "<p>Houve um erro. Tenta de novo.</p>",
		"tooltip_config_select_audio" : "Áudio",
		"tooltiped_label_config_audio" : "Use um link público da caixa de depósito como este: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> <br> Formatos Válido: <br> .mp3, .wav, .ogg",
		"label_config_iconres" : "Resposta de bate-papo",
		"label_leaderboard_viewer" : "Espectador",
		"label_leaderboard_times" : "Vezes",
		"label_leaderboard_spend" : "Bits usados"
	},
	"pt-br":{
		"label_config_image" : "Imagem",
		"label_config_title" : "Título",
		"label_config_font" : "Fonte",
		"label_config_glow_light" : "Cor clara",
		"label_config_glow_dark" : "Escuro",
		"label_select_config_position" : "Posição",
		"label_select_config_fadein" : "Animação desaparecendo",
		"label_select_config_fadeout" : "Fadeout de animação",
		"label_select_config_type" : "Tipo de imagem",
		"label_select_config_shape" : "Forma da imagem",
		"label_config_timeout" : "Tempo limite do alerta",
		"label_config_timeout_tooltiped" : "Tempo limite do alerta",
		"label_config_btnsave" : "salvar",
		"label_config_btnreset" : "limpar",
		"label_config_requirements" : "Exigências",
		"label_config_requirements_content" : "- Bits ativos no seu canal<br>",
		"label_config_usage" : "Use",
		"label_config_usage_content" : "- Neste painel, salve a configuração de cada pupface (9).<br>&nbsp; . Imagem.<br>&nbsp; . Título.<br>&nbsp; . Cor.<br>&nbsp; . Posição.<br>&nbsp; . Animação desaparecendo.<br>&nbsp; . Fadeout de animação.<br>&nbsp; . Tipo de imagem.<br>&nbsp; . Forma da imagem.<br>&nbsp; . Duração.<br>- Deixe seus espectadores usarem os pupfaces.<br>&nbsp; . Eles podem ser testados antes do envio por bits.<br>&nbsp;&nbsp; . O alerta será mostrado apenas no jogador que está testando.<br>&nbsp; . Se o processo de bits for concluído com êxito, o alerta será enviado a todos os visualizadores.<br>",
		"label_config_feedback_text" : "Comentários",
		"label_config_a_send" : "Enviar",
		"label_config_support_text" : "* Se esta extensão o ajudar, seu suporte será muito bem recebido ",
		"label_config_font_color" : "Cor da fonte",
		"label_config_btntest" : "Experimente",
		"label_overlay_preview" : "Vista prévia",
		"label_overlay_send" : "Enviar",
		"label_config_volumen" : "volume de áudio",
		"label_config_volumen_tooltiped" : "volume de áudio",
		"label_config_confetti" : "Confete",
		"label_config_stream_pupface_btn" : "Pupfaces de botão no fluxo",
		"label_config_credits": "Créditos",
		"tooltip_bits_config_complete" : "enviou uma pupface para",
		"tooltip_invalid_ext" : "<p>Extensão inválida<br>Por favor tente novamente</p>",
		"tooltip_invalid_format" : "<p>Formato invalido<br>Por favor tente novamente</p>",
		"tooltip_config_save" : "<p>Configuração <b class='green-text'>salva</b>!</p>",
		"tooltip_reset_tiers" : "<p>As 9 camadas serão redefinidas.<br> Tem certeza?<br><br><a class='btnAccept green white-text btn'>Sim</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>Não</a></p>",
		"tooltip_reset_ok" : "<p><b class='red-text'>Redefinir</b> configurações!</p>",
		"tooltip_feedback_empty" : "Não deixe nenhum campo vazio",
		"tooltip_feedback_ok" : "Obrigado pelo seu feedback. Assim que possível, entenderei seus comentários.",
		"tooltip_feedback_error" : "Sinto muito, mas ocorreu um erro e seu feedback não pôde ser enviado no momento.",
		"tooltip_bits_error" : "<p>Houve um erro. Tenta de novo.</p>",
		"tooltip_config_select_audio" : "Áudio",
		"tooltiped_label_config_audio" : "Use um link público da caixa de depósito como este: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> <br> Formatos Válido: <br> .mp3, .wav, .ogg",
		"label_config_iconres" : "Resposta de bate-papo",
		"label_leaderboard_viewer" : "Espectador",
		"label_leaderboard_times" : "Vezes",
		"label_leaderboard_spend" : "Bits usados"
	},
	"zh":{
		"label_config_image" : "图片",
		"label_config_title" : "标题",
		"label_config_font" : "使",
		"label_config_glow_light" : "浅色",
		"label_config_glow_dark" : "深色",
		"label_select_config_position" : "位置",
		"label_select_config_fadein" : "动画淡入",
		"label_select_config_fadeout" : "动画淡入",
		"label_select_config_type" : "图片类型",
		"label_select_config_shape" : "图像形状",
		"label_config_timeout" : "警报超时",
		"label_config_timeout_tooltiped" : "警报超时",
		"label_config_btnsave" : "保存",
		"label_config_btnreset" : "清理",
		"label_config_requirements" : "要求",
		"label_config_requirements_content" : "- 频道中的有效位<br>",
		"label_config_usage" : "使用",
		"label_config_usage_content" : "- 在此面板中保存每个角色的配置（9）.<br>&nbsp; . 图片.<br>&nbsp; . 标题.<br>&nbsp; . 颜色.<br>&nbsp; . 位置.<br>&nbsp; . 动画淡入.<br>&nbsp; . 动画淡入.<br>&nbsp; . 图片类型.<br>&nbsp; . 图像形状.<br>&nbsp; . 持续时间.<br>- 让您的观众使用.<br>&nbsp; . 在按位发送之前可以对其进行测试.<br>&nbsp;&nbsp; . 该警报仅显示在正在测试的播放器上.<br>&nbsp; .如果位处理成功完成，则将警报发送给所有查看者.<br>",
		"label_config_feedback_text" : "反馈",
		"label_config_a_send" : "发送",
		"label_config_support_text" : "* 如果此扩展程序对您有所帮助，那么您的支持将非常受欢迎 ",
		"label_config_font_color" : "字体颜色",
		"label_config_btntest" : "尝试",
		"label_overlay_preview" : "预览",
		"label_overlay_send" : "发送",
		"label_config_volumen" : "成交量",
		"label_config_volumen_tooltiped" : "成交量",
		"label_config_confetti" : "五彩纸屑",
		"label_config_stream_pupface_btn" : "流中的按钮",
		"label_config_credits": "学分ト",
		"tooltip_bits_config_complete" : "为",
		"tooltip_invalid_ext" : "<p>扩展名无效<br>请再试一次</p>",
		"tooltip_invalid_format" : "<p>格式无效<br>请再试一次</p>",
		"tooltip_config_save" : "<p>配置已保存!</p>",
		"tooltip_reset_tiers" : "<p>9层将被重置。 <br> 你确定<br><br><a class='btnAccept green white-text btn'>如果</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>不</a></p>",
		"tooltip_reset_ok" : "<p>重设设定!</p>",
		"tooltip_feedback_empty" : "不要留下任何空白",
		"tooltip_feedback_ok" : "感谢您的反馈，我会尽快理解您的评论.",
		"tooltip_feedback_error" : "抱歉，出现错误，目前无法发送您的反馈.",
		"tooltip_bits_error" : "<p>发生错误。 再试一次.</p>",
		"tooltip_config_select_audio" : "音频",
		"tooltiped_label_config_audio" : "使用这样的公共保管箱链接：<br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> <br>格式 有效：<br> .mp3，.wav，.ogg",
		"label_config_iconres" : "即时通讯回应",
		"label_leaderboard_viewer" : "观众",
		"label_leaderboard_times" : "时",
		"label_leaderboard_spend" : "使用的位"
	},
	"zh-cn":{
		"label_config_image" : "图片",
		"label_config_title" : "标题",
		"label_config_font" : "使",
		"label_config_glow_light" : "浅色",
		"label_config_glow_dark" : "深色",
		"label_select_config_position" : "位置",
		"label_select_config_fadein" : "动画淡入",
		"label_select_config_fadeout" : "动画淡入",
		"label_select_config_type" : "图片类型",
		"label_select_config_shape" : "图像形状",
		"label_config_timeout" : "警报超时",
		"label_config_timeout_tooltiped" : "警报超时",
		"label_config_btnsave" : "保存",
		"label_config_btnreset" : "清理",
		"label_config_requirements" : "要求",
		"label_config_requirements_content" : "- 频道中的有效位<br>",
		"label_config_usage" : "使用",
		"label_config_usage_content" : "- 在此面板中保存每个角色的配置（9）.<br>&nbsp; . 图片.<br>&nbsp; . 标题.<br>&nbsp; . 颜色.<br>&nbsp; . 位置.<br>&nbsp; . 动画淡入.<br>&nbsp; . 动画淡入.<br>&nbsp; . 图片类型.<br>&nbsp; . 图像形状.<br>&nbsp; . 持续时间.<br>- 让您的观众使用.<br>&nbsp; . 在按位发送之前可以对其进行测试.<br>&nbsp;&nbsp; . 该警报仅显示在正在测试的播放器上.<br>&nbsp; .如果位处理成功完成，则将警报发送给所有查看者.<br>",
		"label_config_feedback_text" : "反馈",
		"label_config_a_send" : "发送",
		"label_config_support_text" : "* 如果此扩展程序对您有所帮助，那么您的支持将非常受欢迎 ",
		"label_config_font_color" : "字体颜色",
		"label_config_btntest" : "尝试",
		"label_overlay_preview" : "预览",
		"label_overlay_send" : "发送",
		"label_config_volumen" : "成交量",
		"label_config_confetti" : "五彩纸屑",
		"label_config_volumen_tooltiped" : "成交量",
		"label_config_stream_pupface_btn" : "流中的按钮",
		"label_config_credits": "学分ト",
		"tooltip_bits_config_complete" : "为",
		"tooltip_invalid_ext" : "<p>扩展名无效<br>请再试一次</p>",
		"tooltip_invalid_format" : "<p>格式无效<br>请再试一次</p>",
		"tooltip_config_save" : "<p>配置已保存!</p>",
		"tooltip_reset_tiers" : "<p>9层将被重置。 <br> 你确定<br><br><a class='btnAccept green white-text btn'>如果</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>不</a></p>",
		"tooltip_reset_ok" : "<p>重设设定!</p>",
		"tooltip_feedback_empty" : "不要留下任何空白",
		"tooltip_feedback_ok" : "感谢您的反馈，我会尽快理解您的评论.",
		"tooltip_feedback_error" : "抱歉，出现错误，目前无法发送您的反馈.",
		"tooltip_bits_error" : "<p>发生错误。 再试一次.</p>",
		"tooltip_config_select_audio" : "音频",
		"tooltiped_label_config_audio" : "使用这样的公共保管箱链接：<br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> <br>格式 有效：<br> .mp3，.wav，.ogg",
		"label_config_iconres" : "即时通讯回应",
		"label_leaderboard_viewer" : "观众",
		"label_leaderboard_times" : "时",
		"label_leaderboard_spend" : "使用的位"
	},
	"zh-tw":{
		"label_config_image" : "图片",
		"label_config_title" : "标题",
		"label_config_font" : "使",
		"label_config_glow_light" : "浅色",
		"label_config_glow_dark" : "深色",
		"label_select_config_position" : "位置",
		"label_select_config_fadein" : "动画淡入",
		"label_select_config_fadeout" : "动画淡入",
		"label_select_config_type" : "图片类型",
		"label_select_config_shape" : "图像形状",
		"label_config_timeout" : "警报超时",
		"label_config_timeout_tooltiped" : "警报超时",
		"label_config_btnsave" : "保存",
		"label_config_btnreset" : "清理",
		"label_config_requirements" : "要求",
		"label_config_requirements_content" : "- 频道中的有效位<br>",
		"label_config_usage" : "使用",
		"label_config_usage_content" : "- 在此面板中保存每个角色的配置（9）.<br>&nbsp; . 图片.<br>&nbsp; . 标题.<br>&nbsp; . 颜色.<br>&nbsp; . 位置.<br>&nbsp; . 动画淡入.<br>&nbsp; . 动画淡入.<br>&nbsp; . 图片类型.<br>&nbsp; . 图像形状.<br>&nbsp; . 持续时间.<br>- 让您的观众使用.<br>&nbsp; . 在按位发送之前可以对其进行测试.<br>&nbsp;&nbsp; . 该警报仅显示在正在测试的播放器上.<br>&nbsp; .如果位处理成功完成，则将警报发送给所有查看者.<br>",
		"label_config_feedback_text" : "反馈",
		"label_config_a_send" : "发送",
		"label_config_support_text" : "* 如果此扩展程序对您有所帮助，那么您的支持将非常受欢迎 ",
		"label_config_font_color" : "字体颜色",
		"label_config_btntest" : "尝试",
		"label_overlay_preview" : "预览",
		"label_overlay_send" : "发送",
		"label_config_volumen" : "成交量",
		"label_config_confetti" : "五彩纸屑",
		"label_config_volumen_tooltiped" : "成交量",
		"label_config_stream_pupface_btn" : "流中的按钮",
		"label_config_credits": "学分ト",
		"tooltip_bits_config_complete" : "为",
		"tooltip_invalid_ext" : "<p>扩展名无效<br>请再试一次</p>",
		"tooltip_invalid_format" : "<p>格式无效<br>请再试一次</p>",
		"tooltip_config_save" : "<p>配置已保存!</p>",
		"tooltip_reset_tiers" : "<p>9层将被重置。 <br> 你确定<br><br><a class='btnAccept green white-text btn'>如果</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>不</a></p>",
		"tooltip_reset_ok" : "<p>重设设定!</p>",
		"tooltip_feedback_empty" : "不要留下任何空白",
		"tooltip_feedback_ok" : "感谢您的反馈，我会尽快理解您的评论.",
		"tooltip_feedback_error" : "抱歉，出现错误，目前无法发送您的反馈.",
		"tooltip_bits_error" : "<p>发生错误。 再试一次.</p>",
		"tooltip_config_select_audio" : "音频",
		"tooltiped_label_config_audio" : "使用这样的公共保管箱链接：<br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> <br>格式 有效：<br> .mp3，.wav，.ogg",
		"label_config_iconres" : "即时通讯回应",
		"label_leaderboard_viewer" : "观众",
		"label_leaderboard_times" : "时",
		"label_leaderboard_spend" : "使用的位"
	},
	"ja":{
		"label_config_image" : "写真",
		"label_config_title" : "タイトル",
		"label_config_font" : "作ります",
		"label_config_glow_light" : "明るい色",
		"label_config_glow_dark" : "暗い色",
		"label_select_config_position" : "役職",
		"label_select_config_fadein" : "アニメーションフェードイン",
		"label_select_config_fadeout" : "アニメーションのフェードアウト",
		"label_select_config_type" : "画像タイプ",
		"label_select_config_shape" : "画像形式",
		"label_config_timeout" : "アラートタイムアウト",
		"label_config_timeout_tooltiped" : "アラートタイムアウト",
		"label_config_btnsave" : "保存する",
		"label_config_btnreset" : "片付ける",
		"label_config_requirements" : "必要条件",
		"label_config_requirements_content" : "- チャンネルのアクティブビット<br>",
		"label_config_usage" : "使用する",
		"label_config_usage_content" : "- このパネルでは、各pupfaceの構成を保存します（9）<br>&nbsp; . 写真.<br>&nbsp; . タイトル.<br>&nbsp; . 色.<br>&nbsp; . 役職.<br>&nbsp; . アニメーションフェードイン.<br>&nbsp; . アニメーションのフェードアウト...<br>&nbsp; . 画像タイプ.<br>&nbsp; . 画像形式.<br>&nbsp; . 期間.<br>- 視聴者にpupfacesを使用させます.<br>&nbsp; . ビットで送信する前にテストできます.<br>&nbsp;&nbsp; . アラートは、テストしているプレイヤーにのみ表示されます.<br>&nbsp; . ビットプロセスが正常に完了すると、アラートがすべての視聴者に送信されます.<br>",
		"label_config_feedback_text" : "フィードバック",
		"label_config_a_send" : "送る",
		"label_config_support_text" : "* この拡張機能が役立つ場合、あなたのサポートは非常に好評です ",
		"label_config_font_color" : "フォントの色",
		"label_config_btntest" : "試して",
		"label_overlay_preview" : "プレビュー",
		"label_overlay_send" : "送る",
		"label_config_volumen" : "アウディオ巻",
		"label_config_volumen_tooltiped" : "アウディオ巻",
		"label_config_confetti" : "五彩纸屑",
		"label_config_stream_pupface_btn" : "流中的按钮",
		"label_config_credits": "クレジット",
		"tooltip_bits_config_complete" : "pupfaceを送信しました",
		"tooltip_invalid_ext" : "<p>無効な拡張子<br>もう一度やり直してください</p>",
		"tooltip_invalid_format" : "<p>無効な形式<br>もう一度やり直してください</p>",
		"tooltip_config_save" : "<p>設定を保存しました!</p>",
		"tooltip_reset_tiers" : "<p>9つの層がリセットされます。 <br> よろしいですか<br><br><a class='btnAccept green white-text btn'>うん</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>いや</a></p>",
		"tooltip_reset_ok" : "<p>設定をリセット!</p>",
		"tooltip_feedback_empty" : "空のフィールドを残さないでください",
		"tooltip_feedback_ok" : "ご意見ありがとうございます、できるだけ早くあなたのコメントを理解します.",
		"tooltip_feedback_error" : "申し訳ありませんが、エラーが発生したため、現時点ではフィードバックを送信できませんでした。",
		"tooltip_bits_error" : "<p>エラーが発生しました。 再試行</p>",
		"tooltip_config_select_audio" : "音声",
		"tooltiped_label_config_audio" : "次のような公開Dropboxリンクを使用します。<br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> <br>形式 有効：<br> .mp3、.wav、.ogg",
		"label_config_iconres" : "チャット応答",
		"label_leaderboard_viewer" : "ストリームpupfacesボタン",
		"label_leaderboard_times" : "回",
		"label_leaderboard_spend" : "使用済みビット"
	},
	"ko":{
		"label_config_image" : "사진",
		"label_config_title" : "제목",
		"label_config_font" : "타이포그래피",
		"label_config_glow_light" : "연한 색",
		"label_config_glow_dark" : "어두운 색",
		"label_select_config_position" : "위치",
		"label_select_config_fadein" : "애니메이션 페데 인",
		"label_select_config_fadeout" : "애니메이션 페이드 아웃",
		"label_select_config_type" : "이미지 타입",
		"label_select_config_shape" : "이미지 형태",
		"label_config_timeout" : "경고 시간 초과",
		"label_config_timeout_tooltiped" : "경고 시간 초과",
		"label_config_btnsave" : "구하다",
		"label_config_btnreset" : "정리하다",
		"label_config_requirements" : "요구 사항",
		"label_config_requirements_content" : "- 채널의 활성 비트<br>",
		"label_config_usage" : "사용",
		"label_config_usage_content" : "- 이 패널에서 각 꼭짓점에 대한 구성을 저장하십시오 (9)..<br>&nbsp; . 사진.<br>&nbsp; . 제목.<br>&nbsp; . 색깔.<br>&nbsp; . 위치.<br>&nbsp; . 애니메이션 페데 인.<br>&nbsp; . 애니메이션 페이드 아웃.<br>&nbsp; . 타입.<br>&nbsp; . 모양.<br>&nbsp; . 기간.<br>- 시청자가 꼭두각시를 사용하게하십시오.<br>&nbsp; . 비트 단위로 보내기 전에 테스트 할 수 있습니다.<br>&nbsp;&nbsp; . 경고는 테스트하는 사람의 비디오 플레이어에만 표시됩니다.<br>&nbsp; . 비트 프로세스가 성공적으로 완료되면 모든 뷰어에게 경고가 전송됩니다..<br>",
		"label_config_feedback_text" : "피드백",
		"label_config_a_send" : "보내기",
		"label_config_support_text" : "* 이 확장 프로그램이 도움이 되시면 귀하의 지원이 매우 잘 전달됩니다 ",
		"label_config_font_color" : "글자 색",
		"label_config_btntest" : "시도",
		"label_overlay_preview" : "미리보기",
		"label_overlay_send" : "보내기",
		"label_config_volumen" : "음량",
		"label_config_volumen_tooltiped" : "음량",
		"label_config_confetti" : "색종이 조각",
		"label_config_stream_pupface_btn" : "꼭두각시 스트림 버튼",
		"label_config_credits": "크레딧",
		"tooltip_bits_config_complete" : "꼭두각시를 보내다",
		"tooltip_invalid_ext" : "<p>잘못된 확장<br>다시 시도하십시오</p>",
		"tooltip_invalid_format" : "<p>잘못된 형식<br>다시 시도하십시오</p>",
		"tooltip_config_save" : "<p>구성이 <b class='green-text'>저장되었습니다</b>!</p>",
		"tooltip_reset_tiers" : "<p>9 개의 계층이 재설정됩니다. <br> 확실합니까<br><br><a class='btnAccept green white-text btn'>응</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>아니요</a></p>",
		"tooltip_reset_ok" : "<p>설정 <b class='red-text'>초기화</b>!</p>",
		"tooltip_feedback_empty" : "빈 칸을 두지 마십시오",
		"tooltip_feedback_ok" : "귀하의 의견에 감사드립니다. 가능한 빨리 귀하의 의견을 이해하겠습니다.",
		"tooltip_feedback_error" : "죄송합니다. 오류가 발생하여 의견을 보내실 수 없습니다.",
		"tooltip_bits_error" : "<p>오류가 발생했습니다. 다시 시도하십시오</p>",
		"tooltip_config_select_audio" : "오디오",
		"tooltiped_label_config_audio" : "다음과 같은 공개 드롭 박스 링크를 사용하십시오. <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> <br> 형식 유효한 : <br> .mp3, .wav, .ogg",
		"label_config_iconres" : "채팅 응답",
		"label_leaderboard_viewer" : "관중",
		"label_leaderboard_times" : "타임즈",
		"label_leaderboard_spend" : "사용 된 비트"
	},
	"da":{
		"label_config_image" : "billede",
		"label_config_title" : "titel",
		"label_config_font" : "Fuente",
		"label_config_glow_light" : "Lys farve",
		"label_config_glow_dark" : "Mørk farve",
		"label_select_config_position" : "position",
		"label_select_config_fadein" : "Animation fadein",
		"label_select_config_fadeout" : "Animation fadeout",
		"label_select_config_type" : "Billedtype",
		"label_select_config_shape" : "Billedform",
		"label_config_timeout" : "Timeout for alarm",
		"label_config_timeout_tooltiped" : "Timeout for alarm",
		"label_config_btnsave" : "spare",
		"label_config_btnreset" : "rydde op",
		"label_config_requirements" : "krav",
		"label_config_requirements_content" : "- Aktive bits i din kanal <br>",
		"label_config_usage" : "brug",
		"label_config_usage_content" : "- Dette panel gemmer konfigurationen for hver pupface (9). <br> &nbsp;. Billede. <br> &nbsp;. Titel. <br> &nbsp;. Farve. <br> &nbsp;. Position. <br> &nbsp;. Animation fadein. <br> &nbsp;. Fadeout af animation. <br> &nbsp;. Type. <br> &nbsp;. Form. <br> &nbsp;. Varighed. <br> - Lad dine seere bruge eleverne. <br> &nbsp;. De kan testes, før de sendes med bits. <br> &nbsp;&nbsp;. Alarmen vises kun på den spiller, der tester. <br> &nbsp;. Hvis bitprocessen er fuldført, sendes alarmen til alle seere. <br>",
		"label_config_feedback_text" : "Feedback",
		"label_config_a_send" : "sende",
		"label_config_support_text" : "* Hvis denne udvidelse hjælper dig, modtages din support meget godt ",
		"label_config_font_color" : "Fontfarve",
		"label_config_btntest" : "prøve",
		"label_overlay_preview" : "forhåndsvisning",
		"label_overlay_send" : "sende",
		"label_config_credits" : "kreditter",
		"label_config_volumen" : "Lydstyrke",
		"label_config_volumen_tooltiped" : "Lydstyrke",
		"label_config_confetti" : "konfetti",
		"label_config_stream_pupface_btn" : "Strøm pupfaces-knap",
		"tooltip_bits_config_complete" : "Jeg sender en hvalpeflade til",
		"tooltip_invalid_ext" : "<p> Ugyldig udvidelse <br> Prøv igen </p>",
		"tooltip_invalid_format" : "<p>Ugyldigt format - Prøv igen</p>",
		"tooltip_config_save" : "<p>Indstillinger <b class='green-text'> Gemt</b>!</p>",
		"tooltip_reset_tiers" : "<p> De 9 niveauer vil blive nulstillet. <br> Er du sikker? <br> <br> <a class='btnAccepter green white-text btn'> Ja </a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'> Nej </a> </p>",
		"tooltip_reset_ok": "<p> Konfiguration <b class='red-text'> reset </b>! </p>",
		"tooltip_feedback_empty" : "Efterlad ikke noget tomt felt",
		"tooltip_feedback_ok" : "Tak for din feedback, så snart som muligt forstår jeg dine kommentarer.",
		"tooltip_feedback_error" : "Jeg beklager, men der opstod en fejl, og din feedback kunne ikke sendes på dette tidspunkt.",
		"tooltip_bits_error" : "<p>Der opstod en fejl. Prøv igen</p>",
		"tooltip_config_select_audio" : "lyd",
		"tooltiped_label_config_audio" : "Brug et offentligt dropbox-link som dette: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> <br> Formater Gyldig: <br> .mp3, .wav, .ogg",
		"label_config_iconres" : "Chatrespons",
		"label_leaderboard_viewer" : "seeren",
		"label_leaderboard_times" : "gange",
		"label_leaderboard_spend" : "Brugte bits"
	},
	"it":{
		"label_config_image" : "immagine",
		"label_config_title" : "titolo",
		"label_config_font" : "composizione",
		"label_config_glow_light" : "Colore chiaro",
		"label_config_glow_dark" : "Colore scuro",
		"label_select_config_position" : "posizione",
		"label_select_config_fadein" : "Animazione dissolvenza",
		"label_select_config_fadeout" : "Dissolvenza dell'animazione",
		"label_select_config_type" : "Tipo di immagine",
		"label_select_config_shape" : "Modulo immagine",
		"label_config_timeout" : "Timeout avviso",
		"label_config_timeout_tooltiped" : "Timeout avviso",
		"label_config_btnsave" : "salvare",
		"label_config_btnreset" : "ripulire",
		"label_config_requirements" : "requisiti",
		"label_config_requirements_content" : "- Bit attivi nel tuo canale <br>",
		"label_config_usage" : "uso",
		"label_config_usage_content" : "- Questo pannello salva la configurazione per ogni pupface (9). <br> &nbsp;. Immagine. <br> &nbsp;. Titolo. <br> &nbsp;. Colore. <br> &nbsp;. Posizione. <br> &nbsp;. Animazione dissolvenza. <br> &nbsp;. Dissolvenza dell'animazione. <br> &nbsp;. Tipo. <br> &nbsp;. Modulo. <br> &nbsp;. Durata. <br> - Consenti ai tuoi spettatori di usare gli alunni. <br> &nbsp;. Possono essere testati prima dell'invio tramite bit. <br> &nbsp;&nbsp;. L'avviso verrà visualizzato solo sul giocatore che sta testando. <br> &nbsp;. Se il processo di bit viene completato correttamente, l'avviso viene inviato a tutti i visualizzatori. <br>",
		"label_config_feedback_text" : "feedback",
		"label_config_a_send" : "inviare",
		"label_config_support_text" : "* Se questa estensione ti aiuta, il tuo supporto è molto ben accolto ",
		"label_config_font_color" : "Colore del carattere",
		"label_config_btntest" : "provare",
		"label_overlay_preview" : "anteprima",
		"label_overlay_send" : "inviare",
		"label_config_credits" : "crediti",
		"label_config_volumen" : "Volume audio",
		"label_config_volumen_tooltiped" : "Volume audio",
		"label_config_confetti" : "coriandoli",
		"label_config_stream_pupface_btn" : "Pulsante stream pupfaces",
		"tooltip_bits_config_complete" : "Mando un pupface per",
		"tooltip_invalid_ext" : "<p>Estensione non valida <br> Riprova</p>",
		"tooltip_invalid_format" : "<p>Formato non valido <br> Riprova</p>",
		"tooltip_config_save" : "<p> Configurazione <b class='green-text'> Salvato </b>! </p> ",
		"tooltip_reset_tiers": "<p> I 9 livelli verranno ripristinati. <br> Sei sicuro? <br> <br> <a class='btnAccept green white-text btn'> Sì </a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'> No </a> </p>",
		"tooltip_reset_ok" : "<p> Configurazione <b class='red-text'> reset </b>! </p>",
		"tooltip_feedback_empty" : "Non lasciare alcun campo vuoto",
		"tooltip_feedback_ok" : "Grazie per il tuo feedback, appena possibile capirò i tuoi commenti.",
		"tooltip_feedback_error" : "Mi dispiace, ma si è verificato un errore e al momento non è stato possibile inviare il tuo feedback.",
		"tooltip_bits_error" : "<p>Si è verificato un errore Riprovare</p>",
		"tooltip_config_select_audio" : "audio",
		"tooltiped_label_config_audio" : "Utilizza un link di dropbox pubblico come questo: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> <br> Formati Valido: <br> .mp3, .wav, .ogg",
		"label_config_iconres" : "Risposta chat",
		"label_leaderboard_viewer" : "spettatore",
		"label_leaderboard_times" : "volte",
		"label_leaderboard_spend" : "Bit usati"
	},
	"hu":{
		"label_config_image": "Kép",
		"label_config_title": "cím",
		"label_config_font": "Forrás",
		"label_config_glow_light": "világos színű",
		"label_config_glow_dark": "Sötét színű",
		"label_select_config_position": "Pozíció",
		"label_select_config_fadein": "Animáció fadein",
		"label_select_config_fadeout": "Animáció elhalványulása",
		"label_select_config_type": "Kép típusa",
		"label_select_config_shape": "Kép forma",
		"label_config_timeout": "Alert timeout",
		"label_config_timeout_tooltiped": "Alert timeout",
		"label_config_btnsave": "mentés",
		"label_config_btnreset": "tiszta",
		"label_config_requirements": "Követelmények",
		"label_config_requirements_content": "- Aktív bitek a csatornádon <br>",
		"label_config_usage": "Használat",
		"label_config_usage_content": "- Ebben a panelen mentse el az egyes felületek konfigurációját (9). <br> &nbsp;. Kép. <br> &nbsp;. Cím. <br> ** * 9 ***. Színes. <br> &nbsp;. Pozíció. <br> &nbsp;. Fadein animáció. <br> &nbsp;. Animáció fadeout. . <br> &nbsp;. Írja be. <br> &nbsp;. Alak. <br> &nbsp;. Időtartam. <br> - Hagyja, hogy a nézők használják a kötőelemek. <br> &nbsp;. Bitekkel történő küldés előtt tesztelhető. <br> &nbsp;&nbsp;. A riasztás csak azon játékosra jelenik meg, akinek elvégzi a tesztet. <br> &nbsp;. Ha a bitfolyamat sikeresen befejeződik, a riasztást minden nézőnek elküldjük. <br> ",
		"label_config_feedback_text": "Visszajelzés",
		"label_config_a_send": "Küldés",
		"label_config_support_text": "* Ha ez a kiterjesztés hasznos, a támogatást nagyon jól fogadják",
		"label_config_font_color": "Betűszín",
		"label_config_btntest": "Test",
		"label_overlay_preview": "Előnézet",
		"label_overlay_send": "Küldés",
		"label_config_credits": "Kreditek",
		"label_config_volumen": "Audio hangerő",
		"label_config_volumen_tooltiped": "Audio hangerő",
		"label_config_confetti" : "konfetti",
		"label_config_stream_pupface_btn": "gomb gombok felületére patakban",
		"tooltip_bits_config_complete": "Küldök egy kutyafelületet",
		"tooltip_invalid_ext": "<p> Érvénytelen kiterjesztés <br> Kérjük, próbálja meg újra </p>",
		"tooltip_invalid_format": "<p> Érvénytelen formátum <br> Kérjük, próbálja meg újra </p>",
		"tooltip_config_save": "<p> Konfiguráció <b class='green-text'> Mentett </b>! </p>",
		"tooltip_reset_tiers": "<p> A 9 szintet alaphelyzetbe állítják. <br> Biztos benne? <br> <br> <a class='btnAccept green white-text btn'> igen </a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'> Nem </a> </p> ",
		"tooltip_reset_ok": "<p> Konfiguráció <b class='red-text'> reset </b>! </p>",
		"tooltip_feedback_empty": "Ne hagyjon üres mezőket",
		"tooltip_feedback_ok": "Köszönjük visszajelzését, a lehető leghamarabb megjegyzéseket fűzök hozzászólásodhoz.",
		"tooltip_feedback_error": "Elnézést kérünk, de hiba történt, és visszajelzését nem sikerült elküldeni.",
		"tooltip_bits_error": "<p> Hiba történt. Próbálkozzon újra. </p>",
		"tooltip_config_select_audio": "Audio",
		"tooltiped_label_config_audio": "Használjon ilyen nyilvános dropbox linket: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br > <br> Érvényes formátumok: <br> .mp3, .wav, .ogg ",
		"label_config_iconres": "Chat válasz",
		"label_leaderboard_viewer": "Néző",
		"label_leaderboard_times": "alkalommal",
		"label_leaderboard_spend": "Használt bitek"
	},
	"nl":{
		"label_config_image": "Afbeelding",
		"label_config_title": "titel",
		"label_config_font": "Bron",
		"label_config_glow_light": "Lichte kleur",
		"label_config_glow_dark": "Donkere kleur",
		"label_select_config_position": "Positie",
		"label_select_config_fadein": "Animatie fadein",
		"label_select_config_fadeout": "Animatie Fadeout",
		"label_select_config_type": "Afbeeldingstype",
		"label_select_config_shape": "Afbeeldingsformulier",
		"label_config_timeout": "Alert timeout",
		"label_config_timeout_tooltiped": "Alert timeout",
		"label_config_btnsave": "opslaan",
		"label_config_btnreset": "schoon",
		"label_config_requirements": "Vereisten",
		"label_config_requirements_content": "- Actieve bits in uw kanaal <br>",
		"label_config_usage": "Gebruik",
		"label_config_usage_content": "- Sla in dit paneel de configuratie op voor elke pupface (9). <br> &nbsp;. Afbeelding. <br> &nbsp;. Titel. <br> ** * 9 ***. Kleur. <br> &nbsp;. Positie. <br> &nbsp;. Animatie fadein. <br> &nbsp;. Animatie fadeout. . <br> &nbsp;. Type. <br> &nbsp;. Vorm. <br> &nbsp;. Duur. <br> - Laat uw kijkers de pupfaces. <br> &nbsp;. Kan worden getest voor verzending door bits. <br> &nbsp;&nbsp;. De waarschuwing wordt alleen weergegeven aan de speler van wie doet de test. <br> &nbsp;. Als het bitproces met succes is voltooid, wordt de waarschuwing naar alle kijkers verzonden. <br> ",
		"label_config_feedback_text": "Feedback",
		"label_config_a_send": "Verzenden",
		"label_config_support_text": "* Als deze extensie nuttig is, wordt uw ondersteuning zeer goed ontvangen",
		"label_config_font_color": "Lettertypekleur",
		"label_config_btntest": "Test",
		"label_overlay_preview": "Preview",
		"label_overlay_send": "Verzenden",
		"label_config_credits": "Credits",
		"label_config_volumen": "Audio volume",
		"label_config_volumen_tooltiped": "Audio volume",
		"label_config_confetti" : "Confetti",
		"label_config_stream_pupface_btn": "knop pupfaces in stream",
		"tooltip_bits_config_complete": "Ik stuur een pupface door",
		"tooltip_invalid_ext": "<p> Ongeldige extensie <br> Probeer het opnieuw </p>",
		"tooltip_invalid_format": "<p> Ongeldig formaat <br> probeer opnieuw </p>",
		"tooltip_config_save": "<p> Configuratie <b class='green-text'> Opgeslagen </b>! </p>",
		"tooltip_reset_tiers": "<p> De 9 niveaus worden gereset. <br> Weet u het zeker? <br> <br> <a class='btnAccept green white-text btn'> Ja </a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'> Nee </a> </p> ",
		"tooltip_reset_ok": "<p> Configuratie <b class='red-text'> reset </b>! </p>",
		"tooltip_feedback_empty": "Laat geen lege velden achter",
		"tooltip_feedback_ok": "Bedankt voor uw feedback, ik zal zo snel mogelijk reageren op uw opmerkingen.",
		"tooltip_feedback_error": "Sorry, maar er is een fout opgetreden en uw feedback kon op dit moment niet worden verzonden.",
		"tooltip_bits_error": "<p> Er is een fout opgetreden. Probeer het opnieuw. </p>",
		"tooltip_config_select_audio": "Audio",
		"tooltiped_label_config_audio": "Gebruik een openbare dropbox-link zoals deze: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br > <br> Geldige formaten: <br> .mp3, .wav, .ogg ",
		"label_config_iconres": "Chatreactie",
		"label_leaderboard_viewer": "Viewer",
		"label_leaderboard_times": "Keer",
		"label_leaderboard_spend": "Gebruikte bits"
	},
	"no":{
		"label_config_image": "Bilde",
		"label_config_title": "tittel",
		"label_config_font": "Kilde",
		"label_config_glow_light": "Lys farge",
		"label_config_glow_dark": "Mørk farge",
		"label_select_config_position": "Posisjon",
		"label_select_config_fadein": "Animasjon fadein",
		"label_select_config_fadeout": "Animasjon fadeout",
		"label_select_config_type": "Bildetype",
		"label_select_config_shape": "Bildeskjema",
		"label_config_timeout": "Alert timeout",
		"label_config_timeout_tooltiped": "Alert timeout",
		"label_config_btnsave": "lagre",
		"label_config_btnreset": "ren",
		"label_config_requirements": "Krav",
		"label_config_requirements_content": "- Aktive biter i kanalen din <br>",
		"label_config_usage": "Bruk",
		"label_config_usage_content": "- I dette panelet lagrer du konfigurasjonen for hver pupface (9). <br> &nbsp;. Image. <br> &nbsp;. Tittel. <br> ** * 9 ***. Farge. <br> &nbsp;. Posisjon. <br> &nbsp;. Animasjon fadein. <br> &nbsp;. Animasjon fadeout. . <br> &nbsp;. Type. <br> &nbsp;. Form. <br> &nbsp;. Varighet. <br> - La seerne dine bruke pupfaces. <br> &nbsp;. Kan testes før du sender med biter. <br> &nbsp;&nbsp;. Alarmen vises bare på spilleren som gjør testen. <br> &nbsp;. Hvis bitprosessen er fullført, blir varselet sendt til alle seere. <br> ",
		"label_config_feedback_text": "Tilbakemelding",
		"label_config_a_send": "Send",
		"label_config_support_text": "* Hvis denne utvidelsen er nyttig, blir støtten din veldig godt mottatt",
		"label_config_font_color": "Fontfarge",
		"label_config_btntest": "Test",
		"label_overlay_preview": "Forhåndsvisning",
		"label_overlay_send": "Send",
		"label_config_credits": "Credits",
		"label_config_volumen": "Lydvolum",
		"label_config_volumen_tooltiped": "Lydvolum",
		"label_config_confetti" : "Confetti",
		"label_config_stream_pupface_btn": "knapp pupfaces i stream",
		"tooltip_bits_config_complete": "Jeg sender en pupface av",
		"tooltip_invalid_ext": "<p> Ugyldig utvidelse. Vennligst prøv igjen </p>",
		"tooltip_invalid_format": "<p> Ugyldig format. Vennligst prøv igjen </p>",
		"tooltip_config_save": "<p> Konfigurasjon <b class='green-text'> Lagret </b>! </p>",
		"tooltip_reset_tiers": "<p> De 9 lagene vil bli tilbakestilt. <br> Er du sikker? <br> <br> <a class='btnAccept green white-text btn'> den </a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'> Nei </a> </p> ",
		"tooltip_reset_ok": "<p> Konfigurasjon <b class='red-text'> reset </b>! </p>",
		"tooltip_feedback_empty": "Ikke legg igjen noen tomme felt",
		"tooltip_feedback_ok": "Takk for tilbakemeldingen, så snart som mulig vil jeg kommentere kommentarene dine.",
		"tooltip_feedback_error": "Beklager, men det var en feil, og tilbakemeldingene dine kunne ikke sendes på dette tidspunktet.",
		"tooltip_bits_error": "<p> Det oppstod en feil. Prøv igjen. </p>",
		"tooltip_config_select_audio": "Audio",
		"tooltiped_label_config_audio": "Bruk en offentlig dropbox-kobling som denne: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br > <br> Gyldige formater: <br> .mp3, .wav, .ogg ",
		"label_config_iconres": "Chatrespons",
		"label_leaderboard_viewer": "Viewer",
		"label_leaderboard_times": "ganger",
		"label_leaderboard_spend": "Brukte biter"
	},
	"ro":{
		"label_config_image": "obraz",
		"label_config_title": "titlu",
		"label_config_font": "Sursa",
		"label_config_glow_light": "Culoare lumină",
		"label_config_glow_dark": "Culoare închisă",
		"label_select_config_position": "Poziție",
		"label_select_config_fadein": "Animare fadein",
		"label_select_config_fadeout": "Animație decăzută",
		"label_select_config_type": "Tip obraz",
		"label_select_config_shape": "Formă obraz",
		"label_config_timeout": "TimeTimpout de alertă",
		"label_config_timeout_tooltiped": "Timp de alertă",
		"label_config_btnsave": "salvați",
		"label_config_btnreset": "curat",
		"label_config_requirements": "Cerințe",
		"label_config_requirements_content": "- Biți activi în canalul tău",
		"label_config_usage": "Utilizați",
		"label_config_usage_content": "- În acest panou salvați configurația pentru fiecare pupface (9). <br> &nbsp;. Image. <br> &nbsp;. Titlu. <br> ** * 9 ***. Culoare. <br> &nbsp;. Poziția. <br> &nbsp;. Animarea fadein. <br> &nbsp;. Dispunerea animației. . <br> &nbsp;. Tip. <br> &nbsp;. Forma. <br> &nbsp;. Durata. <br> - Lăsați spectatorii să utilizeze pupfaces. <br> &nbsp;. Poate fi testat înainte de a fi trimis prin biți. <br> &nbsp;&nbsp;. Alerta va fi afișată numai pe playerul căruia face testul. <br> &nbsp;. Dacă procesul de biți este finalizat cu succes, alerta este trimisă tuturor spectatorilor. <br> ",
		"label_config_feedback_text": "Feedback",
		"label_config_a_send": "Trimite",
		"label_config_support_text": "* Dacă această extensie este utilă, suportul dvs. este foarte bine primit",
		"label_config_font_color": "Culoare font",
		"label_config_btntest": "Test",
		"label_overlay_preview": "Previzualizare",
		"label_overlay_send": "Trimite",
		"label_config_credits": "Credite",
		"label_config_volumen": "Volum audio",
		"label_config_volumen_tooltiped": "Volum audio",
		"label_config_confetti" : "Confeti",
		"label_config_stream_pupface_btn": "butoniere cu buton în flux",
		"tooltip_bits_config_complete": "Trimit un pupface prin",
		"tooltip_invalid_ext": "<p> Extensie nevalidă <br> Vă rugăm să încercați din nou </p>",
		"tooltip_invalid_format": "<p> Format nevalid <br> Vă rugăm să încercați din nou </p>",
		"tooltip_config_save": "<p> Configurare <b class='green-text'> Salvat </b>! </p>",
		"tooltip_reset_tiers": "<p> Cele 9 niveluri vor fi resetate. <br> Sunteți sigur? <br> <br> <a class='btnAccept green white-text btn'> Da </a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'> Nu </a> </p> ",
		"tooltip_reset_ok": "<p> Configurare <b class='red-text'> resetare </b>! </p>",
		"tooltip_feedback_empty": "Nu lăsați câmpuri goale",
		"tooltip_feedback_ok": "Vă mulțumim pentru feedback, cât de curând posibil voi face comentarii.",
		"tooltip_feedback_error": "Ne pare rău, dar a existat o eroare și feedback-ul dvs. nu a putut fi trimis în acest moment.",
		"tooltip_bits_error": "<p> A apărut o eroare. Încercați din nou. </p>",
		"tooltip_config_select_audio": "Audio",
		"tooltiped_label_config_audio": "Folosiți un link public pentru dropbox ca acesta: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br > <br> Formate valide: <br> .mp3, .wav, .ogg ",
		"label_config_iconres": "Răspuns la chat",
		"label_leaderboard_viewer": "divák",
		"label_leaderboard_times": "doba",
		"label_leaderboard_spend": "Biți folosiți"
	},
	"sk":{
		"label_config_image": "obraz",
		"label_config_title": "nadpis",
		"label_config_font": "Source",
		"label_config_glow_light": "Svetlá farba",
		"label_config_glow_dark": "Dark color",
		"label_select_config_position": "pozície",
		"label_select_config_fadein": "Animácia vybledne",
		"label_select_config_fadeout": "Animácia Fadeout",
		"label_select_config_type": "Typ obrázka",
		"label_select_config_shape": "Obrazová forma",
		"label_config_timeout": "Časový limit upozornenia",
		"label_config_timeout_tooltiped": "Časový limit upozornenia",
		"label_config_btnsave": "save",
		"label_config_btnreset": "clean",
		"label_config_requirements": "Požiadavky",
		"label_config_requirements_content": "- Aktívne bity vo vašom kanáli <br>",
		"label_config_usage": "Use",
		"label_config_usage_content": "- Na tomto paneli uložte konfiguráciu pre každé pupface (9). <br> &nbsp;. Obrázok. <br> &nbsp;. Názov. <br> ** * 9 ***. Farba. <br> &nbsp;. Pozícia. <br> &nbsp;. Animácia slabne. <br> &nbsp;. Animácia vybledne. . <br> &nbsp;. Typ. <br> &nbsp;. Tvar. <br> &nbsp;. Trvanie. <br> - Nechajte svojich divákov používať šteniatka. <br> &nbsp;. Môže sa otestovať pred odoslaním bitmi. <br> &nbsp;&nbsp;. Výstraha sa zobrazí iba na hráčovi, ktorého vykoná test. <br> &nbsp;. Ak je bitový proces úspešne dokončený, upozornenie sa odošle všetkým divákom. <br> ",
		"label_config_feedback_text": "Feedback",
		"label_config_a_send": "Poslať",
		"label_config_support_text": "* Ak je toto rozšírenie užitočné, vaša podpora je veľmi dobre prijatá",
		"label_config_font_color": "Farba písma",
		"label_config_btntest": "Test",
		"label_overlay_preview": "Preview",
		"label_overlay_send": "Odoslať",
		"label_config_credits": "Credits",
		"label_config_volumen": "Hlasitosť zvuku",
		"label_config_volumen_tooltiped": "Hlasitosť zvuku",
		"label_config_confetti" : "konfety",
		"label_config_stream_pupface_btn": "tlačidlo pupfaces in stream",
		"tooltip_bits_config_complete": "Posielam pupface od",
		"tooltip_invalid_ext": "<p> Neplatné rozšírenie <br> skúste to znova </p>",
		"tooltip_invalid_format": "<p> Neplatný formát - skúste to znova </p>",
		"tooltip_config_save": "<p> Konfigurácia <b class='green-text'> Saved </b>! </p>",
		"tooltip_reset_tiers": "<p> 9 úrovní sa vynuluje. <br> Ste si istí? <br> <br> <a class='btnAccept green white-text btn'> Áno </a> &nbsp;&nbsp; <a class='btnDecline red white whitetext btn'> Nie </a> </p> ",
		"tooltip_reset_ok": "<p> Konfigurácia <b class='red-text'> reset </b>! </p>",
		"tooltip_feedback_empty": "Nenechávajte žiadne prázdne polia",
		"tooltip_feedback_ok": "Ďakujeme za vaše hodnotenie, hneď ako to bude možné, budem sa vyjadrovať k vašim komentárom.",
		"tooltip_feedback_error": "Ľutujeme, ale vyskytla sa chyba a váš názor sa momentálne nedal odoslať.",
		"tooltip_bits_error": "<p> Vyskytla sa chyba. Skúste to znova. </p>",
		"tooltip_config_select_audio": "Audio",
		"tooltiped_label_config_audio": "Použite takýto odkaz na verejnú schránku: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br > <br> Platné formáty: <br> .mp3, .wav, .ogg ",
		"label_config_iconres": "Odpoveď na rozhovor",
		"label_leaderboard_viewer": "divák",
		"label_leaderboard_times": "doba",
		"label_leaderboard_spend": "Použité bity"
	},
	"fi":{
		"label_config_image": "kuva",
		"label_config_title": "otsikko",
		"label_config_font": "Lähde",
		"label_config_glow_light": "vaalea väri",
		"label_config_glow_dark": "tumma väri",
		"label_select_config_position": "Sijainti",
		"label_select_config_fadein": "Animaatio fadein",
		"label_select_config_fadeout": "Animaation häipyminen",
		"label_select_config_type": "Kuvatyyppi",
		"label_select_config_shape": "Kuvan muoto",
		"label_config_timeout": "Hälytyksen aikakatkaisu",
		"label_config_timeout_tooltiped": "Hälytyksen aikakatkaisu",
		"label_config_btnsave": "tallenna",
		"label_config_btnreset": "puhdas",
		"label_config_requirements": "Vaatimukset",
		"label_config_requirements_content": "- Kanavasi aktiiviset bitit <br>",
		"label_config_usage": "Käytä",
		"label_config_usage_content": "- Tallenna tässä paneelissa kunkin pinnan kokoonpano (9). <br> &nbsp;. Kuva. <br> &nbsp;. Otsikko. <br> ** * 9 ***. Väri. <br> &nbsp;. Sijainti. <br> &nbsp;. Animaatio fadein. <br> &nbsp;. Animaatio fadeout. . <br> &nbsp;. Tyyppi. <br> &nbsp;. Muoto. <br> &nbsp;. Kesto. <br> - Anna katsojien käyttää nukkepinnat. <br> &nbsp;. Voidaan testata ennen lähettämistä biteillä. <br> &nbsp;&nbsp;. Hälytys näkyy vain siinä soittimessa, josta suorittaa testin. <br> &nbsp;. Jos bittiprosessi on suoritettu onnistuneesti, hälytys lähetetään kaikille katsojille. <br> ",
		"label_config_feedback_text": "Palaute",
		"label_config_a_send": "Lähetä",
		"label_config_support_text": "* Jos tämä laajennus on hyödyllinen, tuki on saanut erittäin hyvän vastaanoton",
		"label_config_font_color": "Fontin väri",
		"label_config_btntest": "Test",
		"label_overlay_preview": "Esikatselu",
		"label_overlay_send": "Lähetä",
		"label_config_credits": "Laajuudet",
		"label_config_volumen": "Äänenvoimakkuus",
		"label_config_volumen_tooltiped": "Äänenvoimakkuus",
		"label_config_confetti" : "konfetit",
		"label_config_stream_pupface_btn": "painikkeiden pintarakenteet suorassa",
		"tooltip_bits_config_complete": "Lähetän pentti",
		"tooltip_invalid_ext": "<p> Virheellinen laajennus <br> Yritä uudelleen </p>",
		"tooltip_invalid_format": "<p> Virheellinen muoto <br> Yritä uudelleen </p>",
		"tooltip_config_save": "<p> Kokoonpano <b class='green-text'> Tallennettu </b>! </p>",
		"tooltip_reset_tiers": "<p> 9 tasoa nollataan. <br> Oletko varma? <br> <br> <a class='btnAccept green white-text btn'> Kyllä </a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'> Ei </a> </p> ",
		"tooltip_reset_ok": "<p> Kokoonpano <b class='red-text'> nollataan </b>! </p>",
		"tooltip_feedback_empty": "Älä jätä tyhjiä kenttiä",
		"tooltip_feedback_ok": "Kiitos palautteestasi, kommentoin kommentteja niin pian kuin mahdollista.",
		"tooltip_feedback_error": "Anteeksi, mutta tapahtui virhe ja palautetta ei voitu lähettää tällä hetkellä.",
		"tooltip_bits_error": "<p> Oli virhe. Yritä uudelleen. </p>",
		"tooltip_config_select_audio": "Audio",
		"tooltiped_label_config_audio": "Käytä julkista pudotuslaatikkolinkkiä näin: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br > <br> Voimassa olevat muodot: <br> .mp3, .wav, .ogg ",
		"label_config_iconres": "Chat-vastaus",
		"label_leaderboard_viewer": "katsoja",
		"label_leaderboard_times": "kertaa",
		"label_leaderboard_spend": "Käytetyt bitit"
	},
	"tr":{
		"label_config_image": "resim",
		"label_config_title": "başlık",
		"label_config_font": "Fuente",
		"label_config_glow_light": "Renk kodu",
		"label_config_glow_dark": "Renk uyarısı",
		"label_select_config_position": "Konum",
		"label_select_config_fadein": "Animasyonun faaliyeti",
		"label_select_config_fadeout": "Animasyon fadeo",
		"label_select_config_type": "Görüntü tipi",
		"label_select_config_shape": "Öngörülen görüntü",
		"label_config_timeout": "Uyarı zaman aşımı",
		"label_config_timeout_tooltiped": "Zaman aşımı uyarısı",
		"label_config_btnsave": "kurtarmak",
		"label_config_btnreset": "temizlemek",
		"label_config_requirements": "Gereksinim",
		"label_config_requirements_content": "- Uçları etkin kıl <br>",
		"label_config_usage": "kullanım",
		"label_config_usage_content": "- En iyi panel yapılandırması ve cada pupface (9). <br> &nbsp;. resim. <br> &nbsp;. başlık. <br> &nbsp;. Renkli. <br> &nbsp;. pozisyon. <br> &nbsp; .Farine de animacion. <br> &nbsp;. .. &nbsp;. tip. &nbsp;. şekil.. &nbsp;. süre. <br> - İzleyiciler kullanıldı pupfaces. <br> &nbsp;. denemek en proar antits of bit.. &nbsp;&nbsp;. Uyarı yalnızca test eden oyuncuda gösterilecektir. <br> &nbsp;. Şiirler bir başkasıyla tamamlanır, bir alerji izleyicileri olur. <br> ",
		"label_config_feedback_text": "Geribildirim",
		"label_config_a_send" : "göndermek",
		"label_config_support_text" : "* Bu uzantı size yardımcı olursa, desteğiniz çok iyi karşılanır ",
		"label_config_font_color" : "Yazı tipi rengi",
		"label_config_btntest" : "denemek",
		"label_overlay_preview" : "önizleme",
		"label_overlay_send" : "göndermek",
		"label_config_credits" : "kredi",
		"label_config_volumen" : "Ses seviyesi",
		"label_config_stream_pupface_btn" : "Akbaba akışları düğmesi",
		"tooltip_bits_config_complete" : "İçin bir pupface gönderdim",
		"label_config_volumen_tooltiped" : "Ses seviyesi",
		"label_config_confetti" : "konfeti",
		"tooltip_invalid_ext" : "<p>Geçersiz uzantı <br> Lütfen tekrar deneyin</p>",
		"tooltip_invalid_format" : "<p>Geçersiz biçim <br> Lütfen tekrar deneyin</p>",
		"tooltip_config_save" : "<p>Yapılandırma <b class='green-text'> Kayıtlı</b>!</p>",
		"tooltip_reset_tiers" : "<p>9 kademe sıfırlanacak. <br> Emin misiniz?<br><br><a class='btnAccept green white-text btn'>eğer</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'>değil</a></p>",
		"tooltip_reset_ok" : "<p>Yapılandırma <b class='red-text'> reset </b>!</p>",
		"tooltip_feedback_empty" : "Boş alan bırakmayın",
		"tooltip_feedback_ok" : "Geri bildiriminiz için teşekkür ederiz, en kısa zamanda yorumlarınızı anlayacağım.",
		"tooltip_feedback_error" : "Üzgünüm, bir hata oluştu ve geri bildiriminiz şu anda gönderilemedi.",
		"tooltip_bits_error" : "<p>Bir hata oluştu. Tekrar dene</p>",
		"tooltip_config_select_audio" : "ses",
		"tooltiped_label_config_audio" : "Bunun gibi genel bir açılır kutu bağlantısı kullanın: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> Biçimler Geçerli: <br> .mp3, .wav, .ogg",
		"label_config_iconres" : "Sohbet yanıtı",
		"label_leaderboard_viewer" : "izleyici",
		"label_leaderboard_times" : "kez",
		"label_leaderboard_spend" : "Kullanılan bit"
	},
	"cs":{
		"label_config_image": "Obrázek",
		"label_config_title": "název",
		"label_config_font": "Source",
		"label_config_glow_light": "Světlá barva",
		"label_config_glow_dark": "Dark color",
		"label_select_config_position": "pozice",
		"label_select_config_fadein": "Animace Fadein",
		"label_select_config_fadeout": "Animace Fadeout",
		"label_select_config_type": "Typ obrázku",
		"label_select_config_shape": "Obrazová forma",
		"label_config_timeout": "Timeout upozornění",
		"label_config_timeout_tooltiped": "Timeout upozornění",
		"label_config_btnsave": "save",
		"label_config_btnreset": "clean",
		"label_config_requirements": "Požadavky",
		"label_config_requirements_content": "- Aktivní bity ve vašem kanálu <br>",
		"label_config_usage": "Use",
		"label_config_usage_content": "- Na tomto panelu uložte konfiguraci pro každé pupface (9). <br> &nbsp;. Obrázek. <br> &nbsp;. Název. <br> ** * 9 ***. Barva. <br> &nbsp;. Pozice | <br> &nbsp;. Animace fadein. <br> &nbsp;. Animace fadeout. . <br> &nbsp;. Typ. <br> &nbsp;. Tvar. <br> &nbsp;. Trvání. - - Nechte své diváky používat loutky | <br> &nbsp;. Lze otestovat před odesláním pomocí bitů. <br> &nbsp;&nbsp;. Výstraha se zobrazí pouze na hráče, o kterém provede test. <br> &nbsp;. Pokud je bitový proces úspěšně dokončen, je výstraha odeslána všem divákům. <br> ",
		"label_config_feedback_text": "Feedback",
		"label_config_a_send": "Odeslat",
		"label_config_support_text": "* Pokud je toto rozšíření užitečné, je vaše podpora velmi dobře přijata",
		"label_config_font_color": "Barva písma",
		"label_config_btntest": "Test",
		"label_overlay_preview": "Náhled",
		"label_overlay_send": "Odeslat",
		"label_config_credits": "Úvěry",
		"label_config_volumen": "Hlasitost zvuku",
		"label_config_volumen_tooltiped": "Hlasitost zvuku",
		"label_config_confetti" : "Konfety",
		"label_config_stream_pupface_btn": "tlačítko pupfaces in stream",
		"tooltip_bits_config_complete": "Posílám pupface by",
		"tooltip_invalid_ext": "<p> Neplatné rozšíření <br> zkuste to znovu </p>",
		"tooltip_invalid_format": "<p> Neplatný formát <br> zkuste to znovu </p>",
		"tooltip_config_save": "<p> Konfigurace <b class='green-text'> Uloženo </b>! </p>",
		"tooltip_reset_tiers": "<p> 9 úrovní se resetuje. <br> Jste si jisti? <br> <br> <a class='btnAccept green white-text btn'> Ano </a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'> Ne </a> </p> ",
		"tooltip_reset_ok": "<p> Konfigurace <b class='red-text'> reset </b>! </p>",
		"tooltip_feedback_empty": "Nenechávejte žádná prázdná pole",
		"tooltip_feedback_ok": "Děkuji za vaši zpětnou vazbu, jakmile to bude možné, porozumím vašim komentářům.",
		"tooltip_feedback_error": "Litujeme, ale došlo k chybě a vaše zpětná vazba se v tuto chvíli nemohla odeslat.",
		"tooltip_bits_error": "<p> Došlo k chybě. Zkuste to znovu. </p>",
		"tooltip_config_select_audio": "Audio",
		"tooltiped_label_config_audio": "Použijte veřejný odkaz na tuto schránku: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br > <br> Platné formáty: <br> .mp3, .wav, .ogg ",
		"label_config_iconres": "Chat response",
		"label_leaderboard_viewer": "Viewer",
		"label_leaderboard_times": "Krát",
		"label_leaderboard_spend": "Použité bity"
	},
	"bg":{
		"label_config_image": "Изображение",
		"label_config_title": "заглавие",
		"label_config_font": "Източник",
		"label_config_glow_light": "Светъл цвят",
		"label_config_glow_dark": "Тъмният цвят",
		"label_select_config_position": "Позиция",
		"label_select_config_fadein": "Fadein за анимация",
		"label_select_config_fadeout": "Fadeout за анимация",
		"label_select_config_type": "Тип на изображението",
		"label_select_config_shape": "Форма за изображение",
		"label_config_timeout": "Време за изчакване на предупреждение",
		"label_config_timeout_tooltiped": "Време за изчакване на предупреждение",
		"label_config_btnsave": "запазване",
		"label_config_btnreset": "чист",
		"label_config_requirements": "Изисквания",
		"label_config_requirements_content": "- Активни битове във вашия канал <br>",
		"label_config_usage": "Използване",
		"label_config_usage_content": "- В този панел запишете конфигурацията за всеки pupface (9). <br> &nbsp;. Image. <br> &nbsp;. Title. <br> ** * 9 ***. Цвят. *** &nbsp;. Позиция. <br> &nbsp;. Изчезване на анимацията. <br> &nbsp;. Изчезване на анимацията. . <br> &nbsp;. Тип. *** &nbsp;. Форма. <br> &nbsp;. Продължителност. <br> - Нека вашите зрители използват pupfaces. <br> &nbsp;. Може да бъде тестван, преди да бъде изпратен с битове. <br> &nbsp;&nbsp;. Сигналът ще бъде показан само на играча, на когото прави ли теста. <br> &nbsp;. Ако битовият процес приключи успешно, предупреждението се изпраща на всички зрители. <br> ",
		"label_config_feedback_text": "Обратна връзка",
		"label_config_a_send": "Изпращане",
		"label_config_support_text": "* Ако това разширение е полезно, вашата подкрепа е много добре приета",
		"label_config_font_color": "Цвят на шрифта",
		"label_config_btntest": "Тест",
		"label_overlay_preview": "Визуализация",
		"label_overlay_send": "Изпращане",
		"label_config_credits": "Кредити",
		"label_config_volumen": "Звуков звук",
		"label_config_volumen_tooltiped": "Аудио звук",
		"label_config_confetti" : "конфети",
		"label_config_stream_pupface_btn": "бутони на бутон в поток",
		"tooltip_bits_config_complete": "Изпращам куриер от",
		"tooltip_invalid_ext": "<p> Невалидно разширение <br> Моля, опитайте отново </p>",
		"tooltip_invalid_format": "<p> Невалиден формат. Моля, опитайте отново </p>",
		"tooltip_config_save": "<p> Конфигурация <b class='green-text'> Записан </b>! </p>",
		"tooltip_reset_tiers": "<p> 9-те нива ще бъдат нулирани. <br> Сигурни ли сте? <br> <br> <a class='btnAccept green white-text btn'> Ano</a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'> Не </a> </p> ",
		"tooltip_reset_ok": "<p> Конфигурация <b class='red-text'> нулиране </b>! </p>",
		"tooltip_feedback_empty": "Не оставяйте празни полета",
		"tooltip_feedback_ok": "Благодаря ви за отзивите, възможно най-скоро ще коментирам вашите коментари.",
		"tooltip_feedback_error": "Съжалявам, но възникна грешка и обратната връзка не може да бъде изпратена понастоящем.",
		"tooltip_bits_error": "<p> Възникна грешка. Опитайте отново. </p>",
		"tooltip_config_select_audio": "Аудио",
		"tooltiped_label_config_audio": "Използвайте публична връзка в тази кутия като тази: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br > <br> Валидни формати: <br> .mp3, .wav, .ogg ",
		"label_config_iconres": "Отговор на чата",
		"label_leaderboard_viewer": "Преглед",
		"label_leaderboard_times": "пъти",
		"label_leaderboard_spend": "Използвани битове"
	},
	"pl":{
		"label_config_image": "Obraz",
		"label_config_title": "tytuł",
		"label_config_font": "Źródło",
		"label_config_glow_light": "Kolor światła",
		"label_config_glow_dark": "Ciemny kolor",
		"label_select_config_position": "Pozycja",
		"label_select_config_fadein": "Animacja zanikania",
		"label_select_config_fadeout": "Zanikanie animacji",
		"label_select_config_type": "Typ obrazu",
		"label_select_config_shape": "Forma obrazu",
		"label_config_timeout": "Limit czasu alarmu",
		"label_config_timeout_tooltiped": "Limit czasu alarmu",
		"label_config_btnsave": "zapisz",
		"label_config_btnreset": "czysty",
		"label_config_requirements": "Wymagania",
		"label_config_requirements_content": "- Aktywne bity na Twoim kanale <br>",
		"label_config_usage": "Użyj",
		"label_config_usage_content": "- W tym panelu zapisz konfigurację dla każdego pupface (9). <br> &nbsp;. Zdjęcie. <br> &nbsp;. Tytuł. <br> ** * 9 ***. Kolor. <br> &nbsp;. Pozycja. <br> &nbsp;. Zanikanie animacji. <br> &nbsp;. Zanikanie animacji. . <br> &nbsp;. Typ. <br> &nbsp;. Kształt. <br> &nbsp;. Czas trwania. <br> - Pozwól swoim widzom korzystać z pupfaces. <br> &nbsp;. Można przetestować przed wysłaniem za pomocą bitów. <br> &nbsp;* **** 9 9 ***. Ostrzeżenie zostanie wyświetlone tylko na odtwarzaczu, którego wykonuje test. <br> &nbsp;. Jeśli proces bitowy zakończy się pomyślnie, alert zostanie wysłany do wszystkich przeglądających. <br> ",
		"label_config_feedback_text": "Feedback",
		"label_config_a_send": "Wyślij",
		"label_config_support_text": "* Jeśli to rozszerzenie jest przydatne, twoje wsparcie jest bardzo dobrze odbierane",
		"label_config_font_color": "Kolor czcionki",
		"label_config_btntest": "Test",
		"label_overlay_preview": "Preview",
		"label_overlay_send": "Wyślij",
		"label_config_credits": "Kredyty",
		"label_config_volumen": "Głośność dźwięku",
		"label_config_volumen_tooltiped": "Głośność audio",
		"label_config_confetti" : "Konfetti",
		"label_config_stream_pupface_btn": "przyciski puppaces w strumieniu",
		"tooltip_bits_config_complete": "Wysyłam pupface przez",
		"tooltip_invalid_ext": "<p> Nieprawidłowe rozszerzenie <br> Spróbuj ponownie </p>",
		"tooltip_invalid_format": "<p> Nieprawidłowy format <br> Spróbuj ponownie </p>",
		"tooltip_config_save": "<p> Konfiguracja <b class='green-text'> Zapisano </b>! </p>",
		"tooltip_reset_tiers": "<p> 9 poziomów zostanie zresetowanych. <br> Jesteś pewien? <br> <br> <a class='btnAccept green white-text btn'> Tak </a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'> Nie </a> </p> ",
		"tooltip_reset_ok": "<p> Konfiguracja <b class='red-text'> reset </b>! </p>",
		"tooltip_feedback_empty": "Nie zostawiaj żadnych pustych pól",
		"tooltip_feedback_ok": "Dziękuję za opinie, jak najszybciej skomentuję twoje komentarze.",
		"tooltip_feedback_error": "Przepraszamy, ale wystąpił błąd i w tej chwili nie można wysłać Twojej opinii.",
		"tooltip_bits_error": "<p> Wystąpił błąd. Spróbuj ponownie. </p>",
		"tooltip_config_select_audio": "Audio",
		"tooltiped_label_config_audio": "Użyj publicznego linku Dropbox takiego: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br > <br> Poprawne formaty: <br> .mp3, .wav, .ogg ",
		"label_config_iconres": "Odpowiedź czatu",
		"label_leaderboard_viewer": "Przeglądarka",
		"label_leaderboard_times": "Czasy",
		"label_leaderboard_spend": "Używane bity"
	},
	"el":{
		"label_config_image": "Εικόνα",
		"label_config_title": "τίτλος",
		"label_config_font": "Πηγή",
		"label_config_glow_light": "Χρώμα φωτός",
		"label_config_glow_dark": "Σκούρο χρώμα",
		"label_select_config_position": "Θέση",
		"label_select_config_fadein": "Animation fadein",
		"label_select_config_fadeout": "Απεικόνιση animation",
		"label_select_config_type": "Τύπος εικόνας",
		"label_select_config_shape": "Μορφή εικόνας",
		"label_config_timeout": "Timeout προειδοποίησης",
		"label_config_timeout_tooltiped": "Timeout προειδοποίησης",
		"label_config_btnsave": "αποθήκευση",
		"label_config_btnreset": "καθαρό",
		"label_config_requirements": "Απαιτήσεις",
		"label_config_requirements_content": "- Ενεργά bits στο κανάλι σας",
		"label_config_usage": "Χρήση",
		"label_config_usage_content": "- Σε αυτόν τον πίνακα αποθηκεύστε τη διαμόρφωση για κάθε κουτάβι (9). *** &nbsp;. * 9 *** Χρώμα. *** &nbsp; Θέση. *** &nbsp; Ψυχαγωγία fadein. <br> &nbsp; Τύπος <br> &nbsp; Σχήμα <br> <br> &nbsp; Διάρκεια. puppies <br> <br> &nbsp; Μπορεί να δοκιμαστεί πριν από την αποστολή από τα bits <br> <br> 9 ***&nbsp; Η προειδοποίηση θα εμφανίζεται μόνο στον παίκτη από τον οποίο κάνει τη δοκιμή. <br> &nbsp; Εάν η διαδικασία bit ολοκληρωθεί με επιτυχία, η ειδοποίηση αποστέλλεται σε όλους τους θεατές.",
		"label_config_feedback_text": "Σχόλια",
		"label_config_a_send": "Αποστολή",
		"label_config_support_text": "* Εάν αυτή η επέκταση είναι χρήσιμη, η υποστήριξή σας λαμβάνει πολύ καλά",
		"label_config_font_color": "Χρώμα γραμματοσειράς",
		"label_config_btntest": "Δοκιμή",
		"label_overlay_preview": "Προεπισκόπηση",
		"label_overlay_send": "Αποστολή",
		"label_config_credits": "Πιστώσεις",
		"label_config_volumen": "Ένταση ήχου",
		"label_config_volumen_tooltiped": "Ένταση ήχου",
		"label_config_confetti" : "Κομφετί",
		"label_config_stream_pupface_btn": "κουτάλια κουμπιών σε ροή",
		"tooltip_bits_config_complete": "Στέλνω ένα κουτάβι από",
		"tooltip_invalid_ext": "<p> Μη έγκυρη επέκταση <br> Δοκιμάστε ξανά </p>",
		"tooltip_invalid_format": "<p> Μη έγκυρη μορφή <br> Δοκιμάστε ξανά </p>",
		"tooltip_config_save": "<p> Διαμόρφωση <b class='green-text'> Αποθηκευμένο </b>! </p>",
		"tooltip_reset_tiers": "<p> Οι 9 σειρές πρόκειται να επαναφερθούν. <br> Είστε σίγουροι; <br> <br> <a class='btnAccept green white-text btn'> Ναι </a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'> Όχι </a> </p> ",
		"tooltip_reset_ok": "<p> Ρύθμιση <b class='red-text'> επαναφορά </b>! </p>",
		"tooltip_feedback_empty": "Μην αφήνετε κενά πεδία",
		"tooltip_feedback_ok": "Σας ευχαριστώ για τα σχόλιά σας, το συντομότερο δυνατό θα σχολιάσω τα σχόλιά σας.",
		"tooltip_feedback_error": "Λυπούμαστε, αλλά παρουσιάστηκε ένα σφάλμα και τα σχόλιά σας δεν ήταν δυνατό να σταλούν αυτήν τη στιγμή.",
		"tooltip_bits_error": "<p> Παρουσιάστηκε σφάλμα. Δοκιμάστε ξανά. </p>",
		"tooltip_config_select_audio": "Ήχος",
		"tooltiped_label_config_audio": "Χρησιμοποιήστε έναν δημόσιο σύνδεσμο dropbox ως εξής: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br > <br> Ισχύουσες μορφές: .mp3, .wav, .ogg ",
		"label_config_iconres": "Απόκριση συνομιλίας",
		"label_leaderboard_viewer": "Προβολή",
		"label_leaderboard_times": "Οι χρόνοι",
		"label_leaderboard_spend": "Χρησιμοποιημένα bits"
	},
	"vi":{
		"label_config_image" : "Hình ảnh",
		"label_config_title" : "tiêu đề",
		"label_config_font" : "thư",
		"label_config_glow_light" : "Màu sáng",
		"label_config_glow_dark" : "Màu tối",
		"label_select_config_position" : "Vị trí",
		"label_select_config_fadein" : "Hoạt hình fadein",
		"label_select_config_fadeout" : "Hoạt hình mờ dần",
		"label_select_config_type" : "Loại hình ảnh",
		"label_select_config_shape" : "Hình ảnh",
		"label_config_timeout" : "Hết giờ báo",
		"label_config_timeout_tooltiped" : "Hết giờ báo",
		"label_config_btnsave" : "tiết kiệm",
		"label_config_btnreset" : "dọn dẹp",
		"label_config_requirements" : "Yêu cầu",
		"label_config_requirements_content" : "- Các bit hoạt động trong kênh của bạn<br>",
		"label_config_usage" : "Sử dụng",
		"label_config_usage_content" : "- Trong bảng này, lưu cấu hình cho mỗi con rối (9). <br> &nbsp;. Hình ảnh. <br> &nbsp;. Tiêu đề. <br> &nbsp;. Màu. <br> &nbsp;. Vị trí. <br> &nbsp;. Hoạt hình mờ dần. <br> &nbsp;. Mất dần hình ảnh động. <br> &nbsp;. Loại. <br> &nbsp;. Mẫu. <br> &nbsp;. Thời lượng. <br> - Cho phép người xem của bạn sử dụng các học sinh. <br> &nbsp;. Chúng có thể được kiểm tra trước khi gửi bằng bit. <br> &nbsp;&nbsp;. Cảnh báo sẽ chỉ được hiển thị trên người chơi đang thử nghiệm. <br> &nbsp;. Nếu quá trình bit được hoàn thành thành công, cảnh báo sẽ được gửi đến tất cả người xem. <br>",
		"label_config_feedback_text" : "Phản hồi",
		"label_config_a_send" : "Gửi",
		"label_config_support_text" : "* Nếu tiện ích mở rộng này giúp bạn, sự hỗ trợ của bạn rất được đón nhận",
		"label_config_font_color" : "Màu chữ",
		"label_config_btntest" : "Hãy thử",
		"label_overlay_preview" : "Xem trước",
		"label_overlay_send" : "Gửi",
		"label_config_credits" : "Tín dụng",
		"label_config_volumen" : "Âm lượng âm thanh",
		"label_config_volumen_tooltiped" : "Âm lượng âm thanh",
		"label_config_confetti" : "Confetti",
		"label_config_stream_pupface_btn" : "Nút con rối",
		"tooltip_bits_config_complete" : "Tôi gửi một con rối cho",
		"tooltip_invalid_ext" : "<p>Tiện ích mở rộng không hợp lệ <br> Vui lòng thử lại</p>",
		"tooltip_invalid_format" : "<p>Định dạng không hợp lệ <br> Vui lòng thử lại</p>",
		"tooltip_config_save" : "<p>Cấu hình <b class='green-text'>Đã lưu</b>!</p>",
		"tooltip_reset_tiers" : "<p>9 tầng sẽ được thiết lập lại. <br> Bạn có chắc chắn không?<br><br><a class='btnAccept green white-text btn'>Vâng</a></p> &nbsp;&nbsp; <a class='btnDecline red white-text btn'> Không </a> ",
		"tooltip_reset_ok" : "<p> Cấu hình <b class='red-text'> đặt lại </b>! </p>",
		"tooltip_feedback_empty" : "Đừng để bất kỳ trường trống",
		"tooltip_feedback_ok" : "Cảm ơn phản hồi của bạn, càng sớm càng tốt tôi sẽ hiểu ý kiến của bạn.",
		"tooltip_feedback_error" : "Tôi xin lỗi, nhưng đã xảy ra lỗi và không thể gửi phản hồi của bạn tại thời điểm này.",
		"tooltip_bits_error" : "<p>Có một lỗi. Thử lại</p>",
		"tooltip_config_select_audio" : "Âm thanh",
		"tooltiped_label_config_audio" : "Sử dụng liên kết dropbox công khai như thế này: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> <br> Định dạng Hợp lệ: <br> .mp3, .wav, .ogg",
		"label_config_iconres" : "Phản hồi trò chuyện",
		"label_leaderboard_viewer" : "Khán giả",
		"label_leaderboard_times" : "Thời đại",
		"label_leaderboard_spend" : "Bit được sử dụng"
	},
	"th":{
		"label_config_image" : "ภาพ",
		"label_config_title" : "ชื่อเรื่อง",
		"label_config_font" : "จดหมาย",
		"label_config_glow_light" : "สีอ่อน",
		"label_config_glow_dark" : "สีเข้ม",
		"label_select_config_position" : "ตำแหน่ง",
		"label_select_config_fadein" : "นิเมชั่น fadein",
		"label_select_config_fadeout" : "นิเมชั่น fadeout",
		"label_select_config_type" : "ประเภทภาพ",
		"label_select_config_shape" : "แบบฟอร์มรูปภาพ",
		"label_config_timeout" : "หมดเวลาการแจ้งเตือน",
		"label_config_timeout_tooltiped" : "หมดเวลาการแจ้งเตือน",
		"label_config_btnsave" : "ประหยัด",
		"label_config_btnreset" : "ทำความสะอาด",
		"label_config_requirements" : "ความต้องการ",
		"label_config_requirements_content" : "-บิตที่ใช้งานในช่องของคุณ<br>",
		"label_config_usage" : "ใช้",
		"label_config_usage_content" : "-ในแผงนี้บันทึกการกำหนดค่าสำหรับแต่ละ pupface (9) <br> &nbsp; รูปภาพ <br> &nbsp; ชื่อเรื่อง <br> &nbsp; สี <br> &nbsp; ตำแหน่ง <br> &nbsp; Animation fadein <br> &nbsp; Fadeout ของภาพเคลื่อนไหว <br> &nbsp; ประเภท <br> &nbsp; แบบฟอร์ม <br> &nbsp; ระยะเวลา <br> - ให้ผู้ชมของคุณใช้รูม่านตา <br> &nbsp; พวกเขาสามารถทดสอบก่อนที่จะส่งโดยบิต <br> &nbsp;&nbsp; การแจ้งเตือนจะปรากฏเฉพาะกับผู้เล่นที่กำลังทดสอบ <br> &nbsp; หากกระบวนการบิตเสร็จสิ้นสมบูรณ์การแจ้งเตือนจะถูกส่งไปยังผู้ดูทั้งหมด.<br>",
		"label_config_feedback_text" : "ผลตอบรับ",
		"label_config_a_send" : "ส่ง",
		"label_config_support_text" : "* หากส่วนขยายนี้ช่วยคุณได้รับการสนับสนุนของคุณเป็นอย่างดี",
		"label_config_font_color" : "สีตัวอักษร",
		"label_config_btntest" : "ความพยายาม",
		"label_overlay_preview" : "ภาพตัวอย่าง",
		"label_overlay_send" : "ส่ง",
		"label_config_credits" : "เครดิต",
		"label_config_volumen" : "ระดับเสียง",
		"label_config_volumen_tooltiped" : "ระดับเสียง",
		"label_config_confetti" : "ลูกปา",
		"label_config_stream_pupface_btn" : "สตรีมปุ่ม pupfaces",
		"tooltip_bits_config_complete" : "ฉันส่งภาพหน้าจอสำหรับ",
		"tooltip_invalid_ext" : "<p>ส่วนขยายไม่ถูกต้อง <br> โปรดลองอีกครั้ง</p>",
		"tooltip_invalid_format" : "<p>รูปแบบไม่ถูกต้อง <br> โปรดลองอีกครั้ง</p>",
		"tooltip_config_save" : "<p>การกำหนดค่า <b class = 'green-text'> บันทึกแล้ว</b>!</p>",
		"tooltip_reset_tiers" : "<p>ระดับ 9 จะถูกรีเซ็ต <br> คุณแน่ใจหรือไม่ <br> <br> <a class='btnAccept red white-text btn'> ใช่ </a> &nbsp;&nbsp; <a class='btnDecline red white-text btn'> ไม่</a></p>",
		"tooltip_reset_ok" : "<p>การกำหนดค่า <b class = 'red-text'> รีเซ็ต</b>!</p>",
		"tooltip_feedback_empty" : "อย่าปล่อยให้ฟิลด์ใด ๆ ว่างเปล่า",
		"tooltip_feedback_ok" : "ขอบคุณสำหรับความคิดเห็นของคุณโดยเร็วที่สุดฉันจะเข้าใจความคิดเห็นของคุณ",
		"tooltip_feedback_error" : "ขออภัยด้วยมีข้อผิดพลาดและไม่สามารถส่งความคิดเห็นของคุณได้ในขณะนี้.",
		"tooltip_bits_error" : "<p>มีข้อผิดพลาด ลองใหม่อีกครั้ง</p>",
		"tooltip_config_select_audio" : "เสียง",
		"tooltiped_label_config_audio" : "ใช้ลิงก์ดรอปบ็อกซ์สาธารณะเช่นนี้: <br> <br> <b> https://www.dropbox.com/s/mbyns3mabixdh4a/Bell10.wav?dl=0 </b> <br> รูปแบบ ถูกต้อง: <br> .mp3, .wav, .ogg",
		"label_config_iconres" : "ตอบสนองการแชท",
		"label_leaderboard_viewer" : "ผู้ชม",
		"label_leaderboard_times" : "ครั้ง",
		"label_leaderboard_spend" : "บิตที่ใช้"
	}
};