window.lang = {
	"es":{
		"label_config_save_credentials" : "Guardar datos",
		"label_config_requirements" : "Requerimientos",
		"label_config_requirements_content" : "- Es necesario que instales el siguiente plugin <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank'>OBS websocket</a>.<br>- Tienes que usar <a href='https://ngrok.com/' target='_blank'>ngrok.com</a> para crear una url publica de tu localhost.<br>- Una vez que accedas a ngrok usa las siguientes <a href='https://dashboard.ngrok.com/get-started' target='_blank'>instrucciones para ejecutar ngrok en tu computadora</a>, y el siguiente comando para crear tu url:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "Créditos",
		"label_config_usage" : "Uso",
		"label_config_usage_content" : "- Usa este panel para guardar tus credenciales.<br>- En tu dashboard de <b>twitch</b> en el panel de extensiones van aparecer:<br>&nbsp; . un botón  para iniciar/detener el streaming de OBS.<br>&nbsp; . un botón  por cada escena.<br>&nbsp; . un botón  para cerrar la coneccion a OBS.<br>- <b>Cuando el stream inicie</b>, en tu dashboard/canal <b>video</b> va estar un overlay con :<br>&nbsp; . un botón  para detener el stream de OBS.<br>&nbsp; .  un botón  por cada escena.<br>&nbsp; . un botón  para cerrar la coneccion a OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Si la extension <b class='red-text'>no puede conectarse</b> a OBS, mostrara un login para poder cambiar tus credenciales</emp>.<br>",
		"label_config_feedback_text" : "Feedback",
		"label_config_a_send" : "Enviar",
		"label_config_support_text" : "* Si te sirve esta extensión tu apoyo es muy bien recibido ",
		"label_obs_error_credential" : "<p>Revisa tus credenciales y prueba de nuevo <b class='red-text'>error</b></p>",
		"label_obs_connect"  : "conectar",
		"label_obs_close"  : "cerrar",
		"label_obs_empty"  : "<p>No dejes ningun campo <b class='red-text'>vacío</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'>conectado</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Buscando</b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Buscando</b> de nuevo OBS</p>",
		"label_only_broadcast_view" : "<b>Lo siento<br>solo vista de <br>Emisor<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "No dejes ningun campo vacío",
		"tooltip_feedback_ok" : "Gracias por tu feedback, lo mas pronto posible atendere tus comentarios.",
		"tooltip_feedback_error" : "Lo siente, pero hubo un error y no se pudo mandar tu feedback en este momento.",
		"tooltip_invalid_format" : "<p>Formato invalido<br>Por favor revisa tu url</p>",
		"tooltip_config_save" : "<p>Configuracion <b class='green-text'>guardada</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>La url tiene que tener el siguiente formato:<br><br> <b>wss://</b>a93a7c2255.ngrok.io<br><br>La mejor forma y más fácil de obtener una url pública para tu localhost es usar <a href='https://ngrok.com/' target='_blank'>ngrok.com</a></p>"
	},
	"es-mx":{
		"label_config_save_credentials" : "Guardar datos",
		"label_config_requirements" : "Requerimientos",
		"label_config_requirements_content" : "- Es necesario que instales el siguiente plugin <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank'>OBS websocket</a>.<br>- Tienes que usar <a href='https://ngrok.com/' target='_blank'>ngrok.com</a> para crear una url publica de tu localhost.<br>- Una vez que accedas a ngrok usa las siguientes <a href='https://dashboard.ngrok.com/get-started' target='_blank'>instrucciones para ejecutar ngrok en tu computadora</a>, y el siguiente comando para crear tu url:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "Créditos",
		"label_config_usage" : "Uso",
		"label_config_usage_content" : "- Usa este panel para guardar tus credenciales.<br>- En tu dashboard de <b>twitch</b> en el panel de extensiones van aparecer:<br>&nbsp; . un botón  para iniciar/detener el streaming de OBS.<br>&nbsp; . un botón  por cada escena.<br>&nbsp; . un botón  para cerrar la coneccion a OBS.<br>- <b>Cuando el stream inicie</b>, en tu dashboard/canal <b>video</b> va estar un overlay con :<br>&nbsp; . un botón  para detener el stream de OBS.<br>&nbsp; .  un botón  por cada escena.<br>&nbsp; . un botón  para cerrar la coneccion a OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Si la extension <b class='red-text'>no puede conectarse</b> a OBS, mostrara un login para poder cambiar tus credenciales</emp>.<br>",
		"label_config_feedback_text" : "Feedback",
		"label_config_a_send" : "Enviar",
		"label_config_support_text" : "* Si te sirve esta extensión tu apoyo es muy bien recibido ",
		"label_obs_error_credential" : "<p>Revisa tus credenciales y prueba de nuevo <b class='red-text'>error</b></p>",
		"label_obs_connect"  : "conectar",
		"label_obs_close"  : "cerrar",
		"label_obs_empty"  : "<p>No dejes ningun campo <b class='red-text'>vacío</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'>conectado</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Buscando</b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Buscando</b> de nuevo OBS</p>",
		"label_only_broadcast_view" : "<b>Lo siento<br>solo vista de <br>Emisor<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "No dejes ningun campo vacío",
		"tooltip_feedback_ok" : "Gracias por tu feedback, lo mas pronto posible atendere tus comentarios.",
		"tooltip_feedback_error" : "Lo siente, pero hubo un error y no se pudo mandar tu feedback en este momento.",
		"tooltip_invalid_format" : "<p>Formato invalido<br>Por favor revisa tu url</p>",
		"tooltip_config_save" : "<p>Configuracion <b class='green-text'>guardada</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>La url tiene que tener el siguiente formato:<br><br> <b>wss://</b>a93a7c2255.ngrok.io<br><br>La mejor forma y más fácil de obtener una url pública para tu localhost es usar <a href='https://ngrok.com/' target='_blank'>ngrok.com</a></p>"
	},
	"de":{
		"label_config_save_credentials" : "Daten speichern",
		"label_config_requirements" : "Anforderungen",
		"label_config_requirements_content" : "- Sie müssen das folgende Plugin installieren <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank'>OBS websocket</a>.<br>- Sie müssen <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> verwenden, um eine öffentliche URL Ihres lokalen Hosts zu erstellen.<br>- Wenn Sie auf ngrok zugreifen, verwenden Sie die folgenden <a href='https://dashboard.ngrok.com/get-started' target='_blank'> Anweisungen, um ngrok auf Ihrem Computer auszuführen </a>. und den folgenden Befehl, um Ihre URL zu erstellen:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "Credits",
		"label_config_usage" : "Verwenden Sie",
		"label_config_usage_content" : "- In diesem Bereich können Sie Ihre Anmeldeinformationen speichern. <br> - In Ihrem Dashboard von <b> twitch </b> werden sie im Erweiterungsbereich angezeigt:<br>&nbsp; . eine Schaltfläche zum Starten / Stoppen des Streamings von OBS.<br>&nbsp; . eine Taste für jede Szene.<br>&nbsp; . uKlicken Sie auf die Schaltfläche n, um die Verbindung zu OBS zu beenden. <br> - <b> Wenn der Stream startet </b>, wird in Ihrem Dashboard / Channel-Video </b> eine Überlagerung mit angezeigt :<br>&nbsp; . uTaste n zum Stoppen des OBS-Streams.<br>&nbsp; .  Eine Taste für jede Szene.<br>&nbsp; . eine Schaltfläche, um die Verbindung zu OBS zu beenden.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Wenn die Erweiterung <b class='red-text'> keine Verbindung zu OBS herstellen kann </b>, wird ein Login angezeigt, um Ihre Anmeldeinformationen zu ändern</emp>.<br>",
		"label_config_feedback_text" : "Rückmeldung",
		"label_config_a_send" : "Senden",
		"label_config_support_text" : "* Wenn Ihnen diese Erweiterung hilft, wird Ihre Unterstützung sehr gut angenommen",
		"label_obs_error_credential" : "<p>Überprüfen Sie Ihre Anmeldeinformationen und versuchen Sie es erneut <b class='red-text'>error</b></p>",
		"label_obs_connect"  : "verbinden",
		"label_obs_close"  : "hautnah",
		"label_obs_empty"  : "<p>Lassen Sie keine Felder <b class='red-text'>leer</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'>verbunden</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Suche in</b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Suche </b> erneut nach OBS</p>",
		"label_only_broadcast_view" : "<b>Nur leider Ansicht des Emittenten <br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Lassen Sie kein leeres Feld",
		"tooltip_feedback_ok" : "Vielen Dank für Ihr Feedback. Ich werde Ihre Kommentare so schnell wie möglich verstehen.",
		"tooltip_feedback_error" : "Entschuldigung, aber es gab einen Fehler und Ihr Feedback konnte zu diesem Zeitpunkt nicht gesendet werden.",
		"tooltip_invalid_format" : "<p>Ungültiges Format <br> Bitte überprüfen Sie Ihre URL</p>",
		"tooltip_config_save" : "<p>Einstellungen <b class='green-text'>gespeichert</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>Die URL muss das folgende Format haben:<br><br> <b>wss://</b>a93a7c2255.ngrok.io<br><br> Der beste und einfachste Weg, eine URL zu erhalten Für die Veröffentlichung Ihres lokalen Hosts verwenden Sie <a href='https://ngrok.com/' target='_blank'>ngrok.com</a></p>"
	},
	"zh":{
		"label_config_save_credentials" : "保存数据",
		"label_config_requirements" : "要求",
		"label_config_requirements_content" : "-您需要安装以下插件<a href = 'https：//obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank'>OBS网络套接字</a>。<br>-您必须使用<a href='https://ngrok.com/' target='_blank'> ngrok.com</a>创建本地主机的公共URL。<br>-访问ngrok后，使用以下<a href='https：//dashboard.ngrok.com/get-started' target='_blank'>在计算机上运行ngrok的说明</a>，并使用以下命令创建您的网址：<br><emp>ngrok http {obs port} <br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "学分",
		"label_config_usage" : "使用",
		"label_config_usage_content" : "- 使用此面板保存您的凭据<br>-在扩展面板中<b>抽动</b>的信息中心中，它们将出现:<br>&nbsp; .启动/停止流OBS的按钮.<br>&nbsp; . 每个场景一个按钮。<br>&nbsp; . 一个按钮以关闭与OBS的连接。<br>-<b>流开始</b>时，在您的仪表板/频道<b>视频</b>上将出现一个覆盖 :<br>&nbsp; . 停止OBS流的按钮.<br>&nbsp; .  每个场景一个按钮.<br>&nbsp; . 一个按钮以关闭与OBS的连接.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* 如果扩展<b class='red-text'>无法连接</b>到OBS，它将显示登录名以更改您的凭据</emp>.<br>",
		"label_config_feedback_text" : "反馈",
		"label_config_a_send" : "反馈",
		"label_config_support_text" : "*如果此扩展程序对您有所帮助，那么您的支持将非常受欢迎",
		"label_obs_error_credential" : "<p>检查您的凭据，然后重试<b class='red-text'>错误</b></p>",
		"label_obs_connect"  : "连",
		"label_obs_close"  : "关闭",
		"label_obs_empty"  : "<p>不要保留任何字段<b class='red-text'>空</b>！</p>",
		"label_obs_connected" : "<p> OBS <b class='green-text '>已连接</b> </p>",
		"label_obs_check" : "<p> <b class='orange-text'>搜索</b> OBS</p>",
		"label_obs_check_again" : "<p> <b class='blue-text'>再次寻找</b> OBS </p>",
		"label_only_broadcast_view" : "<b>对不起，颁发者的单一视图<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "不要留下任何空白",
		"tooltip_feedback_ok" : "感谢您的反馈，我们将尽快理解您的评论。",
		"tooltip_feedback_error" : "抱歉，出现了错误，目前无法发送您的反馈。",
		"tooltip_invalid_format" : "<p>格式无效<br>请检查您的网址</p>",
		"tooltip_config_save" : "<p>设置<b class='orange-text'>已保存</b>！</p>",
		"tooltip_config_label_url_tooltiped" : "<p>网址必须具有以下格式：<br><br><b>wss：//</b>a93a7c2255.ngrok.io <br><br>最好的和最简单的方法来获取您的公共网址 本地主机要使用<a href='https://ngrok.com/' target='_blank'> ngrok.com</a></p>"
	},
	"zh-cn":{
		"label_config_save_credentials" : "保存数据",
		"label_config_requirements" : "要求",
		"label_config_requirements_content" : "-您需要安装以下插件<a href = 'https：//obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank'>OBS网络套接字</a>。<br>-您必须使用<a href='https://ngrok.com/' target='_blank'> ngrok.com</a>创建本地主机的公共URL。<br>-访问ngrok后，使用以下<a href='https：//dashboard.ngrok.com/get-started' target='_blank'>在计算机上运行ngrok的说明</a>，并使用以下命令创建您的网址：<br><emp>ngrok http {obs port} <br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "学分",
		"label_config_usage" : "使用",
		"label_config_usage_content" : "- 使用此面板保存您的凭据<br>-在扩展面板中<b>抽动</b>的信息中心中，它们将出现:<br>&nbsp; .启动/停止流OBS的按钮.<br>&nbsp; . 每个场景一个按钮。<br>&nbsp; . 一个按钮以关闭与OBS的连接。<br>-<b>流开始</b>时，在您的仪表板/频道<b>视频</b>上将出现一个覆盖 :<br>&nbsp; . 停止OBS流的按钮.<br>&nbsp; .  每个场景一个按钮.<br>&nbsp; . 一个按钮以关闭与OBS的连接.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* 如果扩展<b class='red-text'>无法连接</b>到OBS，它将显示登录名以更改您的凭据</emp>.<br>",
		"label_config_feedback_text" : "反馈",
		"label_config_a_send" : "反馈",
		"label_config_support_text" : "*如果此扩展程序对您有所帮助，那么您的支持将非常受欢迎",
		"label_obs_error_credential" : "<p>检查您的凭据，然后重试<b class='red-text'>错误</b></p>",
		"label_obs_connect"  : "连",
		"label_obs_close"  : "关闭",
		"label_obs_empty"  : "<p>不要保留任何字段<b class='red-text'>空</b>！</p>",
		"label_obs_connected" : "<p> OBS <b class='green-text '>已连接</b> </p>",
		"label_obs_check" : "<p> <b class='orange-text'>搜索</b> OBS</p>",
		"label_obs_check_again" : "<p> <b class='blue-text'>再次寻找</b> OBS </p>",
		"label_only_broadcast_view" : "<b>对不起，颁发者的单一视图<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "不要留下任何空白",
		"tooltip_feedback_ok" : "感谢您的反馈，我们将尽快理解您的评论。",
		"tooltip_feedback_error" : "抱歉，出现了错误，目前无法发送您的反馈。",
		"tooltip_invalid_format" : "<p>格式无效<br>请检查您的网址</p>",
		"tooltip_config_save" : "<p>设置<b class='orange-text'>已保存</b>！</p>",
		"tooltip_config_label_url_tooltiped" : "<p>网址必须具有以下格式：<br><br><b>wss：//</b>a93a7c2255.ngrok.io <br><br>最好的和最简单的方法来获取您的公共网址 本地主机要使用<a href='https://ngrok.com/' target='_blank'> ngrok.com</a></p>"
	},
	"zh-tw":{
		"label_config_save_credentials" : "保存数据",
		"label_config_requirements" : "要求",
		"label_config_requirements_content" : "-您需要安装以下插件<a href = 'https：//obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank'>OBS网络套接字</a>。<br>-您必须使用<a href='https://ngrok.com/' target='_blank'> ngrok.com</a>创建本地主机的公共URL。<br>-访问ngrok后，使用以下<a href='https：//dashboard.ngrok.com/get-started' target='_blank'>在计算机上运行ngrok的说明</a>，并使用以下命令创建您的网址：<br><emp>ngrok http {obs port} <br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "学分",
		"label_config_usage" : "使用",
		"label_config_usage_content" : "- 使用此面板保存您的凭据<br>-在扩展面板中<b>抽动</b>的信息中心中，它们将出现:<br>&nbsp; .启动/停止流OBS的按钮.<br>&nbsp; . 每个场景一个按钮。<br>&nbsp; . 一个按钮以关闭与OBS的连接。<br>-<b>流开始</b>时，在您的仪表板/频道<b>视频</b>上将出现一个覆盖 :<br>&nbsp; . 停止OBS流的按钮.<br>&nbsp; .  每个场景一个按钮.<br>&nbsp; . 一个按钮以关闭与OBS的连接.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* 如果扩展<b class='red-text'>无法连接</b>到OBS，它将显示登录名以更改您的凭据</emp>.<br>",
		"label_config_feedback_text" : "反馈",
		"label_config_a_send" : "反馈",
		"label_config_support_text" : "*如果此扩展程序对您有所帮助，那么您的支持将非常受欢迎",
		"label_obs_error_credential" : "<p>检查您的凭据，然后重试<b class='red-text'>错误</b></p>",
		"label_obs_connect"  : "连",
		"label_obs_close"  : "关闭",
		"label_obs_empty"  : "<p>不要保留任何字段<b class='red-text'>空</b>！</p>",
		"label_obs_connected" : "<p> OBS <b class='green-text '>已连接</b> </p>",
		"label_obs_check" : "<p> <b class='orange-text'>搜索</b> OBS</p>",
		"label_obs_check_again" : "<p> <b class='blue-text'>再次寻找</b> OBS </p>",
		"label_only_broadcast_view" : "<b>对不起，颁发者的单一视图<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "不要留下任何空白",
		"tooltip_feedback_ok" : "感谢您的反馈，我们将尽快理解您的评论。",
		"tooltip_feedback_error" : "抱歉，出现了错误，目前无法发送您的反馈。",
		"tooltip_invalid_format" : "<p>格式无效<br>请检查您的网址</p>",
		"tooltip_config_save" : "<p>设置<b class='orange-text'>已保存</b>！</p>",
		"tooltip_config_label_url_tooltiped" : "<p>网址必须具有以下格式：<br><br><b>wss：//</b>a93a7c2255.ngrok.io <br><br>最好的和最简单的方法来获取您的公共网址 本地主机要使用<a href='https://ngrok.com/' target='_blank'> ngrok.com</a></p>"
	},
	"ja":{
		"label_config_save_credentials" : "データを保存する",
		"label_config_requirements" : "必要条件",
		"label_config_requirements_content" : "-次のプラグインをインストールする必要があります<a href='https：//obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank'>OBS websocket</a>。<br>-<a href='https://ngrok.com/' target='_blank'>ngrok.com</a>ローカルホストのパブリックURLを作成します。<br>-ngrokにアクセスしたら、次の<a href='https：//dashboard.ngrok.com/get-started ' target ='_blank'>コンピューターでngrokを実行するための指示</a>、およびURLを作成する次のコマンド：<br> <emp> ngrok http {obs port} <br><b> ngrok http 4444 </b> <br> </emp> <br>",
		"label_config_credits" : "クレジット",
		"label_config_usage" : "使用する",
		"label_config_usage_content" : "- このパネルを使用して、資格情報を保存します。<br>-拡張機能パネルの<b> twitch </ b>のダッシュボードに表示されます。:<br>&nbsp; . OBSのストリーミングを開始/停止するボタン.<br>&nbsp; . 各シーンに1つのボタン.<br>&nbsp; .OBSへの接続を閉じるボタン<br>-<b>ストリームの開始</ b>、ダッシュボード/チャンネル<b>ビデオ</ b>にオーバーレイが表示されます :<br>&nbsp; . OBSストリームを停止するボタン.<br>&nbsp; .  各シーンに1つのボタン.<br>&nbsp; . OBSへの接続を閉じるボタン.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* 拡張機能<b class='red-text'>がOBSに接続できない場合</ b>は、ログイン情報を表示して資格情報を変更します</emp>.<br>",
		"label_config_feedback_text" : "フィードバック",
		"label_config_a_send" : "送る",
		"label_config_support_text" : "* この拡張機能が役立つ場合、あなたのサポートは非常に好評です ",
		"label_obs_error_credential" : "<p>資格情報を確認して、もう一度やり直してください<b class='red-text'>エラー</b></p>",
		"label_obs_connect"  : "つなぐ",
		"label_obs_close"  : "クローズアップ",
		"label_obs_empty"  : "<p>フィールド<b class='red-text'>を空のままにしないでください</ b>！</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'>接続</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>検索</b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>再度検索</b>OBS</p>",
		"label_only_broadcast_view" : "<b>発行者の<br>単一ビュー<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "空のフィールドを残さないでください",
		"tooltip_feedback_ok" : "ご意見をお寄せいただきありがとうございます。できるだけ早くあなたのコメントを理解します。",
		"tooltip_feedback_error" : "申し訳ありませんが、エラーが発生したため、現時点ではフィードバックを送信できませんでした。",
		"tooltip_invalid_format" : "<p>無効な形式<br> URLを確認してください</p>",
		"tooltip_config_save" : "<p>設定<b class='green-text'>保存済み</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>URLは次の形式である必要があります：<br><br><b>wss：//</b>a93a7c2255.ngrok.io<br><br>localhostは<a href='https://ngrok.com/' target='_blank'>ngrok.com</a>を使用します</p>"
	},
	"ko":{
		"label_config_save_credentials" : "데이터 저장",
		"label_config_requirements" : "요구 사항",
		"label_config_requirements_content" : "-다음 플러그인을 설치해야합니다 <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank'> OBS 웹 소켓 </a> <br>-<a href='https://ngrok.com/' target='_blank'> ngrok.com </a> 로컬 호스트의 공개 URL을 만들려면 <br>-ngrok에 액세스하면 다음 <a href='https://dashboard.ngrok.com/get-started' target='_blank'> 컴퓨터에서 ngrok를 실행하기위한 지침 </a> 및 다음 명령을 사용하여 URL을 만드십시오. <br><emp> ngrok http {obs port} <br><b> ngrok http 4444 </b><br></emp><br>",
		"label_config_credits" : "크레딧",
		"label_config_usage" : "사용",
		"label_config_usage_content" : "- 이 패널을 사용하여 자격 증명을 저장하십시오. <br>-확장 패널의 <b> twitch </b> 대시 보드에 <br>&nbsp; . OBS 스트리밍을 시작 / 중지하는 버튼.<br>&nbsp;. 각 장면마다 하나의 버튼.<br>&nbsp; . OBS와의 연결을 닫는 버튼.<br>- <b>스트림이 시작되면 </b> 대시 보드 / 채널 <b> 비디오 </ b>에 오버레이가 표시됩니다 :<br>&nbsp; .OBS 스트림을 중지하는 버튼.<br>&nbsp; .  각 장면마다 하나의 버튼.<br>&nbsp;. OBS와의 연결을 닫는 버튼.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>*확장명 <b class='red-text'>가 </b> OBS에 연결할 수없는 경우 자격 증명을 변경하기위한 로그인이 표시됩니다.</emp>.<br>",
		"label_config_feedback_text" : "피드백",
		"label_config_a_send" : "보내기",
		"label_config_support_text" : "* 이 확장 프로그램이 도움이 되시면 귀하의 지원이 매우 잘 전달됩니다 ",
		"label_obs_error_credential" : "<p>자격 증명을 확인하고 <b class='red-text'> 오류를 다시 시도하십시오.</b></p>",
		"label_obs_connect"  : "연결",
		"label_obs_close"  : "닫다",
		"label_obs_empty"  : "<p><b class='red-text'> 필드를 비워 두지 마십시오</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'>연결됨</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>검색 </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>다시 찾고</b> OBS</p>",
		"label_only_broadcast_view" : "<b>발행자에 대한 미안 <br> 단일 뷰<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "빈 칸을 두지 마십시오",
		"tooltip_feedback_ok" : "의견을 보내 주셔서 감사합니다. 가능한 빨리 의견을 이해하겠습니다..",
		"tooltip_feedback_error" : "죄송합니다. 오류가 발생하여 의견을 보내실 수 없습니다..",
		"tooltip_invalid_format" : "<p>잘못된 형식 <br> URL을 확인하십시오</p>",
		"tooltip_config_save" : "<p>설정 <b class='green-text'>저장되었습니다</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>URL은 다음 형식이어야합니다. <br><br> wss://</b>a93a7c2255.ngrok.io <br><br> 귀하의 공개 URL을 얻는 가장 쉽고 쉬운 방법 localhost는 <a href='https://ngrok.com/' target='_blank'> ngrok.com </a>을 사용하는 것입니다</p>"
	},
	"da":{
		"label_config_save_credentials" : "Gem data",
		"label_config_requirements" : "krav",
		"label_config_requirements_content" : "- Du skal installere følgende plugin <a href = 'https: //obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS websocket </a>. <br> - Du skal bruge <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> for at oprette en offentlig url til din localhost . <br> - Når du har adgang til ngrok, skal du bruge følgende <a href='https://dashboard.ngrok.com/get-started' target='_blank'> instruktioner til at køre ngrok på din computer </a> , og følgende kommando for at oprette din url: <br> <emp> ngrok http {obs port} <br> <b> ngrok http 4444 </b> <br> </emp> <br>",
		"label_config_credits" : "kreditter",
		"label_config_usage" : "brug",
		"label_config_usage_content" : "- Brug dette panel til at gemme dine legitimationsoplysninger. <br> - I dit betjeningspanel til <b> rykk </b> i udvidelsespanelet vises de:<br>&nbsp; . en knap for at starte / stoppe streaming af OBS.<br>&nbsp; . en knap til hver scene.<br>&nbsp; . en knap for at lukke forbindelsen til OBS. <br> - <b> Når strømmen starter </b>, på dit dashboard / kanal <b> video </b> vil der være en overlay med:<br>&nbsp; .en knap for at stoppe OBS-strømmen.<br>&nbsp; . En knap til hver scene.<br>&nbsp; . en knap for at lukke forbindelsen til OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Hvis udvidelsen <b class='red-text'> ikke kan oprette forbindelse </b> til OBS, viser den et login for at ændre dine legitimationsoplysninger</emp>.<br>",
		"label_config_feedback_text" : "tilbagemeldinger",
		"label_config_a_send" : "sende",
		"label_config_support_text" : "* Hvis denne udvidelse hjælper dig, modtages din support meget godt ",
		"label_obs_error_credential" : "<p>Kontroller dine legitimationsoplysninger, og prøv igen <b class='red-text'>fejl</b></p>",
		"label_obs_connect"  : "forbinde",
		"label_obs_close"  : "tæt på",
		"label_obs_empty"  : "<p>Efterlad ikke noget felt <b class='red-text'>tom</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> tilsluttet</b></p>",
		"label_obs_check" : "<p><b class 'orange-text'> Søger </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>På udkig efter </b> igen OBS</p>",
		"label_only_broadcast_view" : "<b>Leller jeg føler det eneste syn på Udstederen<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Efterlad ikke noget tomt felt",
		"tooltip_feedback_ok" : "Tak for din feedback, så snart som muligt forstår jeg dine kommentarer.",
		"tooltip_feedback_error" : "Beklager, men der opstod en fejl, og din feedback kunne ikke sendes på dette tidspunkt.",
		"tooltip_invalid_format" : "<p>Ugyldigt format - Tjek venligst din url</p>",
		"tooltip_config_save" : "<p>Indstillinger <b class='green-text'> gemt</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>Url'en skal have følgende format: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> Den bedste og nemmeste måde at få en offentlig url til din localhost er at bruge <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"fr":{
		"label_config_save_credentials" : "Sauvegarder les données",
		"label_config_requirements" : "Les exigences",
		"label_config_requirements_content" : "- Vous devez installer le plugin suivant <a href = 'https: //obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank'> OBS websocket </a>. <br> - Vous devez utiliser <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> pour créer une URL publique de votre localhost. <br> - Une fois que vous avez accédé à ngrok, utilisez les <a href='https://dashboard.ngrok.com/get-started' target='_blank'> instructions suivantes pour exécuter ngrok sur votre ordinateur </ a >, et la commande suivante pour créer votre URL: <br> <emp> ngrok http {obs port} <br> <b> ngrok http 4444 </b> <br> </emp> <br>",
		"label_config_credits" : "Crédits",
		"label_config_usage" : "Utiliser",
		"label_config_usage_content" : "- Utilisez ce panneau pour enregistrer vos informations d'identification. <br> - Dans votre tableau de bord de <b> twitch </b> du panneau des extensions, ils apparaîtront.:<br>&nbsp; . un bouton pour démarrer / arrêter le streaming OBS.<br>&nbsp; . un bouton pour chaque scène.<br>&nbsp; . un bouton pour fermer la connexion à OBS.<br>- <b>Lorsque le flux commence </ b>, sur votre tableau de bord / canal <b> vidéo </b>, il y aura une superposition avec :<br>&nbsp; . un bouton pour arrêter le flux OBS.<br>&nbsp; .  un bouton pour chaque scène.<br>&nbsp; . un bouton pour fermer la connexion à OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Si l'extension <b class='red-text'> ne peut pas se connecter </b> à OBS, un nom d'utilisateur vous permettant de modifier vos informations d'identification s'affiche.</emp>.<br>",
		"label_config_feedback_text" : "Commentaires",
		"label_config_a_send" : "Envoyer",
		"label_config_support_text" : "* Si cette extension vous aide, votre support est très bien reçu ",
		"label_obs_error_credential" : "<p>Vérifiez vos informations d'identification et réessayez <b class='red-text'> error </b>.</p>",
		"label_obs_connect"  : "connecter",
		"label_obs_close"  : "fermer",
		"label_obs_empty"  : "<p>Ne laissez aucun champ <b class='red-text'>vide</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> connecté</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Recherche </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>À la recherche de </b> à nouveau OBS</p>",
		"label_only_broadcast_view" : "<b>Désolé pour une seule vue de l'émetteur<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Ne laissez aucun champ vide",
		"tooltip_feedback_ok" : "Merci pour vos commentaires, dès que possible je comprendrai vos commentaires.",
		"tooltip_feedback_error" : "Désolé, une erreur s'est produite et vos commentaires n'ont pas pu être envoyés pour le moment..",
		"tooltip_invalid_format" : "<p>Format invalide <br> Veuillez vérifier votre URL</p>",
		"tooltip_config_save" : "<p>Paramètres <b class='green-text'> sauvegardés</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>Le format de l’URL doit être le suivant: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> Le meilleur moyen de créer une URL publique pour votre localhost doit utiliser <a href='https://ngrok.com/' target='_blank'> ngrok.com</a></p>"
	},
	"it":{
		"label_config_save_credentials" : "Salva i dati",
		"label_config_requirements" : "requisiti",
		"label_config_requirements_content" : "- Devi installare il seguente plugin <a href = 'https: //obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS websocket </a>. <br> - Devi utilizzare <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> per creare un URL pubblico del tuo host locale . <br> - Dopo aver effettuato l'accesso a ngrok, utilizza le seguenti <a href='https://dashboard.ngrok.com/get-started' target='_blank'> per eseguire ngrok sul tuo computer </a> e il seguente comando per creare l'URL:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "crediti",
		"label_config_usage" : "uso",
		"label_config_usage_content" : "- Usa questo pannello per salvare le tue credenziali. <br> - Appariranno nella dashboard di <b> twitch </b> nel pannello delle estensioni:<br>&nbsp; . un pulsante per avviare / interrompere lo streaming di OBS.<br>&nbsp; . un pulsante per ogni scena.<br>&nbsp; . un pulsante per chiudere la connessione a OBS.<br>- <b>All'avvio dello stream </b>, nella dashboard / canale <b> video </b> verrà visualizzato un overlay :<br>&nbsp; .un pulsante per interrompere il flusso OBS.<br>&nbsp; .  Un pulsante per ogni scena.<br>&nbsp; . un pulsante per chiudere la connessione a OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Se l'estensione <b class='red-text'> non riesce a connettersi </b> a OBS, mostrerà un login per cambiare le tue credenziali</emp>.<br>",
		"label_config_feedback_text" : "feedback",
		"label_config_a_send" : "inviare",
		"label_config_support_text" : "* Se questa estensione ti aiuta, il tuo supporto è molto ben accolto",
		"label_obs_error_credential" : "<p>Controlla le tue credenziali e riprova <b class='red-text'> errore</b></p>",
		"label_obs_connect"  : "connettersi",
		"label_obs_close"  : "da vicino",
		"label_obs_empty"  : "<p>Non lasciare alcun campo <b class='red-text'> vuoto</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> connesso</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Ricerca </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Alla ricerca di </b> di nuovo OBS</p>",
		"label_only_broadcast_view" : "<b>Siamo spiacenti <br> visualizzazione singola dell'Emittente<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Non lasciare alcun campo vuoto",
		"tooltip_feedback_ok" : "Non lasciare campi vuoti.Grazie per il tuo feedback, appena possibile commenterò.",
		"tooltip_feedback_error" : "Siamo spiacenti, si è verificato un errore e al momento non è stato possibile inviare il tuo feedback.",
		"tooltip_invalid_format" : "<p>Formato non valido <br> Controlla l'URL</p>",
		"tooltip_config_save" : "<p>Impostazioni <b class='green-text'> salvate</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>L'URL deve avere il seguente formato: <br> <br> <b>wss://</b>a93a7c2255.ngrok.io <br> <br> Il modo migliore e più semplice per ottenere un URL pubblico per il tuo localhost deve utilizzare <a href='https://ngrok.com/' target='_blank'>ngrok.com</a></p>"
	},
	"hu":{
		"label_config_save_credentials" : "Adatok mentése",
		"label_config_requirements" : "követelmények",
		"label_config_requirements_content" : "- Telepítenie kell a következő plugint <a href='https: //obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS webkamera </a>. <br> - A <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> használatával kell létrehoznia a helyi gazdagép nyilvános URL-jét. . <br> - Az ngrok elérése után használja az alábbi <a href='https://dashboard.ngrok.com/get-started' target='_blank'> utasításokat az ngrok futtatásához a számítógépen </a> , és a következő parancs az URL létrehozásához:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "kredit",
		"label_config_usage" : "használat",
		"label_config_usage_content" : "- Ezzel a panellel mentheti meg a hitelesítő adatait. <br> - A <b> ráncolás </b> irányítópultján a bővítmények panelen megjelennek:<br>&nbsp; . egy gomb az OBS streaming elindításához / leállításához.<br>&nbsp; . egy gomb minden jelenethez.<br>&nbsp; . egy gomb az OBS-hez való kapcsolat bezárásához. <br> - <b> Amikor az adatfolyam elindul </b>, az irányítópulton / csatornádon <b> videó </b> átfedés lesz:<br>&nbsp; . egy gomb az OBS adatfolyam leállításához.<br>&nbsp; .  egy gomb minden jelenethez.<br>&nbsp; . egy gombot az OBS-hez való kapcsolat bezárásához.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Ha a <b class='red-text'> kiterjesztés nem tud csatlakozni </b> az OBS-hez, akkor a bejelentkezés megmutatja a hitelesítő adatok megváltoztatását</emp>.<br>",
		"label_config_feedback_text" : "visszacsatolás",
		"label_config_a_send" : "küld",
		"label_config_support_text" : "* Ha ez a kiterjesztés segít, akkor a támogatást nagyon jól fogadják ",
		"label_obs_error_credential" : "<p>Ellenőrizze hitelesítő adatait, és próbálja meg újra a <b class='red-text'> hibát</b></p>",
		"label_obs_connect"  : "kapcsolódni",
		"label_obs_close"  : "közelről",
		"label_obs_empty"  : "<p>Ne hagyjon üres <b class = 'red-text'> mezőt</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> csatlakoztatva</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Keresés </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Keres </b> ismét OBS</p>",
		"label_only_broadcast_view" : "<b>Sajnos <br> kibocsátó egyetlen nézete<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Ne hagyjon üres mezőket",
		"tooltip_feedback_ok" : "Köszönöm visszajelzését, a lehető leghamarabb megértem az észrevételeidet.",
		"tooltip_feedback_error" : "Sajnáljuk, de történt egy hiba, ezért visszajelzését nem sikerült elküldeni.",
		"tooltip_invalid_format" : "<p>Érvénytelen formátum <br> Kérjük, ellenőrizze az URL-jét</p>",
		"tooltip_config_save" : "<p>A <b class='green-text'> beállítások mentve</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>Az URL-nek a következő formátumúnak kell lennie: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> A legjobb és legegyszerűbb módja annak, hogy nyilvános URL-t szerezzen a következőhöz: localhost kell használni <a href='https://ngrok.com/' target='_blank'>ngrok.com</a></p>"
	},
	"nl":{
		"label_config_save_credentials" : "Gegevens opslaan",
		"label_config_requirements" : "vereisten",
		"label_config_requirements_content" : "- U moet de volgende plug-in <a href = 'https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' installeren > OBS websocket </a>. <br> - U moet <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> gebruiken om een openbare url van uw localhost te maken . <br> - Zodra u toegang hebt tot ngrok, gebruikt u de volgende <a href='https://dashboard.ngrok.com/get-started' target='_blank'> instructies om ngrok op uw computer uit te voeren </a> en de volgende opdracht om uw url te maken:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "credits",
		"label_config_usage" : "gebruik",
		"label_config_usage_content" : "- Gebruik dit paneel om uw inloggegevens op te slaan. <br> - In uw dashboard van <b> twitch </b> in het extensiespaneel verschijnen deze:<br>&nbsp; . een knop om het streamen van OBS te starten / stoppen.<br>&nbsp; . één knop voor elke scène.<br>&nbsp; . een knop om de verbinding met OBS te sluiten.<br>- <b>Wanneer de stream start </b>, staat er op je dashboard / kanaal <b> video </b> een overlay met :<br>&nbsp; . een knop om de OBS-stream te stoppen.<br>&nbsp; .  één knop voor elke scène.<br>&nbsp; . een knop om de verbinding met OBS te sluiten.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Als de extensie <b class='red-text'> geen verbinding kan maken </b> met OBS, wordt een login weergegeven om uw inloggegevens te wijzigen</emp>.<br>",
		"label_config_feedback_text" : "terugkoppeling",
		"label_config_a_send" : "sturen",
		"label_config_support_text" : "* Als deze extensie u helpt, wordt uw ondersteuning zeer goed ontvangen ",
		"label_obs_error_credential" : "<p>Controleer uw gegevens en probeer opnieuw <b class='red-text'> fout</b></p>",
		"label_obs_connect"  : "aansluiten",
		"label_obs_close"  : "van dichtbij",
		"label_obs_empty"  : "<p>Laat geen veld <b class='red-text'> leeg</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> verbonden</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Zoeken </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Op zoek naar </b> opnieuw OBS</p>",
		"label_only_broadcast_view" : "<b>Sorry voor de enkele weergave van de uitgever<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Laat geen leeg veld achter",
		"tooltip_feedback_ok" : "Bedankt voor uw feedback, ik begrijp uw opmerkingen zo snel mogelijk.",
		"tooltip_feedback_error" : "Sorry, maar er is een fout opgetreden en je feedback kon op dit moment niet worden verzonden.",
		"tooltip_invalid_format" : "<p>Ongeldig formaat <br> Controleer uw url</p>",
		"tooltip_config_save" : "<p>Instellingen <b class='green-text'> opgeslagen</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>De url moet de volgende indeling hebben: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> De beste en gemakkelijkste manier om een openbare url voor uw localhost gebruikt <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"no":{
		"label_config_save_credentials" : "Lagre data",
		"label_config_requirements" : "krav",
		"label_config_requirements_content" : "- Du må installere følgende plugin <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank'> OBS websocket </a>. <br> - Du må bruke <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> for å opprette en offentlig url for localhost. <br> - Når du har tilgang til ngrok, bruk følgende <a href='https://dashboard.ngrok.com/get-started' target='_blank'> instruksjoner for å kjøre ngrok på datamaskinen </ a >, og følgende kommando for å opprette url:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "studiepoeng",
		"label_config_usage" : "bruk",
		"label_config_usage_content" : "- Bruk dette panelet til å lagre legitimasjonsbeskrivelsen. <br> - I dashbordet til <b> rykke </b> i utvidelsespanelet vil de vises:<br>&nbsp; . en knapp for å starte / stoppe streaming av OBS.<br>&nbsp; . en knapp for hver scene.<br>&nbsp; . en knapp for å lukke forbindelsen til OBS.<br>- <b>Når strømmen starter </b>, vil det på oversikten / kanalen <b> videoen </b> være et overlegg med :<br>&nbsp; . en knapp for å stoppe OBS-strømmen.<br>&nbsp; .  en knapp for hver scene.<br>&nbsp; . en knapp for å lukke forbindelsen til OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Hvis utvidelsen <b class='red-text'> ikke kan koble til </b> til OBS, vil den vise innlogging for å endre legitimasjonsbeskrivelsen</emp>.<br>",
		"label_config_feedback_text" : "tilbakemeldinger",
		"label_config_a_send" : "sende",
		"label_config_support_text" : "* Hvis denne utvidelsen hjelper deg, blir støtten din veldig godt mottatt ",
		"label_obs_error_credential" : "<p>Kontroller legitimasjonsbeskrivelsen og prøv igjen <b class='red-text'>feil</b></p>",
		"label_obs_connect"  : "koble",
		"label_obs_close"  : "på nært hold",
		"label_obs_empty"  : "<p>Ikke la noe felt <b class='red-text'> være tomt</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> tilkoblet</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Søker </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Ser etter </b> igjen OBS</p>",
		"label_only_broadcast_view" : "<b>Beklager, enkeltvisning av Utsteder<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Ikke la noe tomt felt",
		"tooltip_feedback_ok" : "Takk for tilbakemeldingen, så snart som mulig vil jeg forstå kommentarene dine.",
		"tooltip_feedback_error" : "Beklager, men det var en feil, og tilbakemeldingene dine kunne ikke sendes på dette tidspunktet.",
		"tooltip_invalid_format" : "<p>Ugyldig format <br> Vennligst sjekk url-en din</p>",
		"tooltip_config_save" : "<p>Innstillinger <b class='green-text'> lagret</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>URLen må ha følgende format: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> Den beste og enkleste måten å få en offentlig url for localhost er å bruke <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"pl":{
		"label_config_save_credentials" : "Zapisz dane",
		"label_config_requirements" : "Wymagania",
		"label_config_requirements_content" : "- Musisz zainstalować następującą wtyczkę <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS websocket </a>. <br> - Musisz użyć <a href='https://ngrok.com/' target='_blank'> ngrok.com </a>, aby utworzyć publiczny adres URL lokalnego hosta . <br> - Po uzyskaniu dostępu do ngrok skorzystaj z następujących <a href='https://dashboard.ngrok.com/get-started' target='_blank'> instrukcji, aby uruchomić ngrok na komputerze </a> oraz następujące polecenie, aby utworzyć adres URL:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "Kredyty",
		"label_config_usage" : "Użyj",
		"label_config_usage_content" : "- Użyj tego panelu, aby zapisać swoje dane uwierzytelniające. <br> - Pojawią się na pulpicie <b> twitch </b> w panelu rozszerzeń.:<br>&nbsp; . przycisk, aby rozpocząć / zatrzymać przesyłanie strumieniowe OBS.<br>&nbsp; . jeden przycisk dla każdej sceny.<br>&nbsp; . un boton para cerrar la coneccion a OBS.<br>- <b>Po rozpoczęciu transmisji </b> na pulpicie nawigacyjnym / kanale <b> wideo </b> pojawi się nakładka z :<br>&nbsp; . przycisk, aby zatrzymać strumień OBS.<br>&nbsp; .  un boton por cada escena.<br>&nbsp; . un boton para cerrar la coneccion a OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Jeśli rozszerzenie <b class='red-text'> nie może połączyć się </b> z OBS, wyświetli się login, aby zmienić twoje dane uwierzytelniające</emp>.<br>",
		"label_config_feedback_text" : "Informacje zwrotne",
		"label_config_a_send" : "Wyślij",
		"label_config_support_text" : "* Jeśli to rozszerzenie Ci pomoże, Twoje wsparcie jest bardzo dobrze odbierane ",
		"label_obs_error_credential" : "<p>Sprawdź swoje dane logowania i spróbuj ponownie błąd <b class='red-text'></b></p>",
		"label_obs_connect"  : "połączyć",
		"label_obs_close"  : "z bliska",
		"label_obs_empty"  : "<p>Nie pozostawiaj żadnego pola <b class='red-text'> puste</b>!</p>",
		"label_obs_connected" : "<p><b class='green-text'>Podłączono</b> OBS </p>",
		"label_obs_check" : "<p><b class='orange-text'>Wyszukiwanie </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Poszukuję </b> ponownie OBS</p>",
		"label_only_broadcast_view" : "<b>Przepraszamy <br> pojedynczy widok Emitenta<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Nie pozostawiaj pustego pola",
		"tooltip_feedback_ok" : "Dziękujemy za opinie, jak najszybciej zrozumiem wasze komentarze.",
		"tooltip_feedback_error" : "Przepraszamy, ale wystąpił błąd i w tej chwili nie można wysłać Twojej opinii.",
		"tooltip_invalid_format" : "<p>Nieprawidłowy format <br> Sprawdź swój adres URL</p>",
		"tooltip_config_save" : "<p>Ustawienia <b class='green-text'> zapisane</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>Adres URL musi mieć następujący format: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> Najlepszy i najprostszy sposób na uzyskanie publicznego adresu URL dla Twojego localhost ma używać <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"pt":{
		"label_config_save_credentials" : "Salvar dados",
		"label_config_requirements" : "Exigências",
		"label_config_requirements_content" : "- Você precisa instalar o seguinte plugin <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS websocket </a>. <br> - Você deve usar <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> para criar um URL público do seu host local . <br> - Depois de acessar o ngrok, use as seguintes instruções <a href='https://dashboard.ngrok.com/get-started' target='_blank'> para executar o ngrok no seu computador </a> e o comando a seguir para criar seu URL:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "Créditos",
		"label_config_usage" : "Use",
		"label_config_usage_content" : "- Use este painel para salvar suas credenciais. <br> - No painel de <b> contração muscular </b>, no painel de extensões, elas aparecerão:<br>&nbsp; . um botão para iniciar / parar a transmissão de OBS.<br>&nbsp; . um botão para cada cena.<br>&nbsp; . um botão para fechar a conexão com o OBS.<br>- <b>Quando o fluxo começa</b>, no seu painel / canal <b> vídeo </b>, haverá uma sobreposição com :<br>&nbsp; . um botão para interromper o fluxo OBS.<br>&nbsp; .  um botão para cada cena.<br>&nbsp; . um botão para fechar a conexão com o OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Se a extensão <b class='red-text'> não puder se conectar </b> ao OBS, ela mostrará um login para alterar suas credenciais</emp>.<br>",
		"label_config_feedback_text" : "Comentários",
		"label_config_a_send" : "Enviar",
		"label_config_support_text" : "* Se esta extensão o ajudar, seu suporte será muito bem recebido",
		"label_obs_error_credential" : "<p>Verifique suas credenciais e tente novamente <b class='red-text'> error</b></p>",
		"label_obs_connect"  : "ligar",
		"label_obs_close"  : "Fechar",
		"label_obs_empty"  : "<p>Não deixe nenhum campo <b class='red-text'> vazio</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> conectado</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Pesquisando </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Procurando </b> novamente OBS</p>",
		"label_only_broadcast_view" : "<b>Desculpe, uma visão única do emissor<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Não deixe nenhum campo vazio",
		"tooltip_feedback_ok" : "Obrigado pelo seu feedback. Assim que possível, entenderei seus comentários.",
		"tooltip_feedback_error" : "Desculpe, mas ocorreu um erro e seu feedback não pôde ser enviado no momento.",
		"tooltip_invalid_format" : "<p>Formato inválido <br> Verifique seu URL</p>",
		"tooltip_config_save" : "<p>Configurações <b class='green-text'> salvas</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>O URL deve ter o seguinte formato: <br> <br> <b> wss: // </b> a93a7c2255.ngrok.io <br> <br> A maneira melhor e mais fácil de obter um URL público para o seu localhost é usar <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"pt-br":{
		"label_config_save_credentials" : "Salvar dados",
		"label_config_requirements" : "Exigências",
		"label_config_requirements_content" : "- Você precisa instalar o seguinte plugin <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS websocket </a>. <br> - Você deve usar <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> para criar um URL público do seu host local . <br> - Depois de acessar o ngrok, use as seguintes instruções <a href='https://dashboard.ngrok.com/get-started' target='_blank'> para executar o ngrok no seu computador </a> e o comando a seguir para criar seu URL:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "Créditos",
		"label_config_usage" : "Use",
		"label_config_usage_content" : "- Use este painel para salvar suas credenciais. <br> - No painel de <b> contração muscular </b>, no painel de extensões, elas aparecerão:<br>&nbsp; . um botão para iniciar / parar a transmissão de OBS.<br>&nbsp; . um botão para cada cena.<br>&nbsp; . um botão para fechar a conexão com o OBS.<br>- <b>Quando o fluxo começa</b>, no seu painel / canal <b> vídeo </b>, haverá uma sobreposição com :<br>&nbsp; . um botão para interromper o fluxo OBS.<br>&nbsp; .  um botão para cada cena.<br>&nbsp; . um botão para fechar a conexão com o OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Se a extensão <b class='red-text'> não puder se conectar </b> ao OBS, ela mostrará um login para alterar suas credenciais</emp>.<br>",
		"label_config_feedback_text" : "Comentários",
		"label_config_a_send" : "Enviar",
		"label_config_support_text" : "* Se esta extensão o ajudar, seu suporte será muito bem recebido",
		"label_obs_error_credential" : "<p>Verifique suas credenciais e tente novamente <b class='red-text'> error</b></p>",
		"label_obs_connect"  : "ligar",
		"label_obs_close"  : "Fechar",
		"label_obs_empty"  : "<p>Não deixe nenhum campo <b class='red-text'> vazio</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> conectado</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Pesquisando </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Procurando </b> novamente OBS</p>",
		"label_only_broadcast_view" : "<b>Desculpe, uma visão única do emissor<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Não deixe nenhum campo vazio",
		"tooltip_feedback_ok" : "Obrigado pelo seu feedback. Assim que possível, entenderei seus comentários.",
		"tooltip_feedback_error" : "Desculpe, mas ocorreu um erro e seu feedback não pôde ser enviado no momento.",
		"tooltip_invalid_format" : "<p>Formato inválido <br> Verifique seu URL</p>",
		"tooltip_config_save" : "<p>Configurações <b class='green-text'> salvas</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>O URL deve ter o seguinte formato: <br> <br> <b> wss: // </b> a93a7c2255.ngrok.io <br> <br> A maneira melhor e mais fácil de obter um URL público para o seu localhost é usar <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"ro":{
		"label_config_save_credentials" : "Salvați datele",
		"label_config_requirements" : "cerinţe",
		"label_config_requirements_content" : "- Trebuie să instalați următorul plugin <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS websocket </a>. <br> - Trebuie să utilizați <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> pentru a crea o adresă publică a localhost-ului dvs. . <br> - După ce accesați ngrok, utilizați următoarele <a href='https://dashboard.ngrok.com/get-started' target='_blank'> instrucțiuni pentru a rula ngrok pe computer </a> și următoarea comandă pentru a crea adresa URL:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "credite",
		"label_config_usage" : "utilizare",
		"label_config_usage_content" : "- Folosiți acest panou pentru a vă salva datele de acreditare. <br> - În tabloul de bord al <b> twitch </b> din panoul de extensii vor apărea:<br>&nbsp; . un buton pentru a porni / opri streaming OBS.<br>&nbsp; . un buton pentru fiecare scenă.<br>&nbsp; . un buton pentru a închide conexiunea la OBS. <br> - <b> Când începe fluxul </b>, pe tabloul de bord / canalul <b> video </b> va exista o suprapunere cu :<br>&nbsp; . un buton pentru a opri fluxul OBS.<br>&nbsp; .  un buton pentru fiecare scenă.<br>&nbsp; . un buton pentru a închide conexiunea la OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Dacă extensia <b class='red-text'> nu se poate conecta </b> la OBS, va afișa o autentificare pentru a vă schimba datele de acreditare</emp>.<br>",
		"label_config_feedback_text" : "feedback-ul",
		"label_config_a_send" : "trimite",
		"label_config_support_text" : "* Dacă această extensie vă ajută, suportul dvs. este foarte bine primit ",
		"label_obs_error_credential" : "<p>Verificați-vă datele de acreditare și încercați din nou eroarea <b class='red-text'></b></p>",
		"label_obs_connect"  : "lega",
		"label_obs_close"  : "aproape",
		"label_obs_empty"  : "<p>Nu lăsați niciun câmp <b class='red-text'> gol</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> conectat</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Căutare </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Caută din nou OBS</p>",
		"label_only_broadcast_view" : "<b>Ne pare rău, dar este o singură vedere a emitentului<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Nu lăsați niciun câmp gol",
		"tooltip_feedback_ok" : "Vă mulțumesc pentru feedback, cât de curând posibil vă voi înțelege comentariile.",
		"tooltip_feedback_error" : "Ne pare rău, dar a existat o eroare și feedback-ul dvs. nu a putut fi trimis în acest moment.",
		"tooltip_invalid_format" : "<p>Format nevalid | Vă rugăm să verificați adresa URL</p>",
		"tooltip_config_save" : "<p>Setările <b class='green-text'> salvate</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>Url trebuie să aibă următorul format: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> Cel mai bun și mai simplu mod de a obține o adresă publică de url pentru dvs. localhost trebuie să folosească <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"sk":{
		"label_config_save_credentials" : "Uložte údaje",
		"label_config_requirements" : "požiadavky",
		"label_config_requirements_content" : "- Musíte nainštalovať nasledujúci doplnok <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS websocket </a>. <br> - Na vytvorenie verejnej adresy URL vášho localhost musíte použiť <a href='https://ngrok.com/' target='_blank'> ngrok.com </a>. . <br> - Po spustení programu ngrok postupujte podľa nasledujúcich <a href='https://dashboard.ngrok.com/get-started' target='_blank'> pokynov na spustenie programu ngrok na počítači </a>. a nasledujúci príkaz na vytvorenie adresy URL:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "kreditov",
		"label_config_usage" : "použitie",
		"label_config_usage_content" : "- Pomocou tohto panela môžete uložiť svoje poverenia. <br> - Na paneli rozšírení <b> škubnutí </b> na paneli rozšírení sa zobrazia.:<br>&nbsp; . tlačidlo na spustenie / zastavenie streamovania OBS.<br>&nbsp; . jedno tlačidlo pre každú scénu.<br>&nbsp; . tlačidlo na ukončenie spojenia s OBS. <br> - <b> Keď sa stream spustí </b>, na vašom prístrojovom paneli / kanáli <b> video </b> sa zobrazí prekrytie s :<br>&nbsp; . tlačidlo na zastavenie toku OBS.<br>&nbsp; .  jedno tlačidlo pre každú scénu.<br>&nbsp; . tlačidlo na ukončenie spojenia s OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Ak sa rozšírenie <b class='red-text'> nemôže pripojiť </b> k OBS, zobrazí sa prihlasovacie údaje na zmenu vašich prihlasovacích údajov</emp>.<br>",
		"label_config_feedback_text" : "spätná väzba",
		"label_config_a_send" : "odoslať",
		"label_config_support_text" : "* Ak vám toto rozšírenie pomôže, vaša podpora je veľmi dobre prijatá ",
		"label_obs_error_credential" : "<p>Skontrolujte svoje poverenia a skúste znova <b class='red-text'> error</b></p>",
		"label_obs_connect"  : "pripojiť",
		"label_obs_close"  : "zblízka",
		"label_obs_empty"  : "<p>Nenechávajte žiadne pole <b class='red-text'> prázdne</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> connection</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Vyhľadávanie </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Hľadám znova </b> OBS</p>",
		"label_only_broadcast_view" : "<b>Ospravedlňujeme sa <br> jediné zobrazenie Emitenta<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Nenechávajte žiadne prázdne pole",
		"tooltip_feedback_ok" : "Ďakujeme za vaše hodnotenie, hneď ako to bude možné, pochopím vaše pripomienky.",
		"tooltip_feedback_error" : "Ľutujeme, ale vyskytla sa chyba a váš názor sa momentálne nedal odoslať.",
		"tooltip_invalid_format" : "<p>Neplatný formát <br> Skontrolujte svoju webovú adresu</p>",
		"tooltip_config_save" : "<p>Nastavenia <b class='green-text'> boli uložené</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>Adresa URL musí mať nasledujúci formát: <br> <br> <b> wss: // </b> a93a7c2255.ngrok.io <br> <br> Najlepší a najjednoduchší spôsob získania verejnej adresy URL pre vašu adresu localhost má používať <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"fi":{
		"label_config_save_credentials" : "Tallenna tiedot",
		"label_config_requirements" : "vaatimuksista",
		"label_config_requirements_content" : "- Sinun on asennettava seuraava plugin <a href = 'https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS-verkkojousi </a>. <br> - Sinun on käytettävä <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> -sovellusta, jotta voit luoda paikallisen palvelimesi julkisen URL-osoitteen. . <br> - Kun olet käyttänyt ngrokia, käytä seuraavia <a href='https://dashboard.ngrok.com/get-started' target='_blank'> ohjeita ajamaan ngrok tietokoneellasi </a> , ja seuraava komento URL-osoitteen luomiseksi:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "ov",
		"label_config_usage" : "käyttö",
		"label_config_usage_content" : "- Tallenna käyttäjätiedot tällä paneelilla. <br> - Laajennuspaneelin <b> kutistus </b> -kortissa ne näkyvät.:<br>&nbsp; . painike käynnistää / lopettaa OBS: n suoratoiston.<br>&nbsp; . yksi painike jokaiselle kohtaukselle.<br>&nbsp; . -painike yhteyden sulkemiseen OBS: ään. <br> - <b> Kun suoratoisto alkaa </b>, kojetaulussa / kanavalla <b> videossa </b> on overlay with :<br>&nbsp; . painike OBS-streamin lopettamiseksi.<br>&nbsp; .  yksi painike jokaiselle kohtaukselle.<br>&nbsp; . painike sulkeaksesi yhteyden OBS: ään.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Jos laajennus <b class='red-text'> ei voi muodostaa yhteyttä </b> OBS: iin, se näyttää kirjautumistunnuksen, jolla voit muuttaa käyttöoikeustietojasi</emp>.<br>",
		"label_config_feedback_text" : "palaute",
		"label_config_a_send" : "lähettää",
		"label_config_support_text" : "* Jos tämä laajennus auttaa sinua, tuesi on otettu erittäin hyvin vastaan ",
		"label_obs_error_credential" : "<p>Tarkista käyttäjätiedot ja yritä uudelleen <b class='red-text'> -virhe</b></p>",
		"label_obs_connect"  : "kytkeä",
		"label_obs_close"  : "lähikuva",
		"label_obs_empty"  : "<p>Älä jätä kenttää <b class='red-text'> tyhjäksi</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> kytketty</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Haku </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Etsitään </b> uudelleen OBS</p>",
		"label_only_broadcast_view" : "<b>Valitettavasti yksi näkymä liikkeeseenlaskijaan<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Älä jätä tyhjää kenttää",
		"tooltip_feedback_ok" : "Kiitos palautteestasi, ymmärrän kommenttisi niin pian kuin mahdollista.",
		"tooltip_feedback_error" : "Anteeksi, mutta tapahtui virhe ja palautetta ei voitu lähettää tällä hetkellä.",
		"tooltip_invalid_format" : "<p>Virheellinen muoto <br> Tarkista URL</p>",
		"tooltip_config_save" : "<p>Asetukset <b class='green-text'> tallennettu</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>URL-osoitteella on oltava seuraava muoto: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> Paras ja helpoin tapa saada julkinen URL-osoite localhost on käyttää <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"sv":{
		"label_config_save_credentials" : "Spara data",
		"label_config_requirements" : "krav",
		"label_config_requirements_content" : "- Du måste installera följande plugin <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS websocket </a>. <br> - Du måste använda <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> för att skapa en offentlig url för din localhost . <br> - När du öppnar ngrok använder du följande <a href='https://dashboard.ngrok.com/get-started' target='_blank'> instruktioner för att köra ngrok på din dator </a> , och följande kommando för att skapa din url:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "hp",
		"label_config_usage" : "användning",
		"label_config_usage_content" : "- Använd den här panelen för att spara dina referenser. <br> - I din instrumentpanel för <b> rycka </b> i tilläggspanelen kommer de att visas:<br>&nbsp; . en knapp för att starta / sluta strömma OBS.<br>&nbsp; . en knapp för varje scen.<br>&nbsp; . en knapp för att stänga anslutningen till OBS. <br> - <b> När strömmen startar </b>, på din instrumentbräda / kanal <b> video </b> kommer det att finnas en överlägg med :<br>&nbsp; . en knapp för att stoppa OBS-strömmen.<br>&nbsp; .  en knapp för varje scen.<br>&nbsp; . en knapp för att stänga anslutningen till OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Om tillägget <b class='red-text'> inte kan ansluta </b> till OBS, kommer det att visa en inloggning för att ändra dina referenser</emp>.<br>",
		"label_config_feedback_text" : "Återkoppling",
		"label_config_a_send" : "skicka",
		"label_config_support_text" : "* Om det här tillägget hjälper dig mottas ditt stöd mycket väl ",
		"label_obs_error_credential" : "<p>Kontrollera dina referenser och försök igen <b class='red-text'> -fel</b></p>",
		"label_obs_connect"  : "ansluta",
		"label_obs_close"  : "närbild",
		"label_obs_empty"  : "<p>Lämna inga fält <b class='red-text'> tomma</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> ansluten</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Söker </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>	Letar efter </b> igen OBS</p>",
		"label_only_broadcast_view" : "<b>Ledsen över en enda vy av Emittenten<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Lämna inga tomma fält",
		"tooltip_feedback_ok" : "Tack för din feedback, så snart som möjligt förstår jag dina kommentarer.",
		"tooltip_feedback_error" : "Tyvärr uppstod ett fel och din feedback kunde inte skickas just nu.",
		"tooltip_invalid_format" : "<p>Ogiltigt format - Kontrollera din url</p>",
		"tooltip_config_save" : "<p>Inställningar <b class='green-text'> sparade</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>URL-adressen måste ha följande format: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> Det bästa och enklaste sättet att få en offentlig url till din localhost är att använda <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"vi":{
		"label_config_save_credentials" : "Lưu dữ liệu",
		"label_config_requirements" : "Yêu cầu",
		"label_config_requirements_content" : "- Bạn cần cài đặt plugin sau <a href = 'https://obsproject.com/forum/resource/obs-websocket-remote-control-of-obs-studio-ADE-easy.466/' target='_blank' > Websocket OBS </a>. <br> - Bạn phải sử dụng <a href='https://ngrok.com/' target='etric'> ngrok.com </a> để tạo url công khai của localhost của bạn . <br> - Khi bạn truy cập ngrok, hãy sử dụng các hướng dẫn <a href='https://dashboard.ngrok.com/get-started' target='etric'> sau đây để chạy ngrok trên máy tính của bạn </a> và lệnh sau để tạo url của bạn:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "Tín dụng",
		"label_config_usage" : "Sử dụng",
		"label_config_usage_content" : "- Sử dụng bảng điều khiển này để lưu thông tin đăng nhập của bạn. <br> - Trong bảng điều khiển <b> twitch </ b> của bạn trong bảng tiện ích mở rộng, chúng sẽ xuất hiện:<br>&nbsp; . một nút để bắt đầu / dừng phát trực tuyến OBS.<br>&nbsp; . một nút cho mỗi cảnh.<br>&nbsp; . một nút để đóng kết nối với OBS.<br>- <b>Khi luồng bắt đầu </ b>, trên bảng điều khiển / kênh <b> video </ b> của bạn sẽ có lớp phủ với :<br>&nbsp; . một nút để dừng luồng OBS.<br>&nbsp; .  một nút cho mỗi cảnh.<br>&nbsp; . một nút để đóng kết nối với OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Nếu tiện ích mở rộng <b class='red-text'> không thể kết nối </ b> với OBS, nó sẽ hiển thị thông tin đăng nhập để thay đổi thông tin đăng nhập của bạn</emp>.<br>",
		"label_config_feedback_text" : "Phản hồi",
		"label_config_a_send" : "Gửi",
		"label_config_support_text" : "* Nếu tiện ích mở rộng này giúp bạn, sự hỗ trợ của bạn rất được đón nhận ",
		"label_obs_error_credential" : "<p>Kiểm tra thông tin đăng nhập của bạn và thử lại <b class='red-text'></b></p>",
		"label_obs_connect"  : "kết nối",
		"label_obs_close"  : "đóng lên",
		"label_obs_empty"  : "<p>Không để trống bất kỳ trường nào <b class='red-text'></b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> được kết nối</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Tìm kiếm </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Tìm kiếm </b> một lần nữa OBS</p>",
		"label_only_broadcast_view" : "<b>Xin lỗi <br> quan điểm duy nhất của tổ chức phát hành<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Đừng để bất kỳ trường trống",
		"tooltip_feedback_ok" : "Cảm ơn phản hồi của bạn, càng sớm càng tốt, tôi sẽ hiểu ý kiến của bạn.",
		"tooltip_feedback_error" : "Xin lỗi, nhưng đã xảy ra lỗi và không thể gửi phản hồi của bạn tại thời điểm này.",
		"tooltip_invalid_format" : "<p>Định dạng không hợp lệ <br> Vui lòng kiểm tra url của bạn</p>",
		"tooltip_config_save" : "<p>Cài đặt <b class='green-text'> đã lưu</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>Url phải có định dạng sau: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> Cách tốt nhất và dễ nhất để lấy url công khai cho bạn localhost là sử dụng <a href='https://ngrok.com/' target='etric'> ngrok.com </a></p>"
	},
	"tr":{
		"label_config_save_credentials" : "Veri kaydet",
		"label_config_requirements" : "Gereksinim",
		"label_config_requirements_content" : "- Aşağıdaki eklentiyi kurmanız gerekiyor <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS websocket </a>. <br> - Yerel ana makinenizin genel bir URL'sini oluşturmak için <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> adresini kullanmanız gerekir. .net - ngrok'a eriştikten sonra, aşağıdaki <a href='https://dashboard.ngrok.com/get-started' target='_blank'> bilgisayarınızda ngrok çalıştırma talimatlarını </a> kullanın , url’nizi oluşturmak için aşağıdaki komutu kullanın.:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "kredi",
		"label_config_usage" : "kullanım",
		"label_config_usage_content" : "- Kimlik bilgilerinizi kaydetmek için bu paneli kullanın. <br> - Eklentiler panelinde <b> seğirme </b> gösterge tablonuzda görünecekler:<br>&nbsp; . OBS’den akışı başlatmak / durdurmak için bir düğme.<br>&nbsp; . her sahne için bir düğme.<br>&nbsp; . OBS ile olan bağlantıyı kapatmak için bir düğme. <br> - <b> Akış başladığında </b>, gösterge tablonuzda / kanalınızda <b> video </b> ile bir kaplama olacak :<br>&nbsp; . OBS akışını durdurmak için bir düğme.<br>&nbsp; .  her sahne için bir düğme.<br>&nbsp; .OBS ile olan bağlantıyı kapatmak için bir düğme.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* <B class = 'red-text'> uzantısı OBS'ye bağlanamıyorsa </b>, kimlik bilgilerinizi değiştirmek için bir giriş gösterecektir</emp>.<br>",
		"label_config_feedback_text" : "geri bildirim",
		"label_config_a_send" : "göndermek",
		"label_config_support_text" : "* Bu uzantı size yardımcı olursa, desteğiniz çok iyi karşılanır",
		"label_obs_error_credential" : "<p>Kimlik bilgilerinizi kontrol edin ve tekrar deneyin <b class='red-text'> hatası</b></p>",
		"label_obs_connect"  : "bağlamak",
		"label_obs_close"  : "yakın",
		"label_obs_empty"  : "<p>Hiçbir alanı <b class='red-text'> boş bırakmayın</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> bağlı</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Arama </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>tekrar arıyorsunuz</b> OBS</p>",
		"label_only_broadcast_view" : "<b>Üzgünüz, İhraççı'nın tekli görünümü<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Boş alan bırakmayın",
		"tooltip_feedback_ok" : "Geri bildiriminiz için teşekkür ederiz, yorumlarınızı en kısa sürede cevaplayacağım.",
		"tooltip_feedback_error" : "Maalesef bir hata oluştu ve geri bildiriminiz şu anda gönderilemedi.",
		"tooltip_invalid_format" : "<p>Geçersiz biçim <br> Lütfen URL'nizi kontrol edin</p>",
		"tooltip_config_save" : "<p><b class='green-text'> ayarları kaydedildi</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>URL’nin aşağıdaki biçimde olması gerekir: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> Telefonunuz için genel bir URL almanın en iyi ve en kolay yolu localhost, <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> adresini kullanmaktır</p>"
	},
	"cs":{
		"label_config_save_credentials" : "Uložte data",
		"label_config_requirements" : "Požadavky",
		"label_config_requirements_content" : "- Musíte nainstalovat následující plugin <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS websocket </a>. <br> - Musíte vytvořit <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> a vytvořit veřejnou URL vašeho localhostu. . <br> - Jakmile získáte přístup k ngrok, použijte následující <a href='https://dashboard.ngrok.com/get-started' target='_blank'> pokyny ke spuštění ngrok ve vašem počítači </a> a následující příkaz k vytvoření adresy URL:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "Úvěry",
		"label_config_usage" : "Použití",
		"label_config_usage_content" : "- Pomocí tohoto panelu můžete uložit svá přihlašovací údaje. <br> - Na hlavním panelu <b> škubnutí </b> na panelu rozšíření se zobrazí.:<br>&nbsp; . tlačítko pro spuštění / zastavení streamování z OBS.<br>&nbsp; . jedno tlačítko pro každou scénu.<br>&nbsp; . tlačítko pro ukončení připojení k OBS. <br> - <b> Když se stream spustí </b>, na palubní desce / kanálu <b> video </b> bude překryv s :<br>&nbsp; . tlačítko pro zastavení toku OBS.<br>&nbsp; .  jedno tlačítko pro každou scénu.<br>&nbsp; . tlačítko pro ukončení připojení k OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Pokud se přípona <b class='red-text'> nemůže připojit </b> k OBS, zobrazí se přihlašovací jméno ke změně vašich údajů.</emp>.<br>",
		"label_config_feedback_text" : "Zpětná vazba",
		"label_config_a_send" : "Odeslat",
		"label_config_support_text" : "* Pokud vám toto rozšíření pomůže, vaše podpora je velmi dobře přijata ",
		"label_obs_error_credential" : "<p>Zkontrolujte svá přihlašovací údaje a zkuste chybu <b class='red-text'> znovu</b></p>",
		"label_obs_connect"  : "připojit",
		"label_obs_close"  : "zblízka",
		"label_obs_empty"  : "<p>Nenechávejte prázdné pole <b class='red-text'></b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> připojen</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Hledání </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Hledám znovu </b></p>",
		"label_only_broadcast_view" : "<b>Omlouváme se za jediný pohled na Emitenta<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Nenechávejte žádná prázdná pole",
		"tooltip_feedback_ok" : "Děkujeme za vaši zpětnou vazbu, odpovím na vaše připomínky co nejdříve.",
		"tooltip_feedback_error" : "Litujeme, ale došlo k chybě a vaše zpětná vazba se v tuto chvíli nemohla odeslat.",
		"tooltip_invalid_format" : "<p>Neplatný formát <br> Zkontrolujte prosím svou URL</p>",
		"tooltip_config_save" : "<p>Nastavení <b class='green-text'> savea</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>Adresa URL musí mít následující formát: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> Nejlepší a nejjednodušší způsob, jak získat veřejnou adresu URL pro vaši localhost má používat <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"el":{
		"label_config_save_credentials" : "Αποθήκευση δεδομένων",
		"label_config_requirements" : "Απαιτήσεις",
		"label_config_requirements_content" : "- Θα χρειαστεί να εγκαταστήσετε την ακόλουθη προσθήκη <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS websocket </a> <br> <br> - Πρέπει να χρησιμοποιήσετε το <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> για να δημιουργήσετε μια δημόσια διεύθυνση url του localhost σας . - Μόλις αποκτήσετε πρόσβαση στο ngrok, χρησιμοποιήστε τις παρακάτω <a href='https://dashboard.ngrok.com/get-started' target='_blank'> οδηγίες για να εκτελέσετε ngrok στον υπολογιστή σας </a> , και την ακόλουθη εντολή για τη δημιουργία της διεύθυνσης URL σας:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "Πιστώσεις",
		"label_config_usage" : "Χρήση",
		"label_config_usage_content" : "- Χρησιμοποιήστε αυτόν τον πίνακα για να αποθηκεύσετε τα διαπιστευτήριά σας <br> <br> - στον πίνακα ελέγχου <b> σπάσιμο </ b> στον πίνακα επεκτάσεων θα εμφανιστούν:<br>&nbsp; . ένα κουμπί για την εκκίνηση / διακοπή ροής από το OBS.<br>&nbsp; . ένα κουμπί για κάθε σκηνή.<br>&nbsp; . ένα κουμπί για κάθε σκηνή... :<br>&nbsp; . ένα κουμπί για να σταματήσει το ρεύμα OBS.<br>&nbsp; .  ένα κουμπί για κάθε σκηνή.<br>&nbsp; . ένα κουμπί για να κλείσετε τη σύνδεση με την OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Εάν η επέκταση <b class='red-text'> δεν μπορεί να συνδεθεί </ b> στην OBS, θα εμφανιστεί μια σύνδεση για να αλλάξετε τα διαπιστευτήριά σας</emp>.<br>",
		"label_config_feedback_text" : "Ανατροφοδότηση",
		"label_config_a_send" : "Αποστολή",
		"label_config_support_text" : "* Εάν αυτή η επέκταση σας βοηθήσει, η υποστήριξή σας είναι πολύ καλή ",
		"label_obs_error_credential" : "<p>Ελέγξτε τα διαπιστευτήριά σας και προσπαθήστε ξανά <b class='red-text'> σφάλμα</b></p>",
		"label_obs_connect"  : "συνδεθείτε",
		"label_obs_close"  : "κλείνω",
		"label_obs_empty"  : "<p>Μην αφήνετε κανένα πεδίο <b class='red-text'> κενό</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'>συνδεδεμένο</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Αναζήτηση </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Ψάχνετε για </b> ξανά OBS</p>",
		"label_only_broadcast_view" : "<b>Συγνώμη <br> ενιαία άποψη του εκδότη<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Μην αφήνετε κενά πεδία",
		"tooltip_feedback_ok" : "Σας ευχαριστώ για τα σχόλιά σας, θα απαντήσω στα σχόλιά σας το συντομότερο δυνατό.",
		"tooltip_feedback_error" : "Λυπούμαστε, αλλά παρουσιάστηκε ένα σφάλμα και τα σχόλιά σας δεν ήταν δυνατή αυτή τη στιγμή.",
		"tooltip_invalid_format" : "<p>Μη έγκυρη μορφή <br> Ελέγξτε τη διεύθυνση URL σας</p>",
		"tooltip_config_save" : "<p>Οι ρυθμίσεις <b class='green-text'> αποθηκεύτηκαν</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>Η διεύθυνση URL πρέπει να έχει την ακόλουθη μορφή: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> Ο καλύτερος και ευκολότερος τρόπος για να πάρετε μια δημόσια διεύθυνση για το localhost πρόκειται να χρησιμοποιήσει <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"bg":{
		"label_config_save_credentials" : "Запазване на данни",
		"label_config_requirements" : "изисквания",
		"label_config_requirements_content" : "- Трябва да инсталирате следния плъгин <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS websocket </a>. <br> - Трябва да използвате <a href='https://ngrok.com/' target='_blank'> ngrok.com </a>, за да създадете публичен URL адрес на своя localhost . <br> - След като получите достъп до ngrok, използвайте следните <a href='https://dashboard.ngrok.com/get-started' target='_blank'> инструкции, за да стартирате ngrok на вашия компютър </a> и следната команда за създаване на вашия URL адрес:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "кредити",
		"label_config_usage" : "употреба",
		"label_config_usage_content" : "- Използвайте този панел, за да запазите идентификационните си данни. <br> - В таблото ви на <b> потрепване </b> в панела с разширения те ще се покажат:<br>&nbsp; . бутон за стартиране / спиране на поточно предаване от OBS.<br>&nbsp; . по един бутон за всяка сцена.<br>&nbsp; . бутон за затваряне на връзката с OBS. <br> - <b> Когато потокът започне </b>, на таблото за управление / канал <b> видео </b> ще има наслагване с :<br>&nbsp; . бутон за спиране на потока OBS.<br>&nbsp; .  по един бутон за всяка сцена.<br>&nbsp; . бутон за затваряне на връзката с OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Ако разширението <b class='red-text'> не може да се свърже </b> с OBS, то ще покаже вход за промяна на вашите идентификационни данни</emp>.<br>",
		"label_config_feedback_text" : "Обратна връзка",
		"label_config_a_send" : "изпращам",
		"label_config_support_text" : "* Ако това разширение ви помогне, вашата подкрепа е много добре приета ",
		"label_obs_error_credential" : "<p>Проверете вашите идентификационни данни и опитайте отново <b class='red-text'> грешка</b></p>",
		"label_obs_connect"  : "свържете",
		"label_obs_close"  : "наблизо",
		"label_obs_empty"  : "<p>Не оставяйте поле <b class='red-text'> празно</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> свързан</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Търсене </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Търси </b> отново OBS</p>",
		"label_only_broadcast_view" : "<b>За съжаление - единствен изглед на Емитента<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Не оставяйте празни полета",
		"tooltip_feedback_ok" : "Благодаря ви за отзивите, ще отговоря на вашите коментари възможно най-скоро.",
		"tooltip_feedback_error" : "За съжаление възникна грешка и понастоящем не можете да изпратите отзивите ви.",
		"tooltip_invalid_format" : "<p>Невалиден формат <br> Моля, проверете вашия URL адрес</p>",
		"tooltip_config_save" : "<p>Настройките <b class='green-text'> са запазени</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>URL адресът трябва да има следния формат: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io - <br> Най-добрият и лесен начин за получаване на публичен URL адрес за вашия localhost е да използвате <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"ru":{
		"label_config_save_credentials" : "Сохранить данные",
		"label_config_requirements" : "	требования",
		"label_config_requirements_content" : "- Вам необходимо установить следующий плагин <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > Веб-сокет OBS </a>. <br> - Вы должны использовать <a href='https://ngrok.com/' target='_blank'> ngrok.com </a>, чтобы создать общедоступный URL-адрес своего локального хоста. . <br> - Получив доступ к ngrok, используйте следующие <a href='https://dashboard.ngrok.com/get-started' target='_blank'> инструкции по запуску ngrok на своем компьютере </a> и следующую команду для создания вашего URL:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "кредиты",
		"label_config_usage" : "использование",
		"label_config_usage_content" : "-Используйте эту панель для сохранения своих учетных данных. <br> - На панели инструментов <b> twitch </b> на панели расширений они появятся.:<br>&nbsp; . кнопка для запуска / остановки потоковой передачи из OBS.<br>&nbsp; . одна кнопка для каждой сцены.<br>&nbsp; . кнопка, чтобы закрыть соединение с OBS. <br> - <b> Когда начнется поток </b>, на панели инструментов / канале <b> video </b> будет наложение с :<br>&nbsp; . кнопка для остановки потока OBS.<br>&nbsp; .  одна кнопка для каждой сцены.<br>&nbsp; . кнопка, чтобы закрыть соединение с OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* Если расширение <b class='red-text'> не может подключиться </b> к OBS, оно покажет логин для изменения ваших учетных данных</emp>.<br>",
		"label_config_feedback_text" : "Обратная связь",
		"label_config_a_send" : "послать",
		"label_config_support_text" : "* Если это расширение поможет вам, ваша поддержка будет принята очень хорошо ",
		"label_obs_error_credential" : "<p>Проверьте свои учетные данные и повторите попытку <b class='red-text'> error</b></p>",
		"label_obs_connect"  : "соединять",
		"label_obs_close"  : "закрыть",
		"label_obs_empty"  : "<p>Не оставляйте любое поле <b class='red-text'> пустым</b>!</p>",
		"label_obs_connected" : "<p>OBS <b class='green-text'> подключен</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>Поиск </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>Ищу </b> снова OBS</p>",
		"label_only_broadcast_view" : "<b>Извините за единый взгляд эмитента<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "Не оставляйте пустых полей",
		"tooltip_feedback_ok" : "Спасибо за ваш отзыв, я отвечу на ваши комментарии как можно скорее.",
		"tooltip_feedback_error" : "Извините, но произошла ошибка, и ваш отзыв не может быть отправлен.",
		"tooltip_invalid_format" : "<p>Неверный формат <br> Пожалуйста, проверьте ваш URL</p>",
		"tooltip_config_save" : "<p>Настройки <b class='green-text'> сохранены</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>URL должен иметь следующий формат: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> Лучший и самый простой способ получить публичный URL для вашего localhost должен использовать <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	},
	"th":{
		"label_config_save_credentials" : "บันทึกข้อมูล",
		"label_config_requirements" : "ความต้องการ",
		"label_config_requirements_content" : "- คุณต้องติดตั้งปลั๊กอินต่อไปนี้ <a href='https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/' target='_blank' > OBS websocket </a> <br> - คุณต้องใช้ <a href='https://ngrok.com/' target='_blank'> ngrok.com </a> เพื่อสร้าง URL สาธารณะของ localhost ของคุณ . <br> - เมื่อคุณเข้าถึง ngrok ให้ใช้ <a href='https://dashboard.ngrok.com/get-started' target='_blank'> คำแนะนำเพื่อเรียกใช้ ngrok บนคอมพิวเตอร์ของคุณ </a> และคำสั่งต่อไปนี้เพื่อสร้าง URL ของคุณ:<br><emp>ngrok http {obs port}<br><b>ngrok http 4444</b><br></emp><br>",
		"label_config_credits" : "เครดิต",
		"label_config_usage" : "ใช้",
		"label_config_usage_content" : "- ใช้แผงนี้เพื่อบันทึกข้อมูลรับรองของคุณ <br> - ในแผงควบคุมของ <b> twitch </b> ในแผงส่วนขยายที่ปรากฏ:<br>&nbsp; . ปุ่มสำหรับเริ่ม / หยุดการสตรีมจาก OBS.<br>&nbsp; . ปุ่มเดียวสำหรับแต่ละฉาก.<br>&nbsp; . ปุ่มสำหรับปิดการเชื่อมต่อกับ OBS <br> - <b> เมื่อกระแสข้อมูลเริ่มต้น </b> บนแดชบอร์ด / ช่อง <b> วิดีโอ </b> ของคุณจะมีการซ้อนทับ :<br>&nbsp; . ปุ่มเพื่อหยุดการสตรีม OBS.<br>&nbsp; .  ปุ่มเดียวสำหรับแต่ละฉาก.<br>&nbsp; . ปุ่มเพื่อปิดการเชื่อมต่อกับ OBS.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<emp>* หากส่วนขยาย <b class='red-text'> ไม่สามารถเชื่อมต่อ </b> กับ OBS ได้มันจะแสดงข้อมูลเข้าสู่ระบบเพื่อเปลี่ยนข้อมูลรับรองของคุณ</emp>.<br>",
		"label_config_feedback_text" : "ผลตอบรับ",
		"label_config_a_send" : "ส่ง",
		"label_config_support_text" : "* หากส่วนขยายนี้ช่วยคุณได้รับการสนับสนุนของคุณเป็นอย่างดี ",
		"label_obs_error_credential" : "<p>ตรวจสอบข้อมูลรับรองของคุณแล้วลองอีกครั้ง <b class='red-text'> ข้อผิดพลาด</b></p>",
		"label_obs_connect"  : "ต่อ",
		"label_obs_close"  : "cerrar",
		"label_obs_empty"  : "<p>อย่าปล่อยให้ฟิลด์ใด ๆ <b class='red-text'> ว่าง</b>!</p>",
		"label_obs_connected" : "<p>เชื่อมต่อ OBS <b class='green-text'> แล้ว</b></p>",
		"label_obs_check" : "<p><b class='orange-text'>กำลังค้นหา </b> OBS</p>",
		"label_obs_check_again" : "<p><b class='blue-text'>กำลังมองหา </b> อีกครั้ง OBS</p>",
		"label_only_broadcast_view" : "<b>ขออภัย <br> มุมมองเดียวของผู้ออก<br><br>( •_•)>⌐■-■</b>",
		"tooltip_feedback_empty" : "อย่าเว้นช่องว่างไว้",
		"tooltip_feedback_ok" : "ขอบคุณสำหรับความคิดเห็นของคุณฉันจะตอบความคิดเห็นของคุณโดยเร็วที่สุด.",
		"tooltip_feedback_error" : "ขออภัยมีข้อผิดพลาดและไม่สามารถส่งความคิดเห็นของคุณได้ในขณะนี้.",
		"tooltip_invalid_format" : "<p>	รูปแบบไม่ถูกต้อง <br> โปรดตรวจสอบ URL ของคุณ</p>",
		"tooltip_config_save" : "<p>บันทึกการตั้งค่า <b class='green-text'> แล้ว</b>!</p>",
		"tooltip_config_label_url_tooltiped" : "<p>URL ต้องมีรูปแบบต่อไปนี้: <br> <br> <b> wss://</b>a93a7c2255.ngrok.io <br> <br> วิธีที่ดีที่สุดและง่ายที่สุดในการรับ URL สาธารณะสำหรับคุณ localhost คือการใช้ <a href='https://ngrok.com/' target='_blank'> ngrok.com </a></p>"
	}
};